import type { AuthenticatedNativeStaffWithAdmissionVersion } from "./native-staff-auth";
import type { Env } from "./types";

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const text=(value:unknown,max=512):value is string=>typeof value==="string"&&value.length>0&&value.length<=max&&value.trim()===value;
export type ClientPortalAuthorityV2Command=Readonly<{protocolVersion:2;operationId:string;clientAuthorityId:string;workspaceId:string;
  bindingOperationId:string;issuer:string;subject:string;desiredState:"active"|"revoked";expectedOwnershipEpoch:number;expectedGrantRevision:number;scopes:[]}>;
export type ClientPortalAuthorityV3Command=Readonly<{protocolVersion:3;operationId:string;clientAuthorityId:string;workspaceId:string;
  bindingOperationId:string;issuer:string;subject:string;desiredState:"active"|"revoked";expectedOwnershipEpoch:number;expectedGrantRevision:number;permissions:readonly []|readonly ["operations.service_home.read"]}>;
type ClientPortalAuthorityCommand=ClientPortalAuthorityV2Command|ClientPortalAuthorityV3Command;
type Success=Readonly<{ok:true;protocolVersion:2|3;status:"recorded"|"duplicate";operationId:string;clientAuthorityId:string;workspaceId:string;issuer:string;subject:string;ownershipEpoch:number;grantRevision:number;state:"active"|"revoked";permissions?:readonly string[]}>;
type Failure=Readonly<{ok:false;protocolVersion:2|3;code:string;retryable:boolean}>;
export interface ClientPortalAuthorityV2Binding {applyAuthority(input:ClientPortalAuthorityV2Command):Promise<unknown>;getAuthorityStatus(input:{protocolVersion:2;operationId:string}):Promise<unknown>;applyAuthorityV3?(input:ClientPortalAuthorityV3Command):Promise<unknown>;getAuthorityV3Status?(input:{protocolVersion:3;operationId:string}):Promise<unknown>}
export type AuthorityV2Env=Pick<Env,"OPS_DB"|"CLIENT_PORTAL_AUTHORITY_V2"|"CLIENT_PORTAL_AUTHORITY_V2_OUTBOX_ENABLED">;
export async function enqueueClientPortalAuthorityV2(db:D1Database,actor:AuthenticatedNativeStaffWithAdmissionVersion,input:Omit<ClientPortalAuthorityV2Command,"protocolVersion"|"scopes">&{recipientBindingId:string}){
  if(!UUID.test(input.operationId)||!UUID.test(input.bindingOperationId)||!UUID.test(input.clientAuthorityId)||!UUID.test(input.recipientBindingId)||!text(input.workspaceId,200)||!text(input.issuer)||!text(input.subject)
    ||!Number.isSafeInteger(input.expectedOwnershipEpoch)||!Number.isSafeInteger(input.expectedGrantRevision)
    ||input.expectedOwnershipEpoch<0||input.expectedGrantRevision<0||(input.desiredState!=="active"&&input.desiredState!=="revoked")
    ||(input.expectedOwnershipEpoch===0&&(input.desiredState!=="active"||input.expectedGrantRevision!==0))
    ||(input.desiredState==="revoked"&&input.expectedGrantRevision===0)
    ||!Number.isFinite(Date.parse(actor.verifiedUntil))||Date.parse(actor.verifiedUntil)<=Date.now())throw Error("portal_authority_v2_denied");
  const operationId=input.operationId,session=db.withSession("first-primary");
  const generation=await session.prepare(`SELECT generation FROM native_directory_grant_generations WHERE staff_id=?`)
    .bind(actor.identity.staffId).first<number>("generation");
  if(generation===null||!Number.isSafeInteger(generation)||generation<1)throw Error("portal_authority_v2_denied");
  try { await session.batch([
    session.prepare(`INSERT INTO client_portal_authority_v2_outbox(operation_id,binding_operation_id,client_authority_id,workspace_id,recipient_binding_id,issuer,subject,desired_state,expected_ownership_epoch,expected_grant_revision,authorized_by_staff_id,authorized_access_subject,authorized_admission_version,authorized_profile_version,authorized_grant_generation,protocol_version,permissions_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(operationId,input.bindingOperationId,input.clientAuthorityId,input.workspaceId,input.recipientBindingId,input.issuer,input.subject,input.desiredState,input.expectedOwnershipEpoch,input.expectedGrantRevision,actor.identity.staffId,actor.identity.verifiedAccessSubject,actor.admissionVersion,actor.identity.profileVersion,generation,2,"[]"),
    session.prepare(`INSERT INTO client_portal_authority_v2_outbox_audit(operation_id,action,authorized_by_staff_id,authorized_grant_generation) VALUES(?,'v2.intent.enqueued',?,?)`).bind(operationId,actor.identity.staffId,generation),
  ]); } catch {
    const prior=await session.prepare(`SELECT binding_operation_id,client_authority_id,workspace_id,recipient_binding_id,issuer,subject,desired_state,expected_ownership_epoch,expected_grant_revision,protocol_version,permissions_json FROM client_portal_authority_v2_outbox WHERE operation_id=?`).bind(operationId).first<Record<string,unknown>>();
    if(!prior||prior.binding_operation_id!==input.bindingOperationId||prior.client_authority_id!==input.clientAuthorityId||prior.workspace_id!==input.workspaceId||prior.recipient_binding_id!==input.recipientBindingId||prior.issuer!==input.issuer||prior.subject!==input.subject||prior.desired_state!==input.desiredState||prior.expected_ownership_epoch!==input.expectedOwnershipEpoch||prior.expected_grant_revision!==input.expectedGrantRevision||prior.protocol_version!==2||prior.permissions_json!=="[]")throw Error("portal_authority_v2_denied");
    return {operationId,replayed:true};
  }
  return {operationId,replayed:false};
}
/** Protocol 3 changes only the explicit descriptive-home permission.  It uses
 * the exact same authority outbox, principal revision and staff/recipient
 * guards as v2; it never first creates a v2 grant and patches it later. */
export async function enqueueClientPortalAuthorityV3(db:D1Database,actor:AuthenticatedNativeStaffWithAdmissionVersion,input:Omit<ClientPortalAuthorityV3Command,"protocolVersion"|"permissions">&{recipientBindingId:string;permissions:readonly []|readonly ["operations.service_home.read"]}){
  const permissions=input.permissions.length===0?"[]":input.permissions.length===1&&input.permissions[0]==="operations.service_home.read"?'["operations.service_home.read"]':null;
  if(!permissions||!UUID.test(input.operationId)||!UUID.test(input.bindingOperationId)||!UUID.test(input.clientAuthorityId)||!UUID.test(input.recipientBindingId)||!text(input.workspaceId,200)||!text(input.issuer)||!text(input.subject)
    ||!Number.isSafeInteger(input.expectedOwnershipEpoch)||!Number.isSafeInteger(input.expectedGrantRevision)||input.expectedOwnershipEpoch<0||input.expectedGrantRevision<0||(input.desiredState!=="active"&&input.desiredState!=="revoked")
    ||(input.expectedOwnershipEpoch===0&&(input.desiredState!=="active"||input.expectedGrantRevision!==0))||(input.desiredState==="revoked"&&(input.expectedGrantRevision===0||permissions!=="[]"))
    ||!Number.isFinite(Date.parse(actor.verifiedUntil))||Date.parse(actor.verifiedUntil)<=Date.now())throw Error("portal_authority_v3_denied");
  const session=db.withSession("first-primary"),generation=await session.prepare(`SELECT generation FROM native_directory_grant_generations WHERE staff_id=?`).bind(actor.identity.staffId).first<number>("generation");
  if(generation===null||!Number.isSafeInteger(generation)||generation<1)throw Error("portal_authority_v3_denied");
  try{await session.batch([
    session.prepare(`INSERT INTO client_portal_authority_v2_outbox(operation_id,binding_operation_id,client_authority_id,workspace_id,recipient_binding_id,issuer,subject,desired_state,expected_ownership_epoch,expected_grant_revision,authorized_by_staff_id,authorized_access_subject,authorized_admission_version,authorized_profile_version,authorized_grant_generation,protocol_version,permissions_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(input.operationId,input.bindingOperationId,input.clientAuthorityId,input.workspaceId,input.recipientBindingId,input.issuer,input.subject,input.desiredState,input.expectedOwnershipEpoch,input.expectedGrantRevision,actor.identity.staffId,actor.identity.verifiedAccessSubject,actor.admissionVersion,actor.identity.profileVersion,generation,3,permissions),
    session.prepare(`INSERT INTO client_portal_authority_v2_outbox_audit(operation_id,action,authorized_by_staff_id,authorized_grant_generation) VALUES(?,'v2.intent.enqueued',?,?)`).bind(input.operationId,actor.identity.staffId,generation),
  ]);}catch{
    const prior=await session.prepare(`SELECT binding_operation_id,client_authority_id,workspace_id,recipient_binding_id,issuer,subject,desired_state,expected_ownership_epoch,expected_grant_revision,protocol_version,permissions_json FROM client_portal_authority_v2_outbox WHERE operation_id=?`).bind(input.operationId).first<Record<string,unknown>>();
    if(!prior||prior.binding_operation_id!==input.bindingOperationId||prior.client_authority_id!==input.clientAuthorityId||prior.workspace_id!==input.workspaceId||prior.recipient_binding_id!==input.recipientBindingId||prior.issuer!==input.issuer||prior.subject!==input.subject||prior.desired_state!==input.desiredState||prior.expected_ownership_epoch!==input.expectedOwnershipEpoch||prior.expected_grant_revision!==input.expectedGrantRevision||prior.protocol_version!==3||prior.permissions_json!==permissions)throw Error("portal_authority_v3_denied");
    return{operationId:input.operationId,replayed:true};
  }return{operationId:input.operationId,replayed:false};
}
type Row={operation_id:string;binding_operation_id:string;client_authority_id:string;workspace_id:string;issuer:string;subject:string;desired_state:"active"|"revoked";expected_ownership_epoch:number;expected_grant_revision:number;protocol_version:2|3;permissions_json:"[]"|'["operations.service_home.read"]';attempt_count:number;claim_token:string};
const exact=(value:unknown,keys:string[])=>{if(!value||typeof value!=="object")return null;try{if(Array.isArray(value)||Object.getPrototypeOf(value)!==Object.prototype||Reflect.ownKeys(value).some(key=>typeof key!=="string"))return null;const descriptors=Object.getOwnPropertyDescriptors(value),names=Object.keys(descriptors);if(names.length!==keys.length||names.some(key=>!keys.includes(key)||!("value" in descriptors[key]!)))return null;return Object.fromEntries(names.map(key=>[key,descriptors[key]!.value])) as Record<string,unknown>;}catch{return null;}};
function success(v:unknown,c:ClientPortalAuthorityCommand,status=false):v is Success {const v3=c.protocolVersion===3,x=exact(v,["ok","protocolVersion","status","operationId","clientAuthorityId","workspaceId","issuer","subject","ownershipEpoch","grantRevision","state",...(v3?["permissions"]:[]),...(status?[]:["replayed"])]);return !!x&&x.ok===true&&x.protocolVersion===c.protocolVersion&&(x.status==="recorded"||x.status==="duplicate")&&x.operationId===c.operationId&&x.clientAuthorityId===c.clientAuthorityId&&x.workspaceId===c.workspaceId&&x.issuer===c.issuer&&x.subject===c.subject&&x.ownershipEpoch===(c.expectedOwnershipEpoch||1)&&x.grantRevision===c.expectedGrantRevision+1&&x.state===c.desiredState&&(status||typeof x.replayed==="boolean")&&(!v3||(Array.isArray(x.permissions)&&x.permissions.length===c.permissions.length&&x.permissions.every((p,index)=>p===c.permissions[index])));}
function failure(v:unknown,protocol:2|3):Failure|null {const x=exact(v,["ok","protocolVersion","code","retryable"]);return x&&x.ok===false&&x.protocolVersion===protocol&&typeof x.code==="string"&&typeof x.retryable==="boolean"?x as Failure:null;}
export async function dispatchNextClientPortalAuthorityV2(env:AuthorityV2Env,operationId?:string):Promise<{status:"disabled"|"idle"|"acknowledged"|"retry"|"dead";operationId?:string;code?:string}>{
  if(env.CLIENT_PORTAL_AUTHORITY_V2_OUTBOX_ENABLED!=="true")return{status:"disabled"}; if(!env.CLIENT_PORTAL_AUTHORITY_V2)return{status:"retry",operationId:"configuration",code:"configuration"};
  if(operationId!==undefined&&!UUID.test(operationId))return{status:"idle"};
  const db=env.OPS_DB.withSession("first-primary"),token=crypto.randomUUID(); await db.prepare(`UPDATE client_portal_authority_v2_outbox SET state='dispatching',claim_token=?,claim_until=strftime('%Y-%m-%dT%H:%M:%fZ','now','+2 minutes'),updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE operation_id=(SELECT operation_id FROM client_portal_authority_v2_outbox WHERE ${operationId===undefined?"":"operation_id=? AND "}((state IN ('pending','retry') AND next_attempt_at<=strftime('%Y-%m-%dT%H:%M:%fZ','now')) OR (state='dispatching' AND claim_until<=strftime('%Y-%m-%dT%H:%M:%fZ','now'))) ORDER BY created_at LIMIT 1)`).bind(token,...(operationId===undefined?[]:[operationId])).run();
  const row=await db.prepare(`SELECT operation_id,binding_operation_id,client_authority_id,workspace_id,issuer,subject,desired_state,expected_ownership_epoch,expected_grant_revision,protocol_version,permissions_json,attempt_count,claim_token FROM client_portal_authority_v2_outbox WHERE state='dispatching' AND claim_token=?`).bind(token).first<Row>(); if(!row)return{status:"idle"};
  if(row.desired_state==="active"){const permitted=await db.prepare(`SELECT 1 FROM client_portal_authority_v2_outbox o JOIN client_portal_workspace_binding_outbox b ON b.operation_id=o.binding_operation_id JOIN client_portal_workspace_binding_selections s ON s.selection_id=b.operation_id JOIN native_staff_admissions a ON a.staff_id=o.authorized_by_staff_id JOIN native_staff_profiles p ON p.staff_id=a.staff_id JOIN native_directory_grant_generations g ON g.staff_id=a.staff_id WHERE o.operation_id=? AND a.active=1 AND a.bound_access_subject=o.authorized_access_subject AND a.version=o.authorized_admission_version AND p.version=o.authorized_profile_version AND g.generation=o.authorized_grant_generation AND EXISTS(SELECT 1 FROM staff_role_assignments r WHERE r.staff_id=a.staff_id AND r.role_id='role-owner' AND r.scope='global') AND EXISTS(SELECT 1 FROM native_directory_grants x WHERE x.staff_id=a.staff_id AND x.permission='directory.portal_access.manage' AND x.effect='allow' AND x.active=1 AND (x.scope_kind='global' OR (x.scope_kind='resource' AND x.resource_id=s.record_id))) AND NOT EXISTS(SELECT 1 FROM native_directory_grants d WHERE d.staff_id=a.staff_id AND d.permission='directory.portal_access.manage' AND d.effect='deny' AND d.active=1 AND (d.scope_kind='global' OR (d.scope_kind='resource' AND d.resource_id=s.record_id) OR (d.scope_kind='business_area' AND EXISTS(SELECT 1 FROM native_directory_resource_scopes z WHERE z.record_id=s.record_id AND z.active=1 AND z.business_area_id=d.business_area_id)) OR (d.scope_kind='division' AND EXISTS(SELECT 1 FROM native_directory_resource_scopes z WHERE z.record_id=s.record_id AND z.active=1 AND z.division_id=d.division_id))))`).bind(row.operation_id).first();if(!permitted){await db.prepare(`UPDATE client_portal_authority_v2_outbox SET state='retry',attempt_count=attempt_count+1,last_error_code='authorization-stale',next_attempt_at=strftime('%Y-%m-%dT%H:%M:%fZ','now','+5 minutes'),claim_token=NULL,claim_until=NULL WHERE operation_id=? AND state='dispatching' AND claim_token=?`).bind(row.operation_id,token).run();return{status:"retry",operationId:row.operation_id,code:"authorization-stale"};}}
  // An identity binding can be disabled, expire, or lose its customer relation
  // after enqueue. Never dispatch a new active grant from that stale intent.
  if(row.desired_state==="active"){
    const recipient=await db.prepare(`SELECT 1 FROM client_portal_authority_v2_outbox o
      JOIN client_portal_workspace_binding_selections selection ON selection.selection_id=o.binding_operation_id
      JOIN client_onboarding_recipient_identity_bindings identity ON identity.binding_id=o.recipient_binding_id
      WHERE o.operation_id=? AND identity.status='active'
        AND (identity.expires_at IS NULL OR identity.expires_at>strftime('%Y-%m-%dT%H:%M:%fZ','now'))
        AND identity.access_issuer=o.issuer AND identity.access_subject=o.subject
        AND (identity.target_client_record_id=selection.record_id
          OR EXISTS(SELECT 1 FROM operations_directory_client_organizations relation
            WHERE relation.client_record_id=identity.target_client_record_id
              AND relation.organization_record_id=selection.record_id))`).bind(row.operation_id).first();
    if(!recipient){
      await db.prepare(`UPDATE client_portal_authority_v2_outbox SET state='retry',attempt_count=attempt_count+1,last_error_code='recipient-stale',next_attempt_at=strftime('%Y-%m-%dT%H:%M:%fZ','now','+5 minutes'),claim_token=NULL,claim_until=NULL WHERE operation_id=? AND state='dispatching' AND claim_token=?`).bind(row.operation_id,token).run();
      return{status:"retry",operationId:row.operation_id,code:"recipient-stale"};
    }
  }
  const command:ClientPortalAuthorityCommand=row.protocol_version===2?{protocolVersion:2,operationId:row.operation_id,clientAuthorityId:row.client_authority_id,workspaceId:row.workspace_id,bindingOperationId:row.binding_operation_id,issuer:row.issuer,subject:row.subject,desiredState:row.desired_state,expectedOwnershipEpoch:row.expected_ownership_epoch,expectedGrantRevision:row.expected_grant_revision,scopes:[]}:{protocolVersion:3,operationId:row.operation_id,clientAuthorityId:row.client_authority_id,workspaceId:row.workspace_id,bindingOperationId:row.binding_operation_id,issuer:row.issuer,subject:row.subject,desiredState:row.desired_state,expectedOwnershipEpoch:row.expected_ownership_epoch,expectedGrantRevision:row.expected_grant_revision,permissions:row.permissions_json==="[]"?[]:["operations.service_home.read"]};let receipt:unknown,ambiguous=false;
  try{receipt=command.protocolVersion===2?await env.CLIENT_PORTAL_AUTHORITY_V2.applyAuthority(command):env.CLIENT_PORTAL_AUTHORITY_V2.applyAuthorityV3?await env.CLIENT_PORTAL_AUTHORITY_V2.applyAuthorityV3(command):undefined;}catch{ambiguous=true;}if(!success(receipt,command)){if(!failure(receipt,command.protocolVersion))ambiguous=true;if(ambiguous)try{receipt=command.protocolVersion===2?await env.CLIENT_PORTAL_AUTHORITY_V2.getAuthorityStatus({protocolVersion:2,operationId:row.operation_id}):env.CLIENT_PORTAL_AUTHORITY_V2.getAuthorityV3Status?await env.CLIENT_PORTAL_AUTHORITY_V2.getAuthorityV3Status({protocolVersion:3,operationId:row.operation_id}):undefined;}catch{}}
  if(success(receipt,command,ambiguous)){const epoch=command.expectedOwnershipEpoch||1;await db.batch([db.prepare(`INSERT INTO client_portal_authority_v2_outbox_receipts(operation_id,client_authority_id,workspace_id,issuer,subject,ownership_epoch,grant_revision,resulting_state,acknowledged_claim_token,protocol_version,permissions_json) VALUES(?,?,?,?,?,?,?,?,?,?,?)`).bind(row.operation_id,row.client_authority_id,row.workspace_id,row.issuer,row.subject,epoch,command.expectedGrantRevision+1,row.desired_state,token,command.protocolVersion,row.permissions_json),db.prepare(`UPDATE client_portal_authority_v2_outbox SET state='acknowledged',attempt_count=attempt_count+1,claim_token=NULL,claim_until=NULL,acknowledged_claim_token=?,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE operation_id=? AND state='dispatching' AND claim_token=?`).bind(token,row.operation_id,token)]);const state=await db.prepare(`SELECT state FROM client_portal_authority_v2_outbox WHERE operation_id=? AND acknowledged_claim_token=?`).bind(row.operation_id,token).first<string>("state");return state==="acknowledged"?{status:"acknowledged",operationId:row.operation_id}:{status:"retry",operationId:row.operation_id,code:"lease-lost"};}
  const fail=failure(receipt,command.protocolVersion),dead=!!fail&&!fail.retryable;await db.prepare(`UPDATE client_portal_authority_v2_outbox SET state=?,attempt_count=attempt_count+1,last_error_code=?,next_attempt_at=strftime('%Y-%m-%dT%H:%M:%fZ','now','+30 seconds'),claim_token=NULL,claim_until=NULL,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE operation_id=? AND state='dispatching' AND claim_token=?`).bind(dead?"dead":"retry",fail?.code??"temporarily-unavailable",row.operation_id,token).run();const state=await db.prepare(`SELECT state FROM client_portal_authority_v2_outbox WHERE operation_id=?`).bind(row.operation_id).first<string>("state");return{status:state==="dead"?"dead":"retry",operationId:row.operation_id,code:fail?.code??"temporarily-unavailable"};
}
