import { HTTPException } from "hono/http-exception";
import type { DeliveryItem } from "@ltds/shared";
import { hashAccessCode, randomToken, sha256 } from "./crypto";
import { requirePermission, sqlScope } from "./acl";
import { auditStatement } from "./request-security";
import type { Env, StaffPrincipal } from "./types";

const encoder = new TextEncoder(); const decoder = new TextDecoder("utf-8", { fatal: true });
const MIME: Record<string,string> = { avif:"image/avif",bmp:"image/bmp",gif:"image/gif",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",tif:"image/tiff",tiff:"image/tiff",webp:"image/webp",mp4:"video/mp4",m4v:"video/x-m4v",webm:"video/webm",mov:"video/quicktime",mp3:"audio/mpeg",m4a:"audio/mp4",wav:"audio/wav",ogg:"audio/ogg",pdf:"application/pdf",txt:"text/plain; charset=utf-8",csv:"text/csv; charset=utf-8",json:"application/json; charset=utf-8" };

function b64(bytes: Uint8Array): string { let value=""; for(const byte of bytes)value+=String.fromCharCode(byte); return btoa(value).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,""); }
export function encodeRef(value:string):string{return b64(encoder.encode(value));}
export function decodeRef(value:string):string{if(!/^[A-Za-z0-9_-]+$/.test(value))throw new HTTPException(400,{message:"Invalid item reference"});try{const raw=atob(value.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(value.length/4)*4,"="));return validateRelative(decoder.decode(Uint8Array.from(raw,c=>c.charCodeAt(0))));}catch(error){if(error instanceof HTTPException)throw error;throw new HTTPException(400,{message:"Invalid item reference"});}}
function validateRelative(value:string):string{if(!value||value.startsWith("/")||value.includes("\\")||/[\0-\x1f\x7f]/.test(value))throw new HTTPException(400,{message:"Invalid item path"});const parts=value.split("/");if(parts.some(part=>!part||part==="."||part===".."||part.toLowerCase()==="dump")||parts[0]?.toLowerCase()==="_ltds")throw new HTTPException(404,{message:"Item not found"});return parts.join("/");}
export function normalizePrefix(value:string):string{const prefix=value.trim().replace(/\\/g,"/").replace(/^\/+/,"").replace(/\/{2,}/g,"/").replace(/\/$/,"");if(!prefix||prefix.split("/").some(part=>!part||part==="."||part===".."||part.toLowerCase()==="dump")||prefix.split("/")[0]?.toLowerCase()==="_ltds")throw new HTTPException(400,{message:"Folder prefix is invalid"});return `${prefix}/`;}
function hidden(key:string):boolean{const parts=key.replace(/\\/g,"/").split("/").filter(Boolean);return parts.some(part=>part.toLowerCase()==="dump")||parts[0]?.toLowerCase()==="_ltds";}
function ext(key:string):string{const name=key.split("/").pop()||"";return name.includes(".")?(name.split(".").pop()||"").toLowerCase():"";}
export function mime(key:string):string{return MIME[ext(key)]||"application/octet-stream";}
export function mediaKind(key:string):DeliveryItem["kind"]{const value=mime(key);if(value.startsWith("image/"))return"image";if(value.startsWith("video/"))return"video";if(value.startsWith("audio/"))return"audio";if(value==="application/pdf")return"pdf";if(value.startsWith("text/")||value.startsWith("application/json"))return"text";return"other";}

interface FolderAssociation { division_id: string; r2_prefix: string }

async function browseRoots(env:Env,principal:StaffPrincipal):Promise<{global:boolean;roots:Array<{prefix:string;name:string;divisionId:string}>}>{const scope=await sqlScope(env,principal,"delivery.browse");if(scope.global)return{global:true,roots:[]};if(!scope.divisions.length)return{global:false,roots:[]};const result=await env.OPS_DB.prepare(`SELECT pf.r2_prefix,p.name,pf.division_id FROM project_folders pf LEFT JOIN pa_projects p ON p.id=pf.project_id WHERE pf.division_id IN (${scope.divisions.map(()=>"?").join(",")}) ORDER BY p.name,pf.r2_prefix`).bind(...scope.divisions).all<{r2_prefix:string;name:string|null;division_id:string}>();return{global:false,roots:result.results.map(row=>({prefix:normalizePrefix(row.r2_prefix),name:row.name||row.r2_prefix,divisionId:row.division_id}))};}

export function resolveDivisionAssociation(prefix:string,associations:FolderAssociation[]):string|null{const matches=associations.map(row=>({divisionId:row.division_id,prefix:normalizePrefix(row.r2_prefix)})).filter(row=>prefix.startsWith(row.prefix));if(!matches.length)return null;const longest=Math.max(...matches.map(row=>row.prefix.length));const divisions=[...new Set(matches.filter(row=>row.prefix.length===longest).map(row=>row.divisionId))];if(divisions.length!==1)throw new HTTPException(409,{message:"Folder is associated with multiple divisions and requires review"});return divisions[0]!;}

async function inferDivisionId(env:Env,prefix:string):Promise<string|null>{const associations=await env.OPS_DB.prepare("SELECT division_id,r2_prefix FROM project_folders ORDER BY length(r2_prefix) DESC").all<FolderAssociation>();return resolveDivisionAssociation(prefix,associations.results);}

export function resolveShareExpiration(value:string|null|undefined,maxDays:number,now=Date.now()):string|null{if(value===null||value===undefined||value==="")return null;const requested=new Date(value);if(Number.isNaN(requested.getTime())||requested.getTime()<=now||requested.getTime()>now+maxDays*86400000)throw new HTTPException(400,{message:`Expiration must be within ${maxDays} days`});return requested.toISOString();}

export async function listDeliveryFolder(env:Env,principal:StaffPrincipal,prefixValue:string,cursor?:string){await requirePermission(env,principal,"delivery.browse");const access=await browseRoots(env,principal);if(!access.global&&!prefixValue)return{prefix:"",folders:access.roots.map(root=>({id:encodeRef(root.prefix.slice(0,-1)),prefix:root.prefix,name:root.name})),files:[],nextCursor:null};const prefix=prefixValue?normalizePrefix(prefixValue):"";if(!access.global&&!access.roots.some(root=>prefix.startsWith(root.prefix)))throw new HTTPException(404,{message:"Folder not found"});const listed=await env.DATA_BUCKET.list({prefix,delimiter:"/",limit:500,cursor});return{prefix,folders:listed.delimitedPrefixes.filter(value=>!hidden(value)).map(value=>({id:encodeRef(value.slice(0,-1)),prefix:value,name:value.slice(prefix.length).replace(/\/$/,"")})),files:listed.objects.filter(object=>object.key!==prefix&&!object.key.endsWith("/")&&!hidden(object.key)).map(object=>{const id=encodeRef(object.key);const kind=mediaKind(object.key);return{id,name:object.key.slice(prefix.length),kind,size:object.size,uploadedAt:object.uploaded.toISOString(),previewUrl:["image","video","audio","pdf","text"].includes(kind)?`/api/delivery/items/${id}/preview`:undefined,thumbnailUrl:kind==="image"?`/api/delivery/items/${id}/thumbnail`:undefined,downloadUrl:`/api/delivery/items/${id}/download`};}),nextCursor:listed.truncated?listed.cursor:null};}

export async function authorizeItem(env:Env,principal:StaffPrincipal,itemRef:string):Promise<string>{await requirePermission(env,principal,"delivery.browse");const key=decodeRef(itemRef);if(hidden(key))throw new HTTPException(404,{message:"Item not found"});const access=await browseRoots(env,principal);if(!access.global&&!access.roots.some(root=>key.startsWith(root.prefix)))throw new HTTPException(404,{message:"Item not found"});return key;}

export interface ShareInput{clientName?:string;projectName?:string;r2Prefix?:string;projectId?:string;externalRef?:string;label?:string;accessCode?:string;generateAccessCode?:boolean;expiresAt?:string|null;}
export function deriveShareMetadata(prefix:string,input:Pick<ShareInput,"clientName"|"projectName">={}):{clientName:string;projectName:string}{const folderName=normalizePrefix(prefix).slice(0,-1).split("/").pop()||"Shared folder";return{clientName:input.clientName?.trim()||folderName,projectName:input.projectName?.trim()||folderName};}
export async function createDeliveryShare(env:Env,request:Request,principal:StaffPrincipal,input:ShareInput,idempotencyKey:string){if(!idempotencyKey||idempotencyKey.length>120)throw new HTTPException(400,{message:"Idempotency-Key is required"});if(!input.r2Prefix)throw new HTTPException(400,{message:"r2Prefix is required"});const prefix=normalizePrefix(input.r2Prefix);const{clientName,projectName}=deriveShareMetadata(prefix,input);const access=await browseRoots(env,principal);if(!access.global&&!access.roots.some(root=>prefix.startsWith(root.prefix)))throw new HTTPException(404,{message:"Folder not found"});const existing=input.projectId?await env.DELIVERY_DB.prepare("SELECT id,division_id,r2_prefix FROM projects WHERE id=?").bind(input.projectId).first<{id:string;division_id:string|null;r2_prefix:string}>():null;if(existing&&normalizePrefix(existing.r2_prefix)!==prefix)throw new HTTPException(409,{message:"Project folder does not match"});const associatedDivision=await inferDivisionId(env,prefix);if(existing?.division_id&&associatedDivision&&existing.division_id!==associatedDivision)throw new HTTPException(409,{message:"Project division does not match the folder association"});const divisionId=existing?.division_id||associatedDivision;if(!access.global&&!divisionId)throw new HTTPException(404,{message:"Folder not found"});await requirePermission(env,principal,"delivery.share.create",{divisionId},true);const owner=Boolean(await env.OPS_DB.prepare("SELECT 1 ok FROM staff_role_assignments WHERE staff_id=? AND role_id='role-owner' AND scope='global'").bind(principal.id).first());const expiresAt=resolveShareExpiration(input.expiresAt,owner?365:90);
  const replay=await env.DELIVERY_DB.prepare("SELECT s.id,s.public_id FROM shares s WHERE s.created_by_type='staff' AND s.created_by_id=? AND s.idempotency_key=?").bind(principal.id,idempotencyKey).first<{id:string;public_id:string}>();if(replay)return{id:replay.id,shareUrl:`${env.DELIVERY_BASE_URL.replace(/\/$/,"")}/s/${replay.public_id}`,accessCode:null,idempotentReplay:true};
  const secret=randomToken(32),publicId=randomToken(16),tokenHash=await sha256(secret);let accessCode=input.generateAccessCode?randomToken(12):(input.accessCode?.trim()||null);if(accessCode&&accessCode.length<8)throw new HTTPException(400,{message:"Access code must be at least eight characters"});const password=accessCode?await hashAccessCode(accessCode,env.DELIVERY_ACCESS_CODE_PEPPER):null;const projectId=input.projectId||crypto.randomUUID(),shareId=crypto.randomUUID();const deliveryAudit=env.DELIVERY_DB.prepare("INSERT INTO audit_log (actor_type,actor_id,action,entity_type,entity_id,details_json) VALUES ('staff',?,'share.created','share',?,?)").bind(principal.id,shareId,JSON.stringify({divisionId,r2Prefix:prefix,projectId}));const statements:D1PreparedStatement[]=[];if(!existing)statements.push(env.DELIVERY_DB.prepare("INSERT INTO projects (id,external_ref,client_name,project_name,r2_prefix,division_id,created_by) VALUES (?,?,?,?,?,?,NULL)").bind(projectId,input.externalRef?.trim()||null,clientName,projectName,prefix,divisionId));statements.push(env.DELIVERY_DB.prepare(`INSERT INTO shares (id,project_id,token_hash,public_id,label,password_hash,password_salt,password_iterations,expires_at,created_by_type,created_by_id,idempotency_key,share_version) VALUES (?,?,?,?,?,?,?,?,?,'staff',?,?,2)`).bind(shareId,projectId,tokenHash,publicId,input.label?.trim()||null,password?.hash||null,password?.salt||null,password?.iterations||null,expiresAt,principal.id,idempotencyKey),deliveryAudit);await env.DELIVERY_DB.batch(statements);const opsAudit=await auditStatement(env,request,principal,"delivery.share.created","share",shareId,divisionId,{projectId,r2Prefix:prefix,expiresAt});await env.OPS_DB.batch([opsAudit]);return{id:shareId,shareUrl:`${env.DELIVERY_BASE_URL.replace(/\/$/,"")}/s/${publicId}#${secret}`,accessCode:input.generateAccessCode?accessCode:null,idempotentReplay:false};}

export async function listDeliveryShares(env:Env,principal:StaffPrincipal){await requirePermission(env,principal,"delivery.share.audit");const scope=await sqlScope(env,principal,"delivery.share.audit");if(scope.deniedGlobal)return[];let where="1=1",values:unknown[]=[];if(!scope.global){if(!scope.divisions.length)return[];where=`p.division_id IN (${scope.divisions.map(()=>"?").join(",")})`;values=scope.divisions;}const result=await env.DELIVERY_DB.prepare(`SELECT s.id,s.public_id,s.label,s.expires_at,s.revoked_at,s.created_at,s.last_accessed_at,s.access_count,(s.password_hash IS NOT NULL) password_protected,p.client_name,p.project_name,p.r2_prefix,p.division_id FROM shares s JOIN projects p ON p.id=s.project_id WHERE ${where} ORDER BY s.created_at DESC LIMIT 200`).bind(...values).all();return result.results;}

export async function revokeDeliveryShare(env:Env,request:Request,principal:StaffPrincipal,shareId:string){const share=await env.DELIVERY_DB.prepare("SELECT s.id,p.division_id FROM shares s JOIN projects p ON p.id=s.project_id WHERE s.id=?").bind(shareId).first<{id:string;division_id:string|null}>();if(!share)throw new HTTPException(404,{message:"Share not found"});await requirePermission(env,principal,"delivery.share.revoke",{divisionId:share.division_id},true);const result=await env.DELIVERY_DB.batch([env.DELIVERY_DB.prepare("UPDATE shares SET revoked_at=datetime('now') WHERE id=? AND revoked_at IS NULL").bind(shareId),env.DELIVERY_DB.prepare("INSERT INTO audit_log (actor_type,actor_id,action,entity_type,entity_id) VALUES ('staff',?,'share.revoked','share',?)").bind(principal.id,shareId)]);if(!result[0]?.meta.changes)throw new HTTPException(404,{message:"Share not found or already revoked"});await env.OPS_DB.batch([await auditStatement(env,request,principal,"delivery.share.revoked","share",shareId,share.division_id)]);}
