import { Hono } from "hono";
import { HTTPException } from "hono/http-exception";
import { secureHeaders } from "hono/secure-headers";
import { z } from "zod";
import { type Permission } from "@ltds/shared";
import { authenticateStaff } from "./auth";
import { airspaceView, markAirspaceStaleAndPurge, rebuildOperationAirspaceMatches, refreshSua, refreshTfrs } from "./airspace";
import { hasLocalGlobalAllow, isAdministrator, permissionKeys, requirePermission, sqlScope } from "./acl";
import { consumeFileEvents, reconcileFileIndex, refreshStreamStatuses, type R2Notification } from "./file-events";
import { authorizeItem, createDeliveryShare, decodeRef, encodeRef, getActiveDeliveryShare, listDeliveryFolder, listDeliveryShares, mediaKind, revokeDeliveryShare } from "./delivery";
import { syncProjectAlpha } from "./project-alpha";
import { projectAlphaHealthIsStale } from "./integration-health";
import { auditStatement, csrfToken, requireMutationSecurity } from "./request-security";
import type { Env, StaffPrincipal } from "./types";
import { employeePermissions, paCalendarFilter, paProjectFilter, paResourceFilter } from "./visibility";
import { deleteAlias, resolveAliasKey, upsertAlias } from "./aliases";
import { executeSourceDelete, previewSourceDelete } from "./source-delete";
import { servePreparedArtifact, type PreparedArtifactVariant } from "./prepared-artifact";
import { runRetention } from "./retention";
import { listTrash, purgeTrash, r2PurgeEnabled, restoreTombstone } from "./trash";
import { processR2OperationJobs, purgeReplacementRecovery, registerR2CrudRoutes } from "./r2-crud";
import { requiresAdministratorForMutation } from "./r2-crud-validation";
import { enqueueExpiringNotifications, processClientPortalRequestNotifications, processDeliveryNotifications } from "./notifications";
import { createIncomingStaffRouter, dispatchIncomingPublicRequest } from "./incoming";
import { incomingUploadsCapability } from "./incoming-policy";
import { servePdfSourceFile, serveSourceFile } from "./source-file";
import { directDeliveryUploadsCapability } from "./direct-upload-policy";
import { isFrameableOperationsPdfRequest } from "./frame-policy";
import { dropboxImportCapability, registerDropboxImportRoutes } from "./dropbox-import-routes";
import { cleanupDropboxImports } from "./dropbox-import";
import { effectiveStaffAccessControls, STAFF_ACCESS_CONTROLS, staffAccessControlEffect, type StaffAccessControl } from "./staff-access-controls";

type Variables={principal:StaffPrincipal;administrator:boolean};
const app=new Hono<{Bindings:Env;Variables:Variables}>();

const lockedSecurityHeaders=secureHeaders({contentSecurityPolicy:{defaultSrc:["'self'"],imgSrc:["'self'","https://ledgetopdroneservices.com","data:"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],connectSrc:["'self'","https://*.r2.cloudflarestorage.com"],mediaSrc:["'self'","blob:"],frameAncestors:["'none'"],baseUri:["'none'"],objectSrc:["'none'"],formAction:["'self'"]},referrerPolicy:"no-referrer",xContentTypeOptions:"nosniff",xFrameOptions:"DENY",xXssProtection:false});
const frameablePdfSecurityHeaders=secureHeaders({contentSecurityPolicy:{defaultSrc:["'self'"],imgSrc:["'self'","https://ledgetopdroneservices.com","data:"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],connectSrc:["'self'","https://*.r2.cloudflarestorage.com"],mediaSrc:["'self'","blob:"],frameAncestors:["'self'"],baseUri:["'none'"],objectSrc:["'none'"],formAction:["'self'"]},referrerPolicy:"no-referrer",xContentTypeOptions:"nosniff",xFrameOptions:"SAMEORIGIN",xXssProtection:false});
app.use("*",(c,next)=>isFrameableOperationsPdfRequest(c.req.method,c.req.path)?frameablePdfSecurityHeaders(c,next):lockedSecurityHeaders(c,next));
app.use("*",async(c,next)=>{if(c.env.ENVIRONMENT==="production"&&new URL(c.req.url).host!==c.env.EXPECTED_HOST)return c.json({error:"Not found"},404);await next();c.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");c.header("X-Robots-Tag","noindex, nofollow");if(c.req.path.startsWith("/api/")){c.header("Cloudflare-CDN-Cache-Control","no-store");if(!c.res.headers.has("Cache-Control"))c.header("Cache-Control","no-store");}});
app.use("/api/*",async(c,next)=>{const principal=await authenticateStaff(c.req.raw,c.env),administrator=await isAdministrator(c.env,principal);c.set("principal",principal);c.set("administrator",administrator);if(["POST","PUT","PATCH","DELETE"].includes(c.req.method)){if(requiresAdministratorForMutation(c.req.method,c.req.path)&&!administrator)throw new HTTPException(403,{message:"Administrator access required for this change"});await requireMutationSecurity(c.req.raw,c.env,principal);}await next();});
app.use("/api/admin/*",async(c,next)=>{if(!c.get("administrator"))throw new HTTPException(403,{message:"Administrator access required"});await next();});

async function body<T>(c:any,schema:z.ZodType<T>):Promise<T>{const value=await c.req.json().catch(()=>{throw new HTTPException(400,{message:"Request body must be JSON"});});const parsed=schema.safeParse(value);if(!parsed.success)throw new HTTPException(400,{message:parsed.error.issues.map(issue=>issue.message).join("; ")});return parsed.data;}
async function requireGlobal(env:Env,principal:StaffPrincipal,permission:Permission){const scope=await sqlScope(env,principal,permission);if(!scope.global||scope.deniedGlobal)throw new HTTPException(403,{message:`Global ${permission} permission required`});}
function placeholders(values:unknown[]):string{return values.map(()=>"?").join(",");}

const staffAccessSchema=z.object(Object.fromEntries(Object.keys(STAFF_ACCESS_CONTROLS).map(key=>[key,z.boolean()])) as Record<StaffAccessControl,z.ZodBoolean>).strict();
const clientRequestTriageSchema=z.object({status:z.enum(["under_review","accepted","declined"])}).strict();

app.get("/health",c=>c.json({status:"ok",service:"ltds-ops"}));
app.get("/api/session",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");const [permissions,globalScope]=await Promise.all([permissionKeys(c.env,principal),sqlScope(c.env,principal,"dashboard.view")]);const divisions=administrator&&globalScope.global?await c.env.OPS_DB.prepare("SELECT id,name,code FROM divisions WHERE active=1 ORDER BY name").all():await c.env.OPS_DB.prepare("SELECT d.id,d.name,d.code FROM divisions d JOIN staff_divisions sd ON sd.division_id=d.id WHERE sd.staff_id=? AND d.active=1 ORDER BY sd.is_primary DESC,d.name").bind(principal.id).all();return c.json({user:{id:principal.id,email:principal.email,displayName:principal.displayName,status:"Active",profileType:administrator?"Administrator":"Employee",isAdministrator:administrator,permissions:employeePermissions(permissions,administrator),divisions:divisions.results},csrfToken:await csrfToken(c.env,principal),timezone:c.env.DISPLAY_TIMEZONE,mapStyleUrl:c.env.MAP_STYLE_URL||null,capabilities:{dropboxImport:dropboxImportCapability(c.env),incomingUploads:incomingUploadsCapability(c.env),directDeliveryUploads:directDeliveryUploadsCapability(c.env)}});});

async function visibilityScope(env:Env,principal:StaffPrincipal,administrator:boolean,permission:Permission){const scope=await sqlScope(env,principal,permission);return administrator?scope:{...scope,divisions:[]};}
async function hasExplicitAllOperations(env:Env,principal:StaffPrincipal,administrator:boolean){return administrator||await hasLocalGlobalAllow(env,principal,"operations.view_all");}
async function paScopeWhere(env:Env,principal:StaffPrincipal,administrator:boolean,permission:Permission,alias:string,kind:"operation"|"task"){const [scope,allOperations]=await Promise.all([visibilityScope(env,principal,administrator,permission),hasExplicitAllOperations(env,principal,administrator)]);return paResourceFilter(scope,principal,administrator,alias,kind,allOperations);}
function managedInProjectAlpha():never{throw new HTTPException(405,{message:"Managed in Project Alpha"});}

app.get("/api/dashboard",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");await requirePermission(c.env,principal,"dashboard.view");const op=await paScopeWhere(c.env,principal,administrator,"operations.view","o","operation"),task=await paScopeWhere(c.env,principal,administrator,"tasks.view","t","task");const [operations,tasks,airspace,sync,shares]=await Promise.all([c.env.OPS_DB.prepare(`SELECT o.id,o.title,o.status,o.scheduled_start_at scheduled_start,o.business_unit_id,d.name division_name FROM pa_operations o LEFT JOIN divisions d ON d.project_alpha_business_unit_id=o.business_unit_id WHERE ${op.sql} AND o.status NOT IN ('completed','cancelled') ORDER BY o.scheduled_start_at LIMIT 8`).bind(...op.values).all(),c.env.OPS_DB.prepare(`SELECT t.id,t.title,t.status,t.due_at,t.business_unit_id FROM pa_tasks t WHERE ${task.sql} AND t.status NOT IN ('completed','cancelled') ORDER BY t.due_at LIMIT 8`).bind(...task.values).all(),airspaceView(c.env,op),c.env.OPS_DB.prepare(`SELECT integration,status,last_success_at,last_error_code,updated_at FROM integration_health ${administrator?"":"WHERE integration='project-alpha'"} ORDER BY integration`).all(),administrator?listDeliveryShares(c.env,principal).catch(()=>[]):Promise.resolve([])]);const now=Date.now();const integrations=sync.results.map((row:any)=>({...row,stale:projectAlphaHealthIsStale(row,now)}));return c.json({operations:operations.results,tasks:tasks.results,airspace:{sources:airspace.sources,activeTfrs:airspace.tfrs.filter((row:any)=>row.status==="active").length,scheduledTfrs:airspace.tfrs.filter((row:any)=>row.status==="scheduled").length,activeSua:airspace.sua.filter((row:any)=>row.status==="active").length},integrations,recentShares:shares.slice(0,6)});});

app.get("/api/projects",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");await requirePermission(c.env,principal,"projects.view");const [scope,allOperations]=await Promise.all([visibilityScope(c.env,principal,administrator,"projects.view"),hasExplicitAllOperations(c.env,principal,administrator)]);const access=paProjectFilter(scope,principal,administrator,allOperations);const search=(c.req.query("search")||"").trim();let sql=`SELECT p.id,p.name,p.status,p.start_date,p.end_date,p.client_id,p.organization_id,p.manager_user_id,pm.display_name manager_name,COALESCE(c.name,o.name,'Unassigned') customer_name,CASE WHEN ?=1 THEN pf.r2_prefix ELSE NULL END r2_prefix,CASE WHEN ?=1 THEN pf.division_id ELSE NULL END division_id FROM pa_projects p LEFT JOIN pa_clients c ON c.id=p.client_id LEFT JOIN pa_organizations o ON o.id=p.organization_id LEFT JOIN pa_users pm ON pm.id=p.manager_user_id LEFT JOIN project_folders pf ON pf.project_id=p.id WHERE ${access.sql}`;const values:unknown[]=[administrator?1:0,administrator?1:0,...access.values];if(search){sql+=" AND (p.name LIKE ? OR c.name LIKE ? OR o.name LIKE ? OR pm.display_name LIKE ?)";values.push(`%${search}%`,`%${search}%`,`%${search}%`,`%${search}%`);}sql+=" ORDER BY COALESCE(p.start_date,p.updated_at) DESC LIMIT 200";return c.json({projects:(await c.env.OPS_DB.prepare(sql).bind(...values).all()).results});});
app.get("/api/projects/:id",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");await requirePermission(c.env,principal,"projects.view");const [scope,allOperations]=await Promise.all([visibilityScope(c.env,principal,administrator,"projects.view"),hasExplicitAllOperations(c.env,principal,administrator)]);const access=paProjectFilter(scope,principal,administrator,allOperations);const project=await c.env.OPS_DB.prepare(`SELECT p.*,pm.display_name manager_name,COALESCE(c.name,o.name,'Unassigned') customer_name,CASE WHEN ?=1 THEN pf.r2_prefix ELSE NULL END r2_prefix,CASE WHEN ?=1 THEN pf.division_id ELSE NULL END division_id FROM pa_projects p LEFT JOIN pa_clients c ON c.id=p.client_id LEFT JOIN pa_organizations o ON o.id=p.organization_id LEFT JOIN pa_users pm ON pm.id=p.manager_user_id LEFT JOIN project_folders pf ON pf.project_id=p.id WHERE p.id=? AND ${access.sql}`).bind(administrator?1:0,administrator?1:0,c.req.param("id"),...access.values).first();if(!project)throw new HTTPException(404,{message:"Project not found"});return c.json({project});});
app.post("/api/projects/:id/folder",async c=>{const principal=c.get("principal");const value=await body(c,z.object({divisionId:z.string().min(1),r2Prefix:z.string().min(1).max(1000)}));await requirePermission(c.env,principal,"delivery.browse",{divisionId:value.divisionId},true);const prefix=value.r2Prefix.trim().replace(/\\/g,"/").replace(/^\/+/,"").replace(/\/{2,}/g,"/");if(!prefix||prefix.split("/").some(part=>part===".."||part.toLowerCase()==="dump"||part.toLowerCase()==="_ltds"||part.toLowerCase()===".previews"))throw new HTTPException(400,{message:"Folder prefix is invalid"});const normalized=prefix.endsWith("/")?prefix:`${prefix}/`;await c.env.OPS_DB.batch([c.env.OPS_DB.prepare(`INSERT INTO project_folders (project_id,division_id,r2_prefix,match_method,confirmed_by) VALUES (?,?,?,'manual',?) ON CONFLICT(project_id) DO UPDATE SET division_id=excluded.division_id,r2_prefix=excluded.r2_prefix,match_method='manual',confirmed_by=excluded.confirmed_by,confirmed_at=datetime('now')`).bind(c.req.param("id"),value.divisionId,normalized,principal.id),await auditStatement(c.env,c.req.raw,principal,"project.folder.confirmed","project",c.req.param("id"),value.divisionId,{r2Prefix:normalized})]);return c.json({success:true,r2Prefix:normalized});});

app.get("/api/operations",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"operations.view");const where=await paScopeWhere(c.env,principal,c.get("administrator"),"operations.view","o","operation");const result=await c.env.OPS_DB.prepare(`SELECT o.*,o.scheduled_start_at scheduled_start,o.scheduled_end_at scheduled_end,d.name division_name,p.name project_name FROM pa_operations o LEFT JOIN divisions d ON d.project_alpha_business_unit_id=o.business_unit_id LEFT JOIN pa_projects p ON p.id=o.project_id WHERE ${where.sql} ORDER BY COALESCE(o.scheduled_start_at,o.updated_at) DESC LIMIT 250`).bind(...where.values).all();return c.json({operations:result.results});});
app.post("/api/operations",()=>managedInProjectAlpha());
app.patch("/api/operations/:id",()=>managedInProjectAlpha());

app.get("/api/tasks",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"tasks.view");const where=await paScopeWhere(c.env,principal,c.get("administrator"),"tasks.view","t","task");const result=await c.env.OPS_DB.prepare(`SELECT t.*,t.notes description,d.name division_name,o.title operation_title,p.name project_name,(SELECT GROUP_CONCAT(s.display_name, ', ') FROM pa_task_assignments ta JOIN staff_users s ON s.project_alpha_user_id=ta.user_id WHERE ta.task_id=t.id AND ta.active=1) assigned_name FROM pa_tasks t LEFT JOIN divisions d ON d.project_alpha_business_unit_id=t.business_unit_id LEFT JOIN pa_operations o ON o.id=t.operation_id LEFT JOIN pa_projects p ON p.id=t.project_id WHERE ${where.sql} ORDER BY CASE t.status WHEN 'blocked' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'todo' THEN 2 ELSE 3 END,t.due_at LIMIT 300`).bind(...where.values).all();return c.json({tasks:result.results});});

// Client requests live with their portal grants in DELIVERY_DB. They are not
// Project Alpha tasks yet: creating or mutating PA records requires a separate
// signed, idempotent contract. Global Operations management is the deliberate
// staff triage boundary until that contract exists.
app.get("/api/client-service-requests",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"operations.manage");const result=await c.env.DELIVERY_DB.withSession("first-primary").prepare(`SELECT r.id,r.account_id,r.project_id,r.request_type,r.title,r.details,r.location_text,r.preferred_start_at,r.service_category,r.deliverables_text,r.site_contact_name,r.site_contact_email,r.site_contact_phone,r.desired_completion_at,r.latitude,r.longitude,r.area_geojson,r.status,r.created_at,r.updated_at,a.display_name account_name,p.project_name,p.client_name FROM client_service_requests r JOIN client_accounts a ON a.id=r.account_id JOIN projects p ON p.id=r.project_id WHERE a.status='active' ORDER BY CASE r.status WHEN 'submitted' THEN 0 WHEN 'under_review' THEN 1 WHEN 'accepted' THEN 2 ELSE 3 END,CASE WHEN r.desired_completion_at IS NULL THEN 1 ELSE 0 END,r.desired_completion_at ASC,r.created_at ASC,r.id ASC LIMIT 200`).all();return c.json({requests:result.results});});
app.patch("/api/client-service-requests/:id",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"operations.manage");const value=await body(c,clientRequestTriageSchema);const id=c.req.param("id");const request=await c.env.DELIVERY_DB.withSession("first-primary").prepare("SELECT id,account_id,project_id,status FROM client_service_requests WHERE id=?").bind(id).first<{id:string;account_id:string;project_id:string;status:"submitted"|"under_review"|"accepted"|"declined"|"cancelled"|"completed"}>();if(!request)throw new HTTPException(404,{message:"Client request not found"});const allowed=request.status==="submitted"?["under_review","accepted","declined"]:request.status==="under_review"?["accepted","declined"]:[];if(!allowed.includes(value.status))throw new HTTPException(409,{message:"This client request cannot transition to that status"});const db=c.env.DELIVERY_DB.withSession("first-primary");const updated=await db.prepare("UPDATE client_service_requests SET status=?,updated_at=datetime('now') WHERE id=? AND status=?").bind(value.status,id,request.status).run();if(!updated.meta.changes)throw new HTTPException(409,{message:"This client request changed. Refresh and try again."});await db.batch([db.prepare("INSERT OR IGNORE INTO client_portal_notification_outbox (id,request_id,event_type,status_value,recipient_kind,payload_json) VALUES (?,?, 'request_status_changed', ?, 'client_requester', ?)").bind(crypto.randomUUID(),id,value.status,JSON.stringify({projectId:request.project_id,status:value.status})),db.prepare("INSERT INTO audit_log (actor_type,actor_id,action,entity_type,entity_id,details_json) VALUES ('staff',?,'client.service_request.status_changed','client_service_request',?,?)").bind(principal.id,id,JSON.stringify({from:request.status,to:value.status}))]);await c.env.OPS_DB.batch([await auditStatement(c.env,c.req.raw,principal,"client.service_request.status_changed","client_service_request",id,null,{from:request.status,to:value.status})]);return c.json({id,status:value.status});});
app.post("/api/tasks",()=>managedInProjectAlpha());
app.patch("/api/tasks/:id",()=>managedInProjectAlpha());

app.get("/api/calendar",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");await requirePermission(c.env,principal,"operations.view");const [scope,allOperations]=await Promise.all([visibilityScope(c.env,principal,administrator,"operations.view"),hasExplicitAllOperations(c.env,principal,administrator)]);const where=paCalendarFilter(scope,principal,administrator,"e",allOperations);const result=await c.env.OPS_DB.prepare(`SELECT e.*,p.name project_name FROM pa_calendar_events e LEFT JOIN pa_projects p ON p.id=e.project_id WHERE ${where.sql} ORDER BY e.start_at LIMIT 500`).bind(...where.values).all();return c.json({events:result.results});});

app.get("/api/airspace/tfrs",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"airspace.view");const operationFilter=await paScopeWhere(c.env,principal,c.get("administrator"),"operations.view","o","operation");return c.json(await airspaceView(c.env,operationFilter));});
app.get("/api/delivery/folders",async c=>c.json(await listDeliveryFolder(c.env,c.get("principal"),c.req.query("prefix")||"",c.req.query("cursor"))));
app.get("/api/delivery/shares",async c=>c.json({shares:await listDeliveryShares(c.env,c.get("principal"))}));
app.get("/api/delivery/trash",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.delete");return c.json({items:await listTrash(c.env)});});
app.post("/api/delivery/trash/:id/restore",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.delete");await restoreTombstone(c.env,principal,c.req.param("id"));return c.json({success:true});});
app.get("/api/delivery/shares/active",async c=>{const prefix=c.req.query("prefix");if(!prefix)throw new HTTPException(400,{message:"prefix is required"});return c.json({share:await getActiveDeliveryShare(c.env,c.get("principal"),prefix)});});
app.post("/api/delivery/shares",async c=>{const value=await c.req.json();return c.json({share:await createDeliveryShare(c.env,c.req.raw,c.get("principal"),value,c.req.header("Idempotency-Key")||"")},201);});
app.delete("/api/delivery/shares/:id",async c=>{await revokeDeliveryShare(c.env,c.req.raw,c.get("principal"),c.req.param("id"));return c.json({success:true});});
app.patch("/api/delivery/items/:itemRef/display-name",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.rename");const key=await authorizeItem(c.env,principal,c.req.param("itemRef"));const value=await body(c,z.object({displayName:z.string().min(1).max(160)}));const alias=await upsertAlias(c.env,principal,key,value.displayName);await c.env.OPS_DB.batch([await auditStatement(c.env,c.req.raw,principal,"delivery.alias.updated","file",alias.physical_key,null,{displayName:alias.display_name})]);return c.json({alias});});
app.delete("/api/delivery/items/:itemRef/display-name",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.rename");const authorized=await authorizeItem(c.env,principal,c.req.param("itemRef"));const key=await resolveAliasKey(c.env,authorized);await deleteAlias(c.env,key);await c.env.OPS_DB.batch([await auditStatement(c.env,c.req.raw,principal,"delivery.alias.deleted","file",key,null)]);return c.json({success:true});});
app.post("/api/delivery/items/:itemRef/source/delete-preview",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.delete");await authorizeItem(c.env,principal,c.req.param("itemRef"));return c.json(await previewSourceDelete(c.env,c.req.param("itemRef")));});
app.delete("/api/delivery/items/:itemRef/source",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"delivery.delete");await authorizeItem(c.env,principal,c.req.param("itemRef"));const value=await body(c,z.object({confirmation:z.string().min(1).max(160)}));return c.json({deleted:await executeSourceDelete(c.env,principal,c.req.param("itemRef"),value.confirmation)});});

async function preparedArtifact(c:any,key:string,variant:PreparedArtifactVariant){return servePreparedArtifact(c.env,key,variant,c.req.header("If-None-Match"));}
async function opsFile(c:any,disposition:"inline"|"attachment",raw=false):Promise<Response>{const key=await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef"));const kind=mediaKind(key);if(disposition==="inline"&&!["image","video","audio","pdf","text"].includes(kind))throw new HTTPException(415,{message:"Preview unavailable"});if(!raw&&disposition==="inline"&&kind==="image")return preparedOrOriginal(c,key,"preview");if(!raw&&disposition==="inline"&&kind==="pdf")return preparedArtifact(c,key,"preview");if(!raw&&disposition==="inline"&&kind==="video")throw new HTTPException(409,{message:"Video preview uses Stream or the original source"});return serveSourceFile(c.env.DATA_BUCKET,key,c.req,disposition);}
async function preparedOrOriginal(c:any,key:string,variant:"thumb"|"preview"):Promise<Response>{try{return await preparedArtifact(c,key,variant)}catch(error){if(!(error instanceof HTTPException)||error.status!==404)throw error;}return opsFile(c,"inline",true);}
app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/preview",c=>opsFile(c,"inline"));app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/download",c=>opsFile(c,"attachment"));
app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/source",c=>opsFile(c,"inline",true));
app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/pdf",async c=>servePdfSourceFile(c.env.DATA_BUCKET,await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef")),c.req));
app.get("/api/delivery/items/:itemRef/thumbnail",async c=>{const key=await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef"));const kind=mediaKind(key);if(kind==="image"||kind==="pdf")return preparedArtifact(c,key,"thumb");if(kind==="video")return preparedArtifact(c,key,"poster");throw new HTTPException(415,{message:"Thumbnail unavailable"});});
registerR2CrudRoutes(app);
registerDropboxImportRoutes(app);
app.route("/api/delivery/incoming-link",createIncomingStaffRouter());
app.post("/api/delivery/items/:itemRef/stream-ticket",async c=>{const key=await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef"));if(mediaKind(key)!=="video")throw new HTTPException(415,{message:"Stream preview unavailable"});const row=await c.env.DELIVERY_DB.withSession("first-primary").prepare("SELECT stream_uid,stream_status FROM file_index WHERE r2_key=?").bind(key).first<{stream_uid:string|null;stream_status:string|null}>();if(row?.stream_status!=="ready"||!row.stream_uid||!c.env.STREAM_CUSTOMER_CODE)throw new HTTPException(404,{message:"Video preview unavailable"});const token=await c.env.STREAM.video(row.stream_uid).generateToken();return c.json({url:`https://customer-${c.env.STREAM_CUSTOMER_CODE}.cloudflarestream.com/${token}/iframe`,expiresIn:3600});});

app.get("/api/team/staff",async c=>{const principal=c.get("principal"),administrator=c.get("administrator");await requirePermission(c.env,principal,"team.view");const scope=await sqlScope(c.env,principal,"team.view"),conditions:string[]=[],values:unknown[]=[];if(!scope.global){const divisions=scope.divisions.filter(id=>!scope.deniedDivisions.includes(id));if(!divisions.length)return c.json({staff:[]});conditions.push(`EXISTS (SELECT 1 FROM staff_divisions visible_staff_division WHERE visible_staff_division.staff_id=s.id AND visible_staff_division.division_id IN (${placeholders(divisions)}))`);values.push(...divisions);}if(scope.deniedDivisions.length){conditions.push(`NOT EXISTS (SELECT 1 FROM staff_divisions denied_staff_division WHERE denied_staff_division.staff_id=s.id AND denied_staff_division.division_id IN (${placeholders(scope.deniedDivisions)}))`);values.push(...scope.deniedDivisions);}const where=conditions.length?conditions.join(" AND "):"1=1";const result=await c.env.OPS_DB.prepare(`SELECT s.id,s.email,s.display_name,s.status,s.last_seen_at,s.provisioning_source,s.sync_protected,GROUP_CONCAT(DISTINCT d.name) divisions,GROUP_CONCAT(DISTINCT r.name) roles,(SELECT GROUP_CONCAT(permission_key) FROM (SELECT rp.permission_key FROM staff_role_assignments inherited_assignment JOIN role_permissions rp ON rp.role_id=inherited_assignment.role_id WHERE inherited_assignment.staff_id=s.id UNION SELECT rp.permission_key FROM local_staff_role_assignments local_assignment JOIN role_permissions rp ON rp.role_id=local_assignment.role_id WHERE local_assignment.staff_id=s.id)) inherited_permissions,GROUP_CONCAT(DISTINCT CASE WHEN po.effect='allow' AND po.scope='global' THEN po.permission_key END) direct_allows,GROUP_CONCAT(DISTINCT CASE WHEN po.effect='deny' AND po.scope='global' THEN po.permission_key END) global_denies FROM staff_users s LEFT JOIN staff_divisions sd ON sd.staff_id=s.id LEFT JOIN divisions d ON d.id=sd.division_id LEFT JOIN staff_role_assignments a ON a.staff_id=s.id LEFT JOIN roles r ON r.id=a.role_id LEFT JOIN staff_permission_overrides po ON po.staff_id=s.id WHERE ${where} GROUP BY s.id ORDER BY s.display_name`).bind(...values).all<any>();return c.json({staff:result.results.map(row=>{const{inherited_permissions,direct_allows,global_denies,...roster}=row;return administrator?{...roster,localControls:effectiveStaffAccessControls({inheritedPermissions:inherited_permissions,directAllows:direct_allows,globalDenies:global_denies})}:roster;})});});

app.put("/api/admin/staff/:id/access-controls",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"roles.manage");const value=await body(c,staffAccessSchema);const target=await c.env.OPS_DB.prepare("SELECT id,email,status,sync_protected FROM staff_users WHERE id=?").bind(c.req.param("id")).first<{id:string;email:string;status:string;sync_protected:number}>();if(!target||!["active","inactive"].includes(target.status))throw new HTTPException(404,{message:"Staff member not found"});if(target.id===principal.id)throw new HTTPException(409,{message:"Administrators cannot change their own access controls"});if(target.sync_protected||target.id==="staff-beau-koltz")throw new HTTPException(409,{message:"Protected staff access controls cannot be changed"});const statements=[] as ReturnType<Env["OPS_DB"]["prepare"]>[];for(const [control,permissions] of Object.entries(STAFF_ACCESS_CONTROLS) as [StaffAccessControl,readonly Permission[]][]){for(const permission of permissions){const effect=staffAccessControlEffect(value[control]);statements.push(c.env.OPS_DB.prepare("DELETE FROM staff_permission_overrides WHERE staff_id=? AND permission_key=? AND scope='global'").bind(target.id,permission));statements.push(c.env.OPS_DB.prepare("INSERT INTO staff_permission_overrides(id,staff_id,permission_key,effect,scope,division_id,scope_key,created_by) VALUES(?,?,?,?, 'global',NULL,'global',?)").bind(`staff-control-${target.id}-${permission}`,target.id,permission,effect,principal.id));}}
  statements.push(await auditStatement(c.env,c.req.raw,principal,"staff.access_controls.updated","staff",target.id,null,{controls:value,email:target.email}));await c.env.OPS_DB.batch(statements);return c.json({success:true,controls:value});});
app.post("/api/admin/staff",()=>managedInProjectAlpha());
app.patch("/api/admin/staff/:id",()=>managedInProjectAlpha());
app.get("/api/admin/roles",async c=>{await requireGlobal(c.env,c.get("principal"),"roles.manage");const [roles,permissions]=await Promise.all([c.env.OPS_DB.prepare("SELECT r.id,r.name,r.description,r.immutable,GROUP_CONCAT(rp.permission_key) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.name").all(),c.env.OPS_DB.prepare("SELECT key,description FROM permissions ORDER BY key").all()]);return c.json({roles:roles.results,permissions:permissions.results});});
app.put("/api/admin/roles/:id",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"roles.manage");const id=c.req.param("id"),role=await c.env.OPS_DB.prepare("SELECT immutable FROM roles WHERE id=?").bind(id).first<{immutable:number}>();if(!role)throw new HTTPException(404,{message:"Role not found"});if(role.immutable)throw new HTTPException(409,{message:"Built-in roles are immutable"});const value=await body(c,z.object({name:z.string().min(1).max(100),description:z.string().max(500),permissions:z.array(z.string()).max(100)}));await c.env.OPS_DB.batch([c.env.OPS_DB.prepare("UPDATE roles SET name=?,description=?,updated_at=datetime('now') WHERE id=?").bind(value.name,value.description,id),c.env.OPS_DB.prepare("DELETE FROM role_permissions WHERE role_id=?").bind(id),...value.permissions.map(permission=>c.env.OPS_DB.prepare("INSERT INTO role_permissions (role_id,permission_key) VALUES (?,?)").bind(id,permission)),await auditStatement(c.env,c.req.raw,principal,"role.updated","role",id,null,{permissions:value.permissions})]);return c.json({success:true});});
app.get("/api/admin/audit",async c=>{await requireGlobal(c.env,c.get("principal"),"audit.view");return c.json({events:(await c.env.OPS_DB.prepare("SELECT id,actor_type,actor_email,actor_display_name,action,entity_type,entity_id,division_id,details_json,created_at FROM audit_events ORDER BY created_at DESC LIMIT 500").all()).results});});
app.post("/api/admin/integrations/project-alpha/sync",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"integrations.manage");const result=await syncProjectAlpha(c.env);if(result.changedCollections.some(collection=>collection==="operations"||collection==="service_locations"))await rebuildOperationAirspaceMatches(c.env);await c.env.OPS_DB.batch([await auditStatement(c.env,c.req.raw,principal,"integration.sync","integration","project-alpha",null,result)]);return c.json(result);});

app.notFound(c=>c.json({error:"Not found"},404));app.onError((error,c)=>{const status=error instanceof HTTPException?error.status:500;if(status>=500)console.error(JSON.stringify({event:"ops.error",status,message:error instanceof Error?error.message:"unknown"}));return c.json({error:status>=500?"An unexpected error occurred":error.message},status);});

const CONSOLIDATED_CRON="*/15 * * * *";
const CLIENT_REQUEST_NOTIFICATION_CRON="*/5 * * * *";

async function scheduled(event:ScheduledController,env:Env,ctx:ExecutionContext){
  if(event.cron===CLIENT_REQUEST_NOTIFICATION_CRON){ctx.waitUntil(processClientPortalRequestNotifications(env));return;}
  if(event.cron!==CONSOLIDATED_CRON)return;

  ctx.waitUntil(refreshStreamStatuses(env));
  const scheduledAt=new Date(event.scheduledTime);
  const minute=scheduledAt.getUTCMinutes();
  const hour=scheduledAt.getUTCHours();

  if(minute===0&&hour%2===0)ctx.waitUntil((async()=>{
    const [tfrs,sua]=await Promise.all([refreshTfrs(env),refreshSua(env)]);
    if(tfrs.changed||sua.changed)await rebuildOperationAirspaceMatches(env);
    await markAirspaceStaleAndPurge(env);
  })());

  // Keep the former daily syncs on the same trigger. They run at 08:15 and
  // 08:30 UTC, preserving their order while using one account-level trigger.
  if(hour===8&&minute===15)ctx.waitUntil((async()=>{
    const result=await syncProjectAlpha(env);
    if(result.changedCollections.some(collection=>collection==="operations"||collection==="service_locations"))await rebuildOperationAirspaceMatches(env);
  })());
  if(hour===8&&minute===30)ctx.waitUntil(reconcileFileIndex(env));
  if(hour===8&&minute===45)ctx.waitUntil(runRetention(env));
  if(r2PurgeEnabled(env))ctx.waitUntil(purgeTrash(env));
  ctx.waitUntil(processR2OperationJobs(env));
  ctx.waitUntil(purgeReplacementRecovery(env));
  ctx.waitUntil(enqueueExpiringNotifications(env).then(() => processDeliveryNotifications(env)));
  if(env.DROPBOX_IMPORT_TOKEN_SECRET)ctx.waitUntil(cleanupDropboxImports(env));
}
async function fetch(request:Request,env:Env,ctx:ExecutionContext):Promise<Response>{
  const incoming=dispatchIncomingPublicRequest(request,env,ctx);
  if(incoming)return await incoming;
  return app.fetch(request,env,ctx);
}
export default{fetch,queue:consumeFileEvents,scheduled}satisfies ExportedHandler<Env,R2Notification>;
export { R2CrudWorkflow } from "./r2-crud";
export { IncomingUploadLifecycleWorkflow } from "./incoming";
export { DropboxImportWorkflow } from "./dropbox-import";
