import { Hono } from "hono";
import { HTTPException } from "hono/http-exception";
import { secureHeaders } from "hono/secure-headers";
import { z } from "zod";
import type { Permission } from "@ltds/shared";
import { authenticateStaff } from "./auth";
import { airspaceView, markAirspaceStaleAndPurge, rebuildOperationAirspaceMatches, refreshSua, refreshTfrs } from "./airspace";
import { buildScopedWhere, permissionKeys, requirePermission, sqlScope } from "./acl";
import { consumeFileEvents, reconcileFileIndex, refreshStreamStatuses, type R2Notification } from "./file-events";
import { authorizeItem, createDeliveryShare, decodeRef, listDeliveryFolder, listDeliveryShares, mediaKind, mime, revokeDeliveryShare } from "./delivery";
import { syncProjectAlpha } from "./project-alpha";
import { auditStatement, csrfToken, requireMutationSecurity } from "./request-security";
import type { Env, StaffPrincipal } from "./types";

type Variables={principal:StaffPrincipal};
const app=new Hono<{Bindings:Env;Variables:Variables}>();
const operationInput=z.object({projectId:z.string().max(100).nullable().optional(),divisionId:z.string().min(1).max(100),title:z.string().min(1).max(180),status:z.enum(["draft","scheduled","ready","blocked","in_progress","completed","cancelled"]).default("draft"),scheduledStart:z.string().datetime().nullable().optional(),scheduledEnd:z.string().datetime().nullable().optional(),latitude:z.number().min(-90).max(90).nullable().optional(),longitude:z.number().min(-180).max(180).nullable().optional(),notes:z.string().max(10000).nullable().optional(),assignedStaffIds:z.array(z.string().max(100)).max(30).optional()});
const taskInput=z.object({operationId:z.string().max(100).nullable().optional(),projectId:z.string().max(100).nullable().optional(),divisionId:z.string().min(1).max(100),title:z.string().min(1).max(180),description:z.string().max(10000).nullable().optional(),status:z.enum(["todo","in_progress","blocked","done"]).default("todo"),assignedTo:z.string().max(100).nullable().optional(),dueAt:z.string().datetime().nullable().optional()});

app.use("*",secureHeaders({contentSecurityPolicy:{defaultSrc:["'self'"],imgSrc:["'self'","https://ledgetopdroneservices.com","data:"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],connectSrc:["'self'"],mediaSrc:["'self'","blob:"],frameAncestors:["'none'"],baseUri:["'none'"],objectSrc:["'none'"],formAction:["'self'"]},referrerPolicy:"no-referrer",xContentTypeOptions:"nosniff",xFrameOptions:"DENY",xXssProtection:false}));
app.use("*",async(c,next)=>{if(c.env.ENVIRONMENT==="production"&&new URL(c.req.url).host!==c.env.EXPECTED_HOST)return c.json({error:"Not found"},404);await next();c.header("Permissions-Policy","camera=(), microphone=(), geolocation=()");c.header("X-Robots-Tag","noindex, nofollow");if(c.req.path.startsWith("/api/"))c.header("Cache-Control","no-store");});
app.use("/api/*",async(c,next)=>{const principal=await authenticateStaff(c.req.raw,c.env);c.set("principal",principal);if(["POST","PUT","PATCH","DELETE"].includes(c.req.method))await requireMutationSecurity(c.req.raw,c.env,principal);await next();});

async function body<T>(c:any,schema:z.ZodType<T>):Promise<T>{const value=await c.req.json().catch(()=>{throw new HTTPException(400,{message:"Request body must be JSON"});});const parsed=schema.safeParse(value);if(!parsed.success)throw new HTTPException(400,{message:parsed.error.issues.map(issue=>issue.message).join("; ")});return parsed.data;}
async function requireGlobal(env:Env,principal:StaffPrincipal,permission:Permission){const scope=await sqlScope(env,principal,permission);if(!scope.global||scope.deniedGlobal)throw new HTTPException(403,{message:`Global ${permission} permission required`});}
function placeholders(values:unknown[]):string{return values.map(()=>"?").join(",");}

app.get("/health",c=>c.json({status:"ok",service:"ltds-ops"}));
app.get("/api/session",async c=>{const principal=c.get("principal");const [permissions,globalScope]=await Promise.all([permissionKeys(c.env,principal),sqlScope(c.env,principal,"dashboard.view")]);const divisions=globalScope.global?await c.env.OPS_DB.prepare("SELECT id,name,code FROM divisions WHERE active=1 ORDER BY name").all():await c.env.OPS_DB.prepare("SELECT d.id,d.name,d.code FROM divisions d JOIN staff_divisions sd ON sd.division_id=d.id WHERE sd.staff_id=? AND d.active=1 ORDER BY sd.is_primary DESC,d.name").bind(principal.id).all();return c.json({user:{id:principal.id,email:principal.email,displayName:principal.displayName,permissions,divisions:divisions.results},csrfToken:await csrfToken(c.env,principal),timezone:c.env.DISPLAY_TIMEZONE,mapStyleUrl:c.env.MAP_STYLE_URL||null});});

async function operationWhere(env:Env,principal:StaffPrincipal,permission:Permission){const scope=await sqlScope(env,principal,permission);return buildScopedWhere(scope,principal,"o","EXISTS (SELECT 1 FROM operation_staff os WHERE os.operation_id=o.id AND os.staff_id=?)");}
async function taskWhere(env:Env,principal:StaffPrincipal,permission:Permission){const scope=await sqlScope(env,principal,permission);return buildScopedWhere(scope,principal,"t","(t.assigned_to=? OR EXISTS (SELECT 1 FROM operation_staff os WHERE os.operation_id=t.operation_id AND os.staff_id=?))");}

app.get("/api/dashboard",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"dashboard.view");const op=await operationWhere(c.env,principal,"operations.view"),task=await taskWhere(c.env,principal,"tasks.view");const taskValues=[...task.values];if(task.sql.includes("operation_staff")){const firstAssigned=taskValues.findIndex(value=>value===principal.id);if(firstAssigned>=0)taskValues.splice(firstAssigned+1,0,principal.id);}const [operations,tasks,airspace,sync,shares]=await Promise.all([c.env.OPS_DB.prepare(`SELECT o.id,o.title,o.status,o.scheduled_start,o.division_id,d.name division_name FROM operations o JOIN divisions d ON d.id=o.division_id WHERE ${op.sql} AND o.status NOT IN ('completed','cancelled') ORDER BY o.scheduled_start LIMIT 8`).bind(...op.values).all(),c.env.OPS_DB.prepare(`SELECT t.id,t.title,t.status,t.due_at,t.division_id FROM tasks t WHERE ${task.sql} AND t.status<>'done' ORDER BY t.due_at LIMIT 8`).bind(...taskValues).all(),airspaceView(c.env),c.env.OPS_DB.prepare("SELECT integration,status,last_success_at,last_error_code,updated_at FROM integration_health ORDER BY integration").all(),listDeliveryShares(c.env,principal).catch(()=>[])]);return c.json({operations:operations.results,tasks:tasks.results,airspace:{sources:airspace.sources,activeTfrs:airspace.tfrs.filter((row:any)=>row.status==="active").length,activeSua:airspace.sua.filter((row:any)=>row.status==="active").length},integrations:sync.results,recentShares:shares.slice(0,6)});});

function projectScopeSql(scope:Awaited<ReturnType<typeof sqlScope>>,principal:StaffPrincipal){if(scope.deniedGlobal)return{sql:"0=1",values:[] as unknown[]};if(scope.global)return{sql:"p.active=1",values:[] as unknown[]};const effective=scope.divisions.filter(id=>!scope.deniedDivisions.includes(id));const clauses:string[]=["p.active=1"];const access:string[]=[];const values:unknown[]=[];if(effective.length){access.push(`EXISTS (SELECT 1 FROM pa_project_assignments ppa JOIN pa_worker_business_units wbu ON wbu.user_id=ppa.user_id AND wbu.active=1 JOIN divisions d ON d.project_alpha_business_unit_id=wbu.business_unit_id WHERE ppa.project_id=p.id AND ppa.active=1 AND d.id IN (${placeholders(effective)}))`);values.push(...effective);}if(scope.assigned&&principal.projectAlphaUserId){access.push("EXISTS (SELECT 1 FROM pa_project_assignments ppa WHERE ppa.project_id=p.id AND ppa.active=1 AND ppa.user_id=?)");values.push(principal.projectAlphaUserId);}if(!access.length)return{sql:"0=1",values:[]};clauses.push(`(${access.join(" OR ")})`);return{sql:clauses.join(" AND "),values};}
app.get("/api/projects",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"projects.view");const access=projectScopeSql(await sqlScope(c.env,principal,"projects.view"),principal);const search=(c.req.query("search")||"").trim();let sql=`SELECT p.id,p.name,p.status,p.start_date,p.end_date,p.client_id,p.organization_id,COALESCE(c.name,o.name,'Unassigned') customer_name,pf.r2_prefix,pf.division_id FROM pa_projects p LEFT JOIN pa_clients c ON c.id=p.client_id LEFT JOIN pa_organizations o ON o.id=p.organization_id LEFT JOIN project_folders pf ON pf.project_id=p.id WHERE ${access.sql}`;const values=[...access.values];if(search){sql+=" AND (p.name LIKE ? OR c.name LIKE ? OR o.name LIKE ?)";values.push(`%${search}%`,`%${search}%`,`%${search}%`);}sql+=" ORDER BY COALESCE(p.start_date,p.updated_at) DESC LIMIT 200";return c.json({projects:(await c.env.OPS_DB.prepare(sql).bind(...values).all()).results});});
app.get("/api/projects/:id",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"projects.view");const access=projectScopeSql(await sqlScope(c.env,principal,"projects.view"),principal);const project=await c.env.OPS_DB.prepare(`SELECT p.*,COALESCE(c.name,o.name,'Unassigned') customer_name,pf.r2_prefix,pf.division_id FROM pa_projects p LEFT JOIN pa_clients c ON c.id=p.client_id LEFT JOIN pa_organizations o ON o.id=p.organization_id LEFT JOIN project_folders pf ON pf.project_id=p.id WHERE p.id=? AND ${access.sql}`).bind(c.req.param("id"),...access.values).first();if(!project)throw new HTTPException(404,{message:"Project not found"});return c.json({project});});
app.post("/api/projects/:id/folder",async c=>{const principal=c.get("principal");const value=await body(c,z.object({divisionId:z.string().min(1),r2Prefix:z.string().min(1).max(1000)}));await requirePermission(c.env,principal,"delivery.browse",{divisionId:value.divisionId},true);const prefix=value.r2Prefix.trim().replace(/\\/g,"/").replace(/^\/+/,"").replace(/\/{2,}/g,"/");if(!prefix||prefix.split("/").some(part=>part===".."||part.toLowerCase()==="dump")||prefix.split("/")[0]?.toLowerCase()==="_ltds")throw new HTTPException(400,{message:"Folder prefix is invalid"});const normalized=prefix.endsWith("/")?prefix:`${prefix}/`;await c.env.OPS_DB.batch([c.env.OPS_DB.prepare(`INSERT INTO project_folders (project_id,division_id,r2_prefix,match_method,confirmed_by) VALUES (?,?,?,'manual',?) ON CONFLICT(project_id) DO UPDATE SET division_id=excluded.division_id,r2_prefix=excluded.r2_prefix,match_method='manual',confirmed_by=excluded.confirmed_by,confirmed_at=datetime('now')`).bind(c.req.param("id"),value.divisionId,normalized,principal.id),await auditStatement(c.env,c.req.raw,principal,"project.folder.confirmed","project",c.req.param("id"),value.divisionId,{r2Prefix:normalized})]);return c.json({success:true,r2Prefix:normalized});});

app.get("/api/operations",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"operations.view");const where=await operationWhere(c.env,principal,"operations.view");const result=await c.env.OPS_DB.prepare(`SELECT o.*,d.name division_name,p.name project_name FROM operations o JOIN divisions d ON d.id=o.division_id LEFT JOIN pa_projects p ON p.id=o.project_id WHERE ${where.sql} ORDER BY COALESCE(o.scheduled_start,o.created_at) DESC LIMIT 250`).bind(...where.values).all();return c.json({operations:result.results});});
app.post("/api/operations",async c=>{const principal=c.get("principal"),value=await body(c,operationInput);await requirePermission(c.env,principal,"operations.manage",{divisionId:value.divisionId},true);const id=crypto.randomUUID();const statements:D1PreparedStatement[]=[c.env.OPS_DB.prepare(`INSERT INTO operations (id,project_id,division_id,title,status,scheduled_start,scheduled_end,latitude,longitude,notes,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)`).bind(id,value.projectId||null,value.divisionId,value.title,value.status,value.scheduledStart||null,value.scheduledEnd||null,value.latitude??null,value.longitude??null,value.notes||null,principal.id)];for(const staffId of value.assignedStaffIds||[])statements.push(c.env.OPS_DB.prepare("INSERT INTO operation_staff (operation_id,staff_id) VALUES (?,?)").bind(id,staffId));statements.push(await auditStatement(c.env,c.req.raw,principal,"operation.created","operation",id,value.divisionId,{status:value.status}));await c.env.OPS_DB.batch(statements);return c.json({id},201);});
app.patch("/api/operations/:id",async c=>{const principal=c.get("principal"),id=c.req.param("id");const existing=await c.env.OPS_DB.prepare("SELECT id,division_id,created_by FROM operations WHERE id=?").bind(id).first<{id:string;division_id:string;created_by:string}>();if(!existing)throw new HTTPException(404,{message:"Operation not found"});const assigned=(await c.env.OPS_DB.prepare("SELECT staff_id FROM operation_staff WHERE operation_id=?").bind(id).all<{staff_id:string}>()).results.map(row=>row.staff_id);await requirePermission(c.env,principal,"operations.manage",{divisionId:existing.division_id,assignedStaffIds:assigned,ownerId:existing.created_by},true);const value=await body(c,operationInput.partial());const fields:Record<string,unknown>={project_id:value.projectId,division_id:value.divisionId,title:value.title,status:value.status,scheduled_start:value.scheduledStart,scheduled_end:value.scheduledEnd,latitude:value.latitude,longitude:value.longitude,notes:value.notes};const entries=Object.entries(fields).filter(([,v])=>v!==undefined);if(!entries.length)throw new HTTPException(400,{message:"No fields to update"});const division=String(value.divisionId||existing.division_id);if(value.divisionId)await requirePermission(c.env,principal,"operations.manage",{divisionId:value.divisionId},true);const statement=c.env.OPS_DB.prepare(`UPDATE operations SET ${entries.map(([key])=>`${key}=?`).join(",")},updated_at=datetime('now') WHERE id=?`).bind(...entries.map(([,v])=>v),id);await c.env.OPS_DB.batch([statement,await auditStatement(c.env,c.req.raw,principal,"operation.updated","operation",id,division,{fields:entries.map(([key])=>key)})]);return c.json({success:true});});

app.get("/api/tasks",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"tasks.view");const where=await taskWhere(c.env,principal,"tasks.view");const values=[...where.values];if(where.sql.includes("operation_staff")){const index=values.findIndex(value=>value===principal.id);if(index>=0)values.splice(index+1,0,principal.id);}const result=await c.env.OPS_DB.prepare(`SELECT t.*,d.name division_name,o.title operation_title,p.name project_name,s.display_name assigned_name FROM tasks t JOIN divisions d ON d.id=t.division_id LEFT JOIN operations o ON o.id=t.operation_id LEFT JOIN pa_projects p ON p.id=t.project_id LEFT JOIN staff_users s ON s.id=t.assigned_to WHERE ${where.sql} ORDER BY CASE t.status WHEN 'blocked' THEN 0 WHEN 'in_progress' THEN 1 WHEN 'todo' THEN 2 ELSE 3 END,t.due_at LIMIT 300`).bind(...values).all();return c.json({tasks:result.results});});
app.post("/api/tasks",async c=>{const principal=c.get("principal"),value=await body(c,taskInput);await requirePermission(c.env,principal,"tasks.create",{divisionId:value.divisionId},true);const id=crypto.randomUUID();await c.env.OPS_DB.batch([c.env.OPS_DB.prepare(`INSERT INTO tasks (id,operation_id,project_id,division_id,title,description,status,assigned_to,due_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(id,value.operationId||null,value.projectId||null,value.divisionId,value.title,value.description||null,value.status,value.assignedTo||null,value.dueAt||null,principal.id),await auditStatement(c.env,c.req.raw,principal,"task.created","task",id,value.divisionId,{status:value.status})]);return c.json({id},201);});
app.patch("/api/tasks/:id",async c=>{const principal=c.get("principal"),id=c.req.param("id");const existing=await c.env.OPS_DB.prepare("SELECT id,division_id,assigned_to,created_by FROM tasks WHERE id=?").bind(id).first<{id:string;division_id:string;assigned_to:string|null;created_by:string}>();if(!existing)throw new HTTPException(404,{message:"Task not found"});await requirePermission(c.env,principal,"tasks.update",{divisionId:existing.division_id,assignedStaffIds:existing.assigned_to?[existing.assigned_to]:[],ownerId:existing.created_by},true);const value=await body(c,taskInput.partial());const fields:Record<string,unknown>={operation_id:value.operationId,project_id:value.projectId,division_id:value.divisionId,title:value.title,description:value.description,status:value.status,assigned_to:value.assignedTo,due_at:value.dueAt};const entries=Object.entries(fields).filter(([,v])=>v!==undefined);if(!entries.length)throw new HTTPException(400,{message:"No fields to update"});const division=String(value.divisionId||existing.division_id);await c.env.OPS_DB.batch([c.env.OPS_DB.prepare(`UPDATE tasks SET ${entries.map(([key])=>`${key}=?`).join(",")},updated_at=datetime('now') WHERE id=?`).bind(...entries.map(([,v])=>v),id),await auditStatement(c.env,c.req.raw,principal,"task.updated","task",id,division,{fields:entries.map(([key])=>key)})]);return c.json({success:true});});

app.get("/api/airspace/tfrs",async c=>{await requirePermission(c.env,c.get("principal"),"airspace.view");return c.json(await airspaceView(c.env));});
app.get("/api/delivery/folders",async c=>c.json(await listDeliveryFolder(c.env,c.get("principal"),c.req.query("prefix")||"",c.req.query("cursor"))));
app.get("/api/delivery/shares",async c=>c.json({shares:await listDeliveryShares(c.env,c.get("principal"))}));
app.post("/api/delivery/shares",async c=>{const value=await c.req.json();return c.json({share:await createDeliveryShare(c.env,c.req.raw,c.get("principal"),value,c.req.header("Idempotency-Key")||"")},201);});
app.delete("/api/delivery/shares/:id",async c=>{await revokeDeliveryShare(c.env,c.req.raw,c.get("principal"),c.req.param("id"));return c.json({success:true});});

type ByteRange={offset:number;length:number};
function range(value:string|undefined,size:number):ByteRange|undefined{if(!value)return undefined;const match=/^bytes=(\d*)-(\d*)$/.exec(value);if(!match||value.includes(",")||(!match[1]&&!match[2]))throw new HTTPException(416);if(!match[1]){const suffix=Number(match[2]);if(!Number.isSafeInteger(suffix)||suffix<=0)throw new HTTPException(416);return{offset:Math.max(0,size-suffix),length:Math.min(size,suffix)};}const start=Number(match[1]),end=match[2]?Number(match[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<start||start>=size)throw new HTTPException(416);return{offset:start,length:Math.min(end,size-1)-start+1};}
async function opsFile(c:any,disposition:"inline"|"attachment"){const key=await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef"));const kind=mediaKind(key);if(disposition==="inline"&&!['image','video','audio','pdf','text'].includes(kind))throw new HTTPException(415,{message:"Preview unavailable"});const head=await c.env.DATA_BUCKET.head(key);if(!head)throw new HTTPException(404,{message:"File not found"});let requested:ByteRange|undefined;try{requested=range(c.req.header("Range"),head.size);}catch{return new Response(null,{status:416,headers:{"Content-Range":`bytes */${head.size}`,"Accept-Ranges":"bytes"}});}const headers=new Headers();headers.set("Content-Type",mime(key));headers.set("Content-Disposition",`${disposition}; filename="${(key.split('/').pop()||'file').replace(/[\0-\x1f\x7f"\\]/g,'_')}"`);headers.set("ETag",head.httpEtag);headers.set("Accept-Ranges","bytes");headers.set("Cache-Control","private, no-store");headers.set("Content-Length",String(requested?.length||head.size));if(requested)headers.set("Content-Range",`bytes ${requested.offset}-${requested.offset+requested.length-1}/${head.size}`);if(c.req.method==="HEAD")return new Response(null,{status:requested?206:200,headers});const object=await c.env.DATA_BUCKET.get(key,requested?{range:requested}:undefined);if(!object)throw new HTTPException(404);return new Response(object.body,{status:requested?206:200,headers});}
app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/preview",c=>opsFile(c,"inline"));app.on(["GET","HEAD"],"/api/delivery/items/:itemRef/download",c=>opsFile(c,"attachment"));
app.get("/api/delivery/items/:itemRef/thumbnail",async c=>{const key=await authorizeItem(c.env,c.get("principal"),c.req.param("itemRef"));if(mediaKind(key)!=="image")throw new HTTPException(415);const head=await c.env.DATA_BUCKET.head(key);if(!head)throw new HTTPException(404);if(head.size>20*1024*1024)throw new HTTPException(415);const object=await c.env.DATA_BUCKET.get(key);if(!object)throw new HTTPException(404);const result=(await c.env.IMAGES.input(object.body).transform({width:520,height:340,fit:"cover"}).output({format:"image/webp",quality:72})).response();const headers=new Headers(result.headers);headers.set("Cache-Control","private, max-age=3600");return new Response(result.body,{status:result.status,headers});});

app.get("/api/admin/staff",async c=>{const principal=c.get("principal");await requirePermission(c.env,principal,"team.view");const scope=await sqlScope(c.env,principal,"team.view");let where="1=1",values:unknown[]=[];if(!scope.global){const divisions=scope.divisions.filter(id=>!scope.deniedDivisions.includes(id));if(!divisions.length)return c.json({staff:[]});where=`EXISTS (SELECT 1 FROM staff_divisions sd WHERE sd.staff_id=s.id AND sd.division_id IN (${placeholders(divisions)}))`;values=divisions;}const result=await c.env.OPS_DB.prepare(`SELECT s.id,s.email,s.display_name,s.status,s.last_seen_at,GROUP_CONCAT(DISTINCT d.name) divisions,GROUP_CONCAT(DISTINCT r.name) roles FROM staff_users s LEFT JOIN staff_divisions sd ON sd.staff_id=s.id LEFT JOIN divisions d ON d.id=sd.division_id LEFT JOIN staff_role_assignments a ON a.staff_id=s.id LEFT JOIN roles r ON r.id=a.role_id WHERE ${where} GROUP BY s.id ORDER BY s.display_name`).bind(...values).all();return c.json({staff:result.results});});
app.post("/api/admin/staff",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"team.manage");const value=await body(c,z.object({email:z.string().email().transform(v=>v.toLowerCase()),displayName:z.string().min(1).max(160),roleId:z.string().min(1),scope:z.enum(["global","division","assigned","own"]),divisionId:z.string().nullable().optional()}));const id=crypto.randomUUID(),assignmentId=crypto.randomUUID(),scopeKey=value.scope==="division"?value.divisionId:value.scope;if(value.scope==="division"&&!value.divisionId)throw new HTTPException(400,{message:"divisionId is required"});await c.env.OPS_DB.batch([c.env.OPS_DB.prepare("INSERT INTO staff_users (id,email,display_name) VALUES (?,?,?)").bind(id,value.email,value.displayName),c.env.OPS_DB.prepare("INSERT INTO staff_role_assignments (id,staff_id,role_id,scope,division_id,scope_key,created_by) VALUES (?,?,?,?,?,?,?)").bind(assignmentId,id,value.roleId,value.scope,value.divisionId||null,scopeKey,principal.id),...(value.divisionId?[c.env.OPS_DB.prepare("INSERT INTO staff_divisions (staff_id,division_id,is_primary) VALUES (?,?,1)").bind(id,value.divisionId)]:[]),await auditStatement(c.env,c.req.raw,principal,"staff.created","staff",id,value.divisionId||null,{roleId:value.roleId,scope:value.scope})]);return c.json({id},201);});
app.patch("/api/admin/staff/:id",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"team.manage");const id=c.req.param("id"),value=await body(c,z.object({displayName:z.string().min(1).max(160).optional(),status:z.enum(["active","inactive"]).optional()}));if(value.status==="inactive"){const owner=await c.env.OPS_DB.prepare("SELECT 1 ok FROM staff_role_assignments WHERE staff_id=? AND role_id='role-owner' AND scope='global'").bind(id).first();if(owner){const count=await c.env.OPS_DB.prepare("SELECT COUNT(DISTINCT a.staff_id) count FROM staff_role_assignments a JOIN staff_users s ON s.id=a.staff_id WHERE a.role_id='role-owner' AND a.scope='global' AND s.status='active'").first<{count:number}>();if((count?.count||0)<=1)throw new HTTPException(409,{message:"The last active global Owner cannot be deactivated"});}}const entries=Object.entries({display_name:value.displayName,status:value.status}).filter(([,v])=>v!==undefined);if(!entries.length)throw new HTTPException(400,{message:"No fields to update"});await c.env.OPS_DB.batch([c.env.OPS_DB.prepare(`UPDATE staff_users SET ${entries.map(([key])=>`${key}=?`).join(',')},updated_at=datetime('now') WHERE id=?`).bind(...entries.map(([,v])=>v),id),await auditStatement(c.env,c.req.raw,principal,"staff.updated","staff",id,null,{fields:entries.map(([key])=>key)})]);return c.json({success:true});});
app.get("/api/admin/roles",async c=>{await requireGlobal(c.env,c.get("principal"),"roles.manage");const [roles,permissions]=await Promise.all([c.env.OPS_DB.prepare("SELECT r.id,r.name,r.description,r.immutable,GROUP_CONCAT(rp.permission_key) permissions FROM roles r LEFT JOIN role_permissions rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.name").all(),c.env.OPS_DB.prepare("SELECT key,description FROM permissions ORDER BY key").all()]);return c.json({roles:roles.results,permissions:permissions.results});});
app.put("/api/admin/roles/:id",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"roles.manage");const id=c.req.param("id"),role=await c.env.OPS_DB.prepare("SELECT immutable FROM roles WHERE id=?").bind(id).first<{immutable:number}>();if(!role)throw new HTTPException(404,{message:"Role not found"});if(role.immutable)throw new HTTPException(409,{message:"Built-in roles are immutable"});const value=await body(c,z.object({name:z.string().min(1).max(100),description:z.string().max(500),permissions:z.array(z.string()).max(100)}));await c.env.OPS_DB.batch([c.env.OPS_DB.prepare("UPDATE roles SET name=?,description=?,updated_at=datetime('now') WHERE id=?").bind(value.name,value.description,id),c.env.OPS_DB.prepare("DELETE FROM role_permissions WHERE role_id=?").bind(id),...value.permissions.map(permission=>c.env.OPS_DB.prepare("INSERT INTO role_permissions (role_id,permission_key) VALUES (?,?)").bind(id,permission)),await auditStatement(c.env,c.req.raw,principal,"role.updated","role",id,null,{permissions:value.permissions})]);return c.json({success:true});});
app.get("/api/admin/audit",async c=>{await requireGlobal(c.env,c.get("principal"),"audit.view");return c.json({events:(await c.env.OPS_DB.prepare("SELECT id,actor_type,actor_email,actor_display_name,action,entity_type,entity_id,division_id,details_json,created_at FROM audit_events ORDER BY created_at DESC LIMIT 500").all()).results});});
app.post("/api/admin/integrations/project-alpha/sync",async c=>{const principal=c.get("principal");await requireGlobal(c.env,principal,"integrations.manage");const result=await syncProjectAlpha(c.env);await c.env.OPS_DB.batch([await auditStatement(c.env,c.req.raw,principal,"integration.sync","integration","project-alpha",null,result)]);return c.json(result);});

app.notFound(c=>c.json({error:"Not found"},404));app.onError((error,c)=>{const status=error instanceof HTTPException?error.status:500;if(status>=500)console.error(JSON.stringify({event:"ops.error",status,message:error instanceof Error?error.message:"unknown"}));return c.json({error:status>=500?"An unexpected error occurred":error.message},status);});

async function scheduled(event:ScheduledController,env:Env,ctx:ExecutionContext){const minute=new Date(event.scheduledTime).getUTCMinutes(),hour=new Date(event.scheduledTime).getUTCHours();if(minute%5===0){ctx.waitUntil(Promise.all([refreshTfrs(env),refreshSua(env)]).then(()=>rebuildOperationAirspaceMatches(env)));ctx.waitUntil(markAirspaceStaleAndPurge(env));ctx.waitUntil(refreshStreamStatuses(env));}if(minute%15===0)ctx.waitUntil(syncProjectAlpha(env));if(hour===8&&minute===17)ctx.waitUntil(reconcileFileIndex(env));}
export default{fetch:app.fetch,queue:consumeFileEvents,scheduled}satisfies ExportedHandler<Env,R2Notification>;
