import { Hono, type Context } from "hono";
import { HTTPException } from "hono/http-exception";
import { z } from "zod";
import { sqlScope } from "./acl";
import { readBoundedJson } from "./bounded-json";
import { authenticateNativeStaffWithAdmissionVersion } from "./native-staff-auth";
import { bootstrapProjectAlphaDirectoryOrganization } from "./project-alpha-directory-v2-bootstrap-dispatcher";
import type { Env, StaffPrincipal } from "./types";

type Variables={principal:StaffPrincipal;administrator:boolean}; type App=Hono<{Bindings:Env;Variables:Variables}>; type AppContext=Context<{Bindings:Env;Variables:Variables}>;
export const PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ROUTE="/api/admin/project-alpha/directory/v2/bootstrap";
export function projectAlphaDirectoryV2BootstrapAcceptanceEnabled(env: Pick<Env,"ENVIRONMENT"|"PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ENABLED">): boolean { return env.ENVIRONMENT==="staging"&&env.PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ENABLED==="true"; }
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;
const sourceId=z.string().regex(/^project-alpha:[a-z0-9][a-z0-9_-]{0,63}$/);
const text=(max:number)=>z.string().min(1).max(max).refine(v=>!/[\p{C}]/u.test(v));
const schema=z.object({sourceId,expectedApplicationId:z.string().regex(UUID),commandId:z.string().regex(UUID),recordId:z.string().regex(/^staging-directory-acceptance-[a-z0-9][a-z0-9-]{2,120}$/),scopes:z.array(z.object({businessAreaId:text(191),divisionId:text(191).nullable()}).strict()).min(1).max(16),profile:z.object({name:text(150),generalEmail:z.string().max(255),generalPhone:z.string().max(50),addressLine1:z.string().max(255),addressLine2:z.string().max(255),city:z.string().max(100),state:z.string().max(100),postalCode:z.string().max(32),country:z.string().max(100)}).strict()}).strict();
async function nativeActor(c:AppContext){let a:Awaited<ReturnType<typeof authenticateNativeStaffWithAdmissionVersion>>;try{a=await authenticateNativeStaffWithAdmissionVersion(c.req.raw,c.env.OPS_DB,{enabled:true,issuer:c.env.TEAM_DOMAIN??"",staffAudience:c.env.OPERATIONS_AUD,onboardingAudience:c.env.NATIVE_STAFF_ONBOARDING_AUD??""});}catch{throw new HTTPException(403,{message:"Current native staff authority is required"});}const p=c.get("principal"),i=a.identity;if(i.staffId!==p.id||i.email!==p.email||i.verifiedAccessSubject!==p.accessSubject)throw new HTTPException(403,{message:"Operations and native staff identities do not match"});return{staffId:i.staffId,accessSubject:i.verifiedAccessSubject,admissionVersion:a.admissionVersion};}
/** Explicit default-off staging fixture. It is not an onboarding or production route. Origin/CSRF is enforced by the mounted /api middleware; this route adds native authority and integrations.manage. */
export function registerProjectAlphaDirectoryV2BootstrapAcceptanceRoutes(app:App):void{app.post(PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ROUTE,async c=>{if(!projectAlphaDirectoryV2BootstrapAcceptanceEnabled(c.env))throw new HTTPException(404,{message:"Not found"});if(!c.get("administrator"))throw new HTTPException(403,{message:"Administrator access required"});const permission=await sqlScope(c.env,c.get("principal"),"integrations.manage");if(!permission.global||permission.deniedGlobal)throw new HTTPException(403,{message:"Global integrations.manage permission required"});const parsed=schema.safeParse(await readBoundedJson(c.req.raw,16*1024,"Directory bootstrap acceptance"));if(!parsed.success)throw new HTTPException(400,{message:"Directory bootstrap acceptance request is invalid"});if(c.req.header("Idempotency-Key")!==parsed.data.commandId)throw new HTTPException(400,{message:"Idempotency-Key must match commandId"});c.header("Cache-Control","no-store");const outcome=await bootstrapProjectAlphaDirectoryOrganization(c.env,{...parsed.data,actor:await nativeActor(c)});return c.json({sourceId:parsed.data.sourceId,commandId:parsed.data.commandId,recordId:parsed.data.recordId,outcome});});}
