import type { Env } from "./types";

type Row = Record<string, unknown>;
interface Snapshot { generated_at: string; users: Row[]; business_units: Row[]; worker_business_units: Row[]; clients: Row[]; organizations: Row[]; projects: Row[]; project_assignments: Row[]; service_locations: Row[]; has_more: boolean; next_page: number | null; }

function text(value: unknown): string | null { return value === null || value === undefined ? null : String(value); }
function active(value: unknown): number { return value === true || value === 1 || value === "1" ? 0 : 1; }
async function runBatches(db: D1Database, statements: D1PreparedStatement[]): Promise<void> { for (let index = 0; index < statements.length; index += 75) await db.batch(statements.slice(index, index + 75)); }

export async function syncProjectAlpha(env: Env): Promise<{ status: "disabled" | "success"; records: number }> {
  if (!env.PROJECT_ALPHA_BASE_URL || !env.PROJECT_ALPHA_API_KEY) {
    await env.OPS_DB.prepare("UPDATE integration_health SET status='disabled',updated_at=datetime('now') WHERE integration='project-alpha'").run();
    return { status: "disabled", records: 0 };
  }
  const syncId = crypto.randomUUID(); const runId = crypto.randomUUID(); let page = 1; let records = 0; let completed = false;
  await env.OPS_DB.batch([
    env.OPS_DB.prepare("INSERT INTO sync_runs (id,integration,status) VALUES (?,'project-alpha','running')").bind(runId),
    env.OPS_DB.prepare("UPDATE integration_health SET last_attempt_at=datetime('now'),updated_at=datetime('now') WHERE integration='project-alpha'"),
  ]);
  try {
    while (page <= 1000) {
      const url = new URL("/api/v1/ops/snapshot", env.PROJECT_ALPHA_BASE_URL); url.searchParams.set("page", String(page)); url.searchParams.set("limit", "500");
      const response = await fetch(url, { headers: { Authorization: `Bearer ${env.PROJECT_ALPHA_API_KEY}`, Accept: "application/json" } });
      if (!response.ok) throw new Error(`project-alpha-http-${response.status}`);
      const data = await response.json<Snapshot>();
      for (const key of ["users","business_units","worker_business_units","clients","organizations","projects","project_assignments","service_locations"] as const) if (!Array.isArray(data[key])) throw new Error(`project-alpha-schema-${key}`);
      const statements: D1PreparedStatement[] = [];
      for (const row of data.users) { const id=text(row.id); if(!id)continue; const email=text(row.email)?.toLowerCase()||null,display=text(row.display_name)||text(row.username)||email; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_users (id,email,display_name,role,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,role=excluded.role,active=excluded.active,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id,updated_at=datetime('now')`).bind(id,email,display,text(row.role),active(Boolean(row.is_disabled)||Boolean(row.deleted_at)),JSON.stringify(row),syncId)); if(email)statements.push(env.OPS_DB.prepare("UPDATE staff_users SET project_alpha_user_id=COALESCE(project_alpha_user_id,?) WHERE email=? AND (project_alpha_user_id IS NULL OR project_alpha_user_id=?)").bind(id,email,id)); }
      for (const row of data.business_units) { const id=text(row.id); if(!id)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_business_units (id,name,code,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,code=excluded.code,active=excluded.active,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id,updated_at=datetime('now')`).bind(id,text(row.name)||`Business unit ${id}`,text(row.code),row.is_active===false?0:1,JSON.stringify(row),syncId)); }
      for (const row of data.worker_business_units) { const userId=text(row.user_id),unitId=text(row.business_unit_id); if(!userId||!unitId)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_worker_business_units (user_id,business_unit_id,is_lead,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?) ON CONFLICT(user_id,business_unit_id) DO UPDATE SET is_lead=excluded.is_lead,active=1,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id`).bind(userId,unitId,row.is_lead?1:0,1,JSON.stringify(row),syncId)); }
      for (const row of data.clients) { const id=text(row.id); if(!id)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_clients (id,name,organization_id,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,organization_id=excluded.organization_id,active=excluded.active,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id,updated_at=datetime('now')`).bind(id,text(row.name)||`Client ${id}`,text(row.organization_id),active(Boolean(row.archived)||Boolean(row.deleted_at)),JSON.stringify(row),syncId)); }
      for (const row of data.organizations) { const id=text(row.id); if(!id)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_organizations (id,name,active,payload_json,last_sync_id) VALUES (?,?,1,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,active=1,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id,updated_at=datetime('now')`).bind(id,text(row.name)||`Organization ${id}`,JSON.stringify(row),syncId)); }
      for (const row of data.projects) { const id=text(row.id); if(!id)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_projects (id,client_id,organization_id,name,status,start_date,end_date,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET client_id=excluded.client_id,organization_id=excluded.organization_id,name=excluded.name,status=excluded.status,start_date=excluded.start_date,end_date=excluded.end_date,active=1,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id,updated_at=datetime('now')`).bind(id,text(row.client_id),text(row.organization_id),text(row.name)||`Project ${id}`,text(row.status),text(row.start_date)||text(row.estimated_start),text(row.end_date)||text(row.estimated_end),1,JSON.stringify(row),syncId)); }
      for (const row of data.project_assignments) { const id=text(row.id),projectId=text(row.project_id),userId=text(row.user_id); if(!id||!projectId||!userId)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_project_assignments (id,project_id,user_id,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id,user_id=excluded.user_id,active=1,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id`).bind(id,projectId,userId,1,JSON.stringify(row),syncId)); }
      for (const row of data.service_locations) { const id=text(row.id); if(!id)continue; statements.push(env.OPS_DB.prepare(`INSERT INTO pa_service_locations (id,project_id,client_id,organization_id,name,latitude,longitude,active,payload_json,last_sync_id) VALUES (?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET project_id=excluded.project_id,client_id=excluded.client_id,organization_id=excluded.organization_id,name=excluded.name,latitude=excluded.latitude,longitude=excluded.longitude,active=excluded.active,payload_json=excluded.payload_json,last_sync_id=excluded.last_sync_id`).bind(id,text(row.project_id),text(row.client_id),text(row.organization_id),text(row.name),row.latitude??null,row.longitude??null,active(Boolean(row.archived)),JSON.stringify(row),syncId)); }
      await runBatches(env.OPS_DB,statements); records += statements.length; if(!data.has_more){completed=true;break;} if(!data.next_page||data.next_page<=page)throw new Error("project-alpha-pagination");page=data.next_page;
    }
    if(!completed)throw new Error("project-alpha-page-limit");
    await env.OPS_DB.batch([
      env.OPS_DB.prepare("UPDATE pa_users SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_business_units SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_worker_business_units SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_clients SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_organizations SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_projects SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_project_assignments SET active=0 WHERE last_sync_id<>?").bind(syncId),env.OPS_DB.prepare("UPDATE pa_service_locations SET active=0 WHERE last_sync_id<>?").bind(syncId),
      env.OPS_DB.prepare("UPDATE sync_runs SET status='success',completed_at=datetime('now'),records_seen=? WHERE id=?").bind(records,runId),
      env.OPS_DB.prepare("UPDATE integration_health SET status='healthy',last_success_at=datetime('now'),last_error_code=NULL,updated_at=datetime('now') WHERE integration='project-alpha'"),
    ]); return{status:"success",records};
  }catch(error){const code=error instanceof Error?error.message.slice(0,120):"unknown";await env.OPS_DB.batch([env.OPS_DB.prepare("UPDATE sync_runs SET status='failed',completed_at=datetime('now'),error_code=? WHERE id=?").bind(code,runId),env.OPS_DB.prepare("UPDATE integration_health SET status='error',last_error_code=?,updated_at=datetime('now') WHERE integration='project-alpha'").bind(code)]);throw error;}
}
