const STAGING_HOST = "ops-staging.ledgetopdroneservices.com";
const STAGING_ORIGIN = `https://${STAGING_HOST}`;

export type NativeStagingAdmissionEnv = Readonly<{
  ENVIRONMENT?: string;
  EXPECTED_HOST?: string;
  PUBLIC_BASE_URL?: string;
  CLIENT_PORTAL_NATIVE_RECIPIENT_ENROLLMENT_ENABLED?: string;
  CLIENT_PORTAL_NATIVE_RECIPIENT_OWNER_ENABLED?: string;
  OPERATIONS_PORTAL_NATIVE_RECIPIENT_AUTHORITY_DISPATCH_ENABLED?: string;
  OPERATIONS_PORTAL_NATIVE_RECIPIENT_AUTHORITY?: unknown;
  OPERATIONS_PORTAL_NATIVE_DELIVERY_OWNER_ENABLED?: string;
  OPERATIONS_PORTAL_NATIVE_DELIVERY_AUTHORITY_DISPATCH_ENABLED?: string;
  OPERATIONS_PORTAL_NATIVE_DELIVERY_AUTHORITY?: unknown;
  OPERATIONS_PORTAL_NATIVE_DELIVERY_READER_ENABLED?: string;
}>;

export function exactNativeStagingConfiguration(request: Request, env: NativeStagingAdmissionEnv): boolean {
  const url = new URL(request.url);
  return env.ENVIRONMENT === "staging" && env.EXPECTED_HOST === STAGING_HOST
    && url.origin === STAGING_ORIGIN && env.PUBLIC_BASE_URL === STAGING_ORIGIN
    && env.CLIENT_PORTAL_NATIVE_RECIPIENT_ENROLLMENT_ENABLED === "true"
    && env.CLIENT_PORTAL_NATIVE_RECIPIENT_OWNER_ENABLED === "true"
    && env.OPERATIONS_PORTAL_NATIVE_RECIPIENT_AUTHORITY_DISPATCH_ENABLED === "true"
    && Boolean(env.OPERATIONS_PORTAL_NATIVE_RECIPIENT_AUTHORITY)
    && env.OPERATIONS_PORTAL_NATIVE_DELIVERY_OWNER_ENABLED === "true"
    && env.OPERATIONS_PORTAL_NATIVE_DELIVERY_AUTHORITY_DISPATCH_ENABLED === "true"
    && Boolean(env.OPERATIONS_PORTAL_NATIVE_DELIVERY_AUTHORITY)
    && env.OPERATIONS_PORTAL_NATIVE_DELIVERY_READER_ENABLED === "true";
}
