import { useEffect, useRef, useState } from "react";
import mapboxgl from "mapbox-gl";

export type PortalAreaGeoJson = { type: "Polygon"; coordinates: [number, number][][] };
type Point = [number, number];
type MapStyle = "satellite" | "streets";

function area(vertices: Point[]): PortalAreaGeoJson | null { return vertices.length >= 3 ? { type: "Polygon", coordinates: [[...vertices, vertices[0]!]] } : null; }
function data(pin: Point | null, vertices: Point[]): GeoJSON.FeatureCollection {
  const selected = area(vertices);
  return { type: "FeatureCollection", features: [...(pin ? [{ type: "Feature" as const, properties: { pin: true }, geometry: { type: "Point" as const, coordinates: pin } }] : []), ...vertices.map((coordinates, index) => ({ type: "Feature" as const, properties: { index }, geometry: { type: "Point" as const, coordinates } })), ...(selected ? [{ type: "Feature" as const, properties: {}, geometry: selected }] : [])] };
}

function locationError(error: GeolocationPositionError): string {
  if (error.code === error.PERMISSION_DENIED) return "Location permission was declined. You can still search an address or place a pin.";
  if (error.code === error.TIMEOUT) return "Location lookup timed out. Try again or search an address.";
  return "Your location could not be determined. Search an address or place a pin instead.";
}

export function MapAreaSelector({ value, onChange, token, point, onPoint }: { value: PortalAreaGeoJson | null; onChange: (next: PortalAreaGeoJson | null) => void; token: string | null; point: Point | null; onPoint: (next: Point | null) => void }) {
  const element = useRef<HTMLDivElement | null>(null); const instance = useRef<mapboxgl.Map | null>(null);
  const pointRef = useRef<Point | null>(point); const verticesRef = useRef<Point[]>(value?.coordinates[0]?.slice(0, -1) ?? []); const modeRef = useRef<"pin" | "area">("pin");
  const [vertices, setVertices] = useState<Point[]>(verticesRef.current); const [mode, setMode] = useState<"pin" | "area">("pin"); const [query, setQuery] = useState(""); const [message, setMessage] = useState(""); const [locating, setLocating] = useState(false); const [mapStyle, setMapStyle] = useState<MapStyle>("satellite");
  pointRef.current = point;
  const update = (next = verticesRef.current, nextPin = pointRef.current) => { (instance.current?.getSource("request-area") as mapboxgl.GeoJSONSource | undefined)?.setData(data(nextPin, next)); };
  const setPin = (next: Point | null) => { pointRef.current = next; onPoint(next); update(verticesRef.current, next); };
  const ensureLayers = (map: mapboxgl.Map) => { if (!map.getSource("request-area")) map.addSource("request-area", { type: "geojson", data: data(pointRef.current, verticesRef.current) }); if (!map.getLayer("request-fill")) map.addLayer({ id: "request-fill", type: "fill", source: "request-area", filter: ["==", "$type", "Polygon"], paint: { "fill-color": "#ee5007", "fill-opacity": .2 } }); if (!map.getLayer("request-line")) map.addLayer({ id: "request-line", type: "line", source: "request-area", filter: ["==", "$type", "Polygon"], paint: { "line-color": "#ee5007", "line-width": 3 } }); if (!map.getLayer("request-points")) map.addLayer({ id: "request-points", type: "circle", source: "request-area", filter: ["==", "$type", "Point"], paint: { "circle-radius": 6, "circle-color": "#171d23", "circle-stroke-color": "#fff", "circle-stroke-width": 2 } }); };
  useEffect(() => { if (!token || !element.current || instance.current) return; mapboxgl.accessToken = token; const map = new mapboxgl.Map({ container: element.current, style: "mapbox://styles/mapbox/satellite-streets-v12", center: [-88.07, 44.5], zoom: 7 }); instance.current = map; map.on("style.load", () => ensureLayers(map)); map.on("click", event => { const selected: Point = [Number(event.lngLat.lng.toFixed(6)), Number(event.lngLat.lat.toFixed(6))]; if (modeRef.current === "pin") setPin(selected); else setVertices(current => { const next = current.length < 64 ? [...current, selected] : current; verticesRef.current = next; update(next); onChange(area(next)); return next; }); }); return () => { instance.current = null; map.remove(); }; }, [token]);
  const chooseStyle = (next: MapStyle) => { if (next === mapStyle) return; setMapStyle(next); instance.current?.setStyle(next === "satellite" ? "mapbox://styles/mapbox/satellite-streets-v12" : "mapbox://styles/mapbox/streets-v12"); };
  const chooseMode = (next: "pin" | "area") => { modeRef.current = next; setMode(next); };
  const edit = (fn: (current: Point[]) => Point[]) => setVertices(current => { const next = fn(current); verticesRef.current = next; update(next); onChange(area(next)); return next; });
  const focus = (selected: Point) => { setPin(selected); instance.current?.flyTo({ center: selected, zoom: 15 }); };
  const find = async () => { if (!token || !query.trim()) return; setMessage(""); try { const response = await fetch(`https://api.mapbox.com/search/geocode/v6/forward?q=${encodeURIComponent(query)}&limit=1&access_token=${encodeURIComponent(token)}`); const body = await response.json() as { features?: Array<{ geometry?: { coordinates?: unknown } }> }; const coordinates = body.features?.[0]?.geometry?.coordinates; if (!response.ok || !Array.isArray(coordinates) || typeof coordinates[0] !== "number" || typeof coordinates[1] !== "number") throw new Error("not-found"); focus([coordinates[0], coordinates[1]]); } catch { setMessage("Address not found. Try a fuller address or place a pin on the map."); } };
  const useCurrentLocation = () => { if (!navigator.geolocation) { setMessage("This browser does not support current location. Search an address or place a pin instead."); return; } setLocating(true); setMessage(""); navigator.geolocation.getCurrentPosition(position => { focus([Number(position.coords.longitude.toFixed(6)), Number(position.coords.latitude.toFixed(6))]); setLocating(false); }, error => { setMessage(locationError(error)); setLocating(false); }, { enableHighAccuracy: false, timeout: 12_000, maximumAge: 300_000 }); };
  if (!token) return <p className="portal-map-unavailable">Map selection is temporarily unavailable. You can still submit the address details above.</p>;
  return <section className="portal-map-selector"><div className="portal-map-copy"><strong>Location and requested area</strong><span>Optional. Search an address, use your current location, place a pin, or outline an area.</span></div><div className="portal-map-search"><input aria-label="Search address or place" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search address or place"/><button type="button" className="button-ghost button-small" onClick={() => void find()}>Find</button><button type="button" className="button-ghost button-small" onClick={useCurrentLocation} disabled={locating}>{locating ? "Locating…" : "Use current location"}</button></div>{message && <small className="portal-map-error" role="status">{message}</small>}<div className="portal-map-controls"><div className="portal-map-mode" aria-label="Map selection mode"><button type="button" className={mode === "pin" ? "active" : ""} aria-pressed={mode === "pin"} onClick={() => chooseMode("pin")}>Place pin</button><button type="button" className={mode === "area" ? "active" : ""} aria-pressed={mode === "area"} onClick={() => chooseMode("area")}>Draw area</button></div><div className="portal-map-style" aria-label="Map style"><button type="button" className={mapStyle === "satellite" ? "active" : ""} aria-pressed={mapStyle === "satellite"} onClick={() => chooseStyle("satellite")}>Satellite</button><button type="button" className={mapStyle === "streets" ? "active" : ""} aria-pressed={mapStyle === "streets"} onClick={() => chooseStyle("streets")}>Streets</button></div></div><div ref={element} className="portal-map-canvas"/><div className="portal-map-actions"><span>{point ? "Pin selected" : "No pin selected"}{vertices.length ? ` · ${vertices.length} area points` : ""}</span><button type="button" className="button-ghost button-small" onClick={() => setPin(null)} disabled={!point}>Clear pin</button><button type="button" className="button-ghost button-small" onClick={() => edit(current => current.slice(0, -1))} disabled={!vertices.length}>Undo area point</button><button type="button" className="button-ghost button-small" onClick={() => edit(() => [])} disabled={!vertices.length}>Clear area</button></div></section>;
}
