import{beforeEach,describe,expect,it,vi}from"vitest";
const calls=vi.hoisted(()=>({auth:vi.fn(),enqueue:vi.fn(),dispatch:vi.fn()}));
vi.mock("../src/worker/native-staff-auth",()=>({authenticateNativeStaffWithAdmissionVersion:calls.auth}));
vi.mock("../src/worker/client-portal-authority-v2-outbox",()=>({enqueueClientPortalAuthorityV3:calls.enqueue,dispatchNextClientPortalAuthorityV2:calls.dispatch}));
import{handleAuthorityV3OwnerHttp,type AuthorityV3OwnerHttpDependencies}from"../src/worker/client-portal-authority-v3-owner-http";
const origin="https://ops-staging.example.test",op="11111111-1111-4111-8111-111111111111",selection="22222222-2222-4222-8222-222222222222",recipient="33333333-3333-4333-8333-333333333333";
const actor={identity:{kind:"native" as const,staffId:"owner",verifiedAccessSubject:"access|owner",email:"owner@example.test",displayName:"Owner",profileVersion:2},admissionVersion:3,verifiedUntil:"2099-01-01T00:00:00.000Z"};
const row={binding_operation_id:selection,client_authority_id:"44444444-4444-4444-8444-444444444444",workspace_id:"workspace-a",issuer:"https://team.cloudflareaccess.com",subject:"access|client",ownership_epoch:null,grant_revision:null,permissions_json:null};
function database(derived:unknown=row){return{withSession(){return this},prepare(sql:string){return{bind(){return{first:async(column?:string)=>sql.includes("SELECT generation")&&column==="generation"?1:sql.includes("WHERE operation_id=?")&&!sql.includes("workspace_binding")?null:derived}}}}}as unknown as D1Database}
const binding={applyAuthorityV3:vi.fn(),getAuthorityV3Status:vi.fn(),applyAuthority:vi.fn(),getAuthorityStatus:vi.fn()};
function deps(enabled=true,db=database()):AuthorityV3OwnerHttpDependencies{return{environment:"staging",expectedHost:"ops-staging.example.test",configuration:{enabled,issuer:"https://team.cloudflareaccess.com",staffAudience:"synthetic-staff-audience",origin,csrfSecret:"authority-v3-owner-secret-at-least-thirty-two-bytes"},database:db,dispatch:{OPS_DB:db,CLIENT_PORTAL_AUTHORITY_V2_OUTBOX_ENABLED:"true",CLIENT_PORTAL_AUTHORITY_V2:binding}}}
async function session(d=deps()){const r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3/session`,{headers:{"X-Native-Staff-Request":"1","Sec-Fetch-Site":"same-origin",Origin:origin}}),d);expect(r.status).toBe(200);return(await r.json()as{csrfToken:string}).csrfToken}
beforeEach(()=>{binding.applyAuthorityV3=vi.fn();binding.getAuthorityV3Status=vi.fn();calls.auth.mockReset().mockResolvedValue(actor);calls.enqueue.mockReset().mockResolvedValue({operationId:op,replayed:false});calls.dispatch.mockReset().mockResolvedValue({status:"acknowledged",operationId:op})});
describe("native owner authority v3 boundary",()=>{
 it("is absent while its dedicated flag is off",async()=>{const r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3/session`),deps(false));expect(r.status).toBe(404);expect(calls.auth).not.toHaveBeenCalled()});
 it("fails closed when either v3 RPC method is missing",async()=>{const d=deps();d.dispatch.CLIENT_PORTAL_AUTHORITY_V2!.applyAuthorityV3=undefined;const r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3/session`),d);expect(r.status).toBe(503);expect(calls.auth).not.toHaveBeenCalled()});
 it("derives and dispatches only the requested operation",async()=>{const d=deps(),csrf=await session(d),r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3`,{method:"POST",headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({operationId:op,selectionId:selection,recipientBindingId:recipient,serviceHomeRead:true})}),d);expect(r.status).toBe(200);expect(calls.enqueue).toHaveBeenCalledWith(d.database,actor,expect.objectContaining({operationId:op,bindingOperationId:selection,recipientBindingId:recipient,expectedOwnershipEpoch:0,expectedGrantRevision:0,permissions:["operations.service_home.read"]}));expect(calls.dispatch).toHaveBeenCalledWith(d.dispatch,op)});
 it("rejects extra input before database derivation",async()=>{const d=deps(),csrf=await session(d),r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3`,{method:"POST",headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({operationId:op,selectionId:selection,recipientBindingId:recipient,serviceHomeRead:true,scope:"all"})}),d);expect(r.status).toBe(400);expect(calls.enqueue).not.toHaveBeenCalled()});
 it.each([["known denial",new Error("portal_authority_v3_denied"),403],["storage failure",new Error("storage"),503]] as const)("classifies %s during enqueue",async(_name,error,status)=>{calls.enqueue.mockRejectedValueOnce(error);const d=deps(),csrf=await session(d),r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3`,{method:"POST",headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({operationId:op,selectionId:selection,recipientBindingId:recipient,serviceHomeRead:true})}),d);expect(r.status).toBe(status)});
 it("returns unavailable for dispatch storage failure and rejected for terminal dispatch",async()=>{const d=deps(),csrf=await session(d),request=()=>new Request(`${origin}/api/native-client-portal/authority-v3`,{method:"POST",headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({operationId:op,selectionId:selection,recipientBindingId:recipient,serviceHomeRead:true})});calls.dispatch.mockRejectedValueOnce(new Error("storage"));expect((await handleAuthorityV3OwnerHttp(request(),d)).status).toBe(503);calls.dispatch.mockResolvedValueOnce({status:"dead",operationId:op});expect((await handleAuthorityV3OwnerHttp(request(),d)).status).toBe(409)});
 it("returns rejected for a pinned dead operation without enqueueing or dispatching",async()=>{const prior={...row,recipient_binding_id:recipient,protocol_version:3,desired_state:"active",authorized_by_staff_id:actor.identity.staffId,authorized_access_subject:actor.identity.verifiedAccessSubject,authorized_admission_version:actor.admissionVersion,authorized_profile_version:actor.identity.profileVersion,authorized_grant_generation:1,state:"dead",permissions_json:'["operations.service_home.read"]'},db={withSession(){return this},prepare(sql:string){return{bind(){return{first:async(column?:string)=>sql.includes("SELECT generation")&&column==="generation"?1:sql.includes("WHERE operation_id=?")&&!sql.includes("workspace_binding")?prior:row}}}}}as unknown as D1Database,d=deps(true,db),csrf=await session(d),r=await handleAuthorityV3OwnerHttp(new Request(`${origin}/api/native-client-portal/authority-v3`,{method:"POST",headers:{Origin:origin,"Sec-Fetch-Site":"same-origin","Content-Type":"application/json","X-CSRF-Token":csrf},body:JSON.stringify({operationId:op,selectionId:selection,recipientBindingId:recipient,serviceHomeRead:true})}),d);expect(r.status).toBe(409);expect(await r.json()).toEqual({operationId:op,status:"rejected"});expect(calls.enqueue).not.toHaveBeenCalled();expect(calls.dispatch).not.toHaveBeenCalled()});
});
