import { readFileSync } from "node:fs";
import { Miniflare } from "miniflare";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { reconcileIncomingRcloneDispatched } from "../src/worker/incoming-rclone-reconcile";
let runtime:Miniflare,db:D1Database;
async function row(id="upload-one",segment=0){await db.batch([db.prepare("INSERT INTO file_requests(id,public_id,title,created_by,expires_at,max_files,max_bytes,session_version) VALUES(?,?, 't','s',datetime('now','+1 day'),500,999999,1)").bind(`r-${id}`,`p-${id}`),db.prepare("INSERT INTO file_request_contributors(id,request_id,name,email,client_address_hash) VALUES(?,?,'n','e@x.test','h')").bind(`c-${id}`,`r-${id}`),db.prepare("INSERT INTO file_request_uploads(id,request_id,contributor_id,object_key,upload_id,original_name,declared_size,content_type,status) VALUES(?,?,?,?,?,'f',1,'x','quarantined')").bind(id,`r-${id}`,`c-${id}`,`q/${id}`,"m"),db.prepare("INSERT INTO file_request_upload_promotion_outbox(upload_id,segment,consecutive_failures,state,instance_id) VALUES(?,?,0,'dispatched',?)").bind(id,segment,`instance-${id}-${segment}`)]);}
describe("incoming rclone reconciliation",()=>{beforeAll(async()=>{runtime=new Miniflare({compatibilityDate:"2026-08-06",modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:"reconcile"}});db=await runtime.getD1Database("DB") as unknown as D1Database;for(const n of ["0090_aliases_incoming_requests.sql","0093_reusable_incoming_uploads.sql","0116_incoming_upload_hardening.sql","0199_incoming_upload_pickup_lifecycle.sql","0211_incoming_upload_verification_lifecycle.sql","0213_incoming_rclone_promotion.sql"]){const s=readFileSync(new URL(`../../client/migrations/${n}`,import.meta.url),"utf8").replace(/^\s*--.*$/gm,"").replace(/^\s*PRAGMA\s+foreign_keys\s*=\s*ON;\s*/i,"");await db.exec(s.replace(/\s*\n\s*/g," "));}});beforeEach(()=>db.exec("DELETE FROM file_request_upload_promotion_outbox;DELETE FROM file_request_upload_promotion_journal;DELETE FROM file_request_uploads;DELETE FROM file_request_contributors;DELETE FROM file_requests;"));afterAll(()=>runtime.dispose());
it("gate false does not read D1",async()=>expect(await reconcileIncomingRcloneDispatched({INCOMING_RCLONE_PROMOTION_ENABLED:"false",DELIVERY_DB:{}} as never)).toEqual({inspected:0,actionable:0,transportFailures:0,skipped:0}));
it("marks confirmed errored status actionable without restart",async()=>{await row();const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};const workflow={get:async()=>({status:async()=>({status:"errored"})})};expect(await reconcileIncomingRcloneDispatched(env as never,workflow as never)).toMatchObject({actionable:1});expect(await db.prepare("SELECT state,error_code FROM file_request_upload_promotion_outbox").first()).toEqual({state:"needs_attention",error_code:"workflow_errored"});});
it("leaves transport failures dispatched and skips newer or terminal work",async()=>{await row("upload-one",0);await db.prepare("INSERT INTO file_request_upload_promotion_outbox(upload_id,segment,consecutive_failures,state,instance_id) VALUES('upload-one',1,0,'dispatched','instance-upload-one-1')").run();await row("upload-two",0);await db.prepare("INSERT INTO file_request_upload_promotion_journal(upload_id,source_identity,source_key,destination_key,state) VALUES('upload-two','{}','s','d','ready')").run();const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};const workflow={get:async()=>{throw new Error("transport")}};expect(await reconcileIncomingRcloneDispatched(env as never,workflow as never)).toMatchObject({inspected:1,transportFailures:1});expect(await db.prepare("SELECT state FROM file_request_upload_promotion_outbox WHERE upload_id='upload-one' AND segment=1").first()).toEqual({state:"dispatched"});});
it("fairly reaches jobs after the first healthy ten",async()=>{for(let i=0;i<11;i++)await row(`upload-${String(i).padStart(2,"0")}`);const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};const calls:string[]=[];const workflow={get:async(id:string)=>({status:async()=>{calls.push(id);return {status:"running"}}})};expect(await reconcileIncomingRcloneDispatched(env as never,workflow as never)).toMatchObject({inspected:10});await reconcileIncomingRcloneDispatched(env as never,workflow as never);expect(calls).toContain("instance-upload-10-0");});});
