import { readFileSync } from "node:fs";
import { Miniflare } from "miniflare";
import { afterAll,beforeAll,beforeEach,describe,expect,it } from "vitest";
import { backfillIncomingRcloneOutbox, drainIncomingRcloneOutbox, enqueueIncomingRcloneSegment } from "../src/worker/incoming-rclone-outbox";
let runtime:Miniflare,db:D1Database;
async function seed(id="upload-one", status="quarantined") { const request=`r-${id}`, contributor=`c-${id}`; await db.batch([db.prepare("INSERT INTO file_requests(id,public_id,title,created_by,expires_at,max_files,max_bytes,session_version) VALUES(?,?,'t','s',datetime('now','+1 day'),500,999999,1)").bind(request,`p-${id}`),db.prepare("INSERT INTO file_request_contributors(id,request_id,name,email,client_address_hash) VALUES(?,?,'n','e@x.test','h')").bind(contributor,request),db.prepare("INSERT INTO file_request_uploads(id,request_id,contributor_id,object_key,upload_id,original_name,declared_size,content_type,status,verification_state) VALUES(?,?,?,?,?,'f.pdf',1,'application/pdf',?,'awaiting_verification')").bind(id,request,contributor,`q/${id}`,"m",status)]); }
describe("incoming rclone outbox",()=>{beforeAll(async()=>{runtime=new Miniflare({compatibilityDate:"2026-08-06",modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:"outbox"}});db=await runtime.getD1Database("DB") as unknown as D1Database;for(const n of ["0090_aliases_incoming_requests.sql","0093_reusable_incoming_uploads.sql","0116_incoming_upload_hardening.sql","0199_incoming_upload_pickup_lifecycle.sql","0211_incoming_upload_verification_lifecycle.sql","0213_incoming_rclone_promotion.sql"]){const s=readFileSync(new URL(`../../client/migrations/${n}`,import.meta.url),"utf8").replace(/^\s*--.*$/gm,"").replace(/^\s*PRAGMA\s+foreign_keys\s*=\s*ON;\s*/i,"");await db.exec(s.replace(/\s*\n\s*/g," "));}});beforeEach(()=>db.exec("DELETE FROM file_request_upload_promotion_outbox;DELETE FROM file_request_uploads;DELETE FROM file_request_contributors;DELETE FROM file_requests;"));afterAll(()=>runtime.dispose());
it("gate false performs no DB work",async()=>{expect(await enqueueIncomingRcloneSegment({INCOMING_RCLONE_PROMOTION_ENABLED:"false",DELIVERY_DB:{}} as never,{uploadId:"upload-one",segment:0,consecutiveFailures:0})).toEqual({enqueued:false,reason:"disabled"});});
it("deduplicates eligible intent and dispatches it once",async()=>{await seed();const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};expect((await enqueueIncomingRcloneSegment(env as never,{uploadId:"upload-one",segment:0,consecutiveFailures:0})).enqueued).toBe(true);expect((await enqueueIncomingRcloneSegment(env as never,{uploadId:"upload-one",segment:0,consecutiveFailures:0})).enqueued).toBe(false);const calls:string[]=[];expect(await drainIncomingRcloneOutbox(env as never,{create:async({id}:{id:string})=>{calls.push(id)},get:async()=>{throw new Error()}} as never)).toMatchObject({dispatched:1});expect(calls).toHaveLength(1);});
it("backfill respects upload/request relationship and excludes rejected",async()=>{await seed("upload-one");await seed("upload-two","rejected");const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};expect(await backfillIncomingRcloneOutbox(env as never)).toBe(1);expect(await db.prepare("SELECT count(*) count FROM file_request_upload_promotion_outbox").first()).toEqual({count:1});});
it("leases once across parallel drains",async()=>{await seed();const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};await enqueueIncomingRcloneSegment(env as never,{uploadId:"upload-one",segment:0,consecutiveFailures:0});let creates=0;const workflow={create:async()=>{creates++},get:async()=>{throw new Error()}};await Promise.all([drainIncomingRcloneOutbox(env as never,workflow as never),drainIncomingRcloneOutbox(env as never,workflow as never)]);expect(creates).toBe(1);});
it("marks repeatedly unconfirmed dispatches actionable",async()=>{await seed();const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};await enqueueIncomingRcloneSegment(env as never,{uploadId:"upload-one",segment:0,consecutiveFailures:0});const bad={create:async()=>{throw new Error("lost")},get:async()=>{throw new Error("missing")}};for(let i=0;i<3;i++){await db.prepare("UPDATE file_request_upload_promotion_outbox SET next_attempt_at=NULL,state='pending' WHERE upload_id='upload-one'").run();await drainIncomingRcloneOutbox(env as never,bad as never);}expect(await db.prepare("SELECT state,error_code FROM file_request_upload_promotion_outbox WHERE upload_id='upload-one'").first()).toEqual({state:"needs_attention",error_code:"dispatch_unconfirmed"});});
it("backfill is bounded to ten",async()=>{for(let i=0;i<11;i++)await seed(`upload-${String(i).padStart(2,"0")}`);const env={INCOMING_RCLONE_PROMOTION_ENABLED:"true",DELIVERY_DB:db};expect(await backfillIncomingRcloneOutbox(env as never)).toBe(10);});});
