import { readFileSync } from "node:fs";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { Miniflare } from "miniflare";
import { splitD1MigrationStatements } from "../../client/test/helpers/d1-migrations";

let runtime: Miniflare, db: D1Database; let sequence = 0;
const uuid = () => `10000000-0000-4000-8000-${(++sequence).toString(16).padStart(12, "0")}`;
const hash = "a".repeat(64), responseHash = "b".repeat(64), publicId = "c".repeat(32);
type Seed = ReturnType<typeof seed>;
function seed(overrides: Partial<{ sourceInstanceId: string; applicationId: string; historyEpochId: string }> = {}) { const n = ++sequence; return { commandId: uuid(), externalProjectId: `project-${n}`, sourceInstanceId: overrides.sourceInstanceId ?? uuid(), applicationId: overrides.applicationId ?? uuid(), historyEpochId: overrides.historyEpochId ?? uuid(), staffId: `staff-${n}`, subject: `subject-${n}`, email: `staff-${n}@example.test` }; }
async function migrate(name: string) { const sql = readFileSync(new URL(`../migrations/${name}`, import.meta.url), "utf8"); await db.batch(splitD1MigrationStatements(sql).map(statement => db.prepare(statement))); }
function body(v: Seed, operation: "create" | "update" | "bind" = "create") { return operation === "bind" ? JSON.stringify({ commandId: v.commandId, externalId: v.externalProjectId, expectedPublicId: publicId, expectedRevision: "7", expectedProjectionSha256: hash, expectedAuthorizationGeneration: "0" }) : operation === "update" ? JSON.stringify({ commandId: v.commandId, externalId: v.externalProjectId, expectedRevision: "7", expectedProjectionSha256: hash, expectedAuthorizationGeneration: "1", project: {} }) : JSON.stringify({ commandId: v.commandId, externalId: v.externalProjectId, expectedAuthorizationGeneration: "0", project: {}, organization: {}, client: null }); }
async function native(v: Seed, operation: "create" | "update" | "bind" = "create", commandJson = body(v, operation)) { await db.batch([
  db.prepare("INSERT INTO native_staff_admissions VALUES(?,1,?,1)").bind(v.staffId, v.subject), db.prepare("INSERT INTO native_staff_profiles VALUES(?,?,1)").bind(v.staffId, v.email),
  db.prepare("INSERT INTO project_alpha_project_destinations(external_project_id,source_id,application_id,destination_base_url,expected_source_instance_id,expected_history_epoch_id) VALUES(?,'project-alpha:primary',?,'https://alpha.example.test',?,?)").bind(v.externalProjectId, v.applicationId, v.sourceInstanceId, v.historyEpochId),
  db.prepare("INSERT INTO native_project_grants(id,staff_id,capability,effect,scope_kind,external_project_id,granted_by) VALUES(?,?,'project.shared.sync','allow','exact_project',?,?)").bind(`grant-${v.staffId}`, v.staffId, v.externalProjectId, v.staffId),
  db.prepare("INSERT INTO native_project_command_proofs(command_id,external_project_id,actor_staff_id,actor_access_subject,actor_admission_version,actor_profile_version,actor_email,verified_until,grant_generation,scopes_json) VALUES(?,?,?,?,1,1,?,'2999-01-01T00:00:00.000Z',1,'[]')").bind(v.commandId, v.externalProjectId, v.staffId, v.subject, v.email),
  db.prepare("INSERT INTO project_alpha_project_outbox(command_id,external_project_id,operation,command_json,source_id,application_id,destination_base_url,expected_source_instance_id,origin_snapshot_json,state,attempts,next_attempt_at,expected_history_epoch_id) VALUES(?,?,?,?,'project-alpha:primary',?,'https://alpha.example.test',?,?,'pending',0,0,?)").bind(v.commandId, v.externalProjectId, operation, commandJson, v.applicationId, v.sourceInstanceId, JSON.stringify({ actorId: v.staffId }), v.historyEpochId),
  db.prepare("INSERT INTO native_project_command_reservations(command_id) VALUES(?)").bind(v.commandId),
]); }
async function nativeCommandForExistingDestination(v: Seed, operation: "update", commandJson: string) { await db.batch([
  db.prepare("INSERT INTO native_project_command_proofs(command_id,external_project_id,actor_staff_id,actor_access_subject,actor_admission_version,actor_profile_version,actor_email,verified_until,grant_generation,scopes_json) VALUES(?,?,?,?,1,1,?,'2999-01-01T00:00:00.000Z',1,'[]')").bind(v.commandId, v.externalProjectId, v.staffId, v.subject, v.email),
  db.prepare("INSERT INTO project_alpha_project_outbox(command_id,external_project_id,operation,command_json,source_id,application_id,destination_base_url,expected_source_instance_id,origin_snapshot_json,state,attempts,next_attempt_at,expected_history_epoch_id) VALUES(?,?,?,?,'project-alpha:primary',?,'https://alpha.example.test',?,?,'pending',0,0,?)").bind(v.commandId, v.externalProjectId, operation, commandJson, v.applicationId, v.sourceInstanceId, JSON.stringify({ actorId: v.staffId }), v.historyEpochId),
  db.prepare("INSERT INTO native_project_command_reservations(command_id) VALUES(?)").bind(v.commandId),
]); }
async function mappedUpdate(removeField?: "expectedRevision" | "expectedProjectionSha256" | "expectedAuthorizationGeneration") { const established = seed(); await native(established); await db.prepare("UPDATE project_alpha_project_outbox SET state='leased',lease_token='lease',lease_expires_at=1 WHERE command_id=?").bind(established.commandId).run(); await db.prepare("INSERT INTO project_alpha_project_mappings(external_project_id,source_id,source_instance_id,application_id,project_alpha_public_id,establishment_kind,establishment_command_id,create_command_id,history_epoch_id) VALUES(?,'project-alpha:primary',?,?,?,'create',?,?,?)").bind(established.externalProjectId, established.sourceInstanceId, established.applicationId, publicId, established.commandId, established.commandId, established.historyEpochId).run(); await db.prepare("UPDATE project_alpha_project_outbox SET state='acknowledged',lease_token=NULL,lease_expires_at=NULL,outcome_json='{}' WHERE command_id=?").bind(established.commandId).run(); const v = { ...established, commandId: uuid() }; const command = JSON.parse(body(v, "update")) as Record<string, unknown>; if (removeField) delete command[removeField]; await nativeCommandForExistingDestination(v, "update", JSON.stringify(command)); return v; }
const fingerprint = (v: Seed, value = hash) => db.prepare("INSERT INTO project_alpha_project_v2_request_fingerprints(command_id,request_sha256) VALUES(?,?)").bind(v.commandId, value);
const event = (v: Seed, version: number, state: string, value = hash, occurredAt = "2026-09-15T12:35:56.789Z") => db.prepare("INSERT INTO project_alpha_project_v2_events(command_id,state_version,transition_id,request_sha256,state,occurred_at) VALUES(?,?,?,?,?,?)").bind(v.commandId, version, uuid(), value, state, occurredAt);
function ack(v: Seed, overrides: Record<string, unknown> = {}) { const value = { acknowledgement_id: uuid(), command_id: v.commandId, acknowledged_state_version: 2, request_sha256: hash, source_instance_id: v.sourceInstanceId, application_id: v.applicationId, history_epoch_id: v.historyEpochId, destination_origin: "https://alpha.example.test", project_alpha_public_id: publicId, project_alpha_revision: "7", projection_sha256: hash, authorization_generation: "1", pa_request_id: uuid(), pa_replayed: 0, response_sha256: responseHash, ...overrides }; return { value, statement: db.prepare("INSERT INTO project_alpha_project_v2_validated_acknowledgements(acknowledgement_id,command_id,acknowledged_state_version,request_sha256,source_instance_id,application_id,history_epoch_id,destination_origin,project_alpha_public_id,project_alpha_revision,projection_sha256,authorization_generation,pa_request_id,pa_replayed,response_sha256) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(...Object.values(value)) }; }
function receipt(v: Seed, acknowledgementId: string, overrides: Record<string, unknown> = {}) { const value = { receipt_id: uuid(), acknowledgement_id: acknowledgementId, command_id: v.commandId, request_sha256: hash, source_instance_id: v.sourceInstanceId, application_id: v.applicationId, history_epoch_id: v.historyEpochId, destination_origin: "https://alpha.example.test", project_alpha_public_id: publicId, project_alpha_revision: "7", projection_sha256: hash, authorization_generation: "1", pa_request_id: uuid(), pa_replayed: 0, response_sha256: responseHash, ...overrides }; return db.prepare("INSERT INTO project_alpha_project_v2_success_receipts(receipt_id,acknowledgement_id,command_id,request_sha256,source_instance_id,application_id,history_epoch_id,destination_origin,project_alpha_public_id,project_alpha_revision,projection_sha256,authorization_generation,pa_request_id,pa_replayed,response_sha256) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(...Object.values(value)); }
let legacy: Seed; let preservedBeforeMigration: unknown[];
beforeAll(async () => { runtime = new Miniflare({ modules: true, compatibilityDate: "2026-08-06", script: "export default {fetch(){return new Response('ok')}}", d1Databases: ["OPS_DB"] }); db = await runtime.getD1Database("OPS_DB") as D1Database;
  await migrate("0062_project_alpha_project_outbox.sql"); await migrate("0063_project_alpha_project_adoption.sql"); await migrate("0064_project_alpha_project_history_epoch.sql");
  await db.batch(splitD1MigrationStatements("CREATE TABLE native_staff_admissions(staff_id TEXT PRIMARY KEY,active INTEGER,bound_access_subject TEXT,version INTEGER); CREATE TABLE native_staff_profiles(staff_id TEXT PRIMARY KEY,login_email TEXT,version INTEGER); CREATE TABLE native_business_areas(id TEXT PRIMARY KEY,active INTEGER); CREATE TABLE native_business_divisions(id TEXT PRIMARY KEY,business_area_id TEXT,active INTEGER,UNIQUE(business_area_id,id)); CREATE TABLE operations_directory_records(record_id TEXT PRIMARY KEY,record_kind TEXT); CREATE TABLE project_alpha_directory_mappings(source_id TEXT,source_instance_id TEXT,application_id TEXT,history_epoch_id TEXT,resource_type TEXT,external_id TEXT,project_alpha_public_id TEXT); CREATE TABLE operations_directory_client_organizations(client_record_id TEXT,organization_record_id TEXT);").map(s => db.prepare(s)));
  legacy = seed(); await db.batch([db.prepare("INSERT INTO project_alpha_project_destinations(external_project_id,source_id,application_id,destination_base_url,expected_source_instance_id,expected_history_epoch_id) VALUES(?,'project-alpha:primary',?,'https://legacy.example.test',?,?)").bind(legacy.externalProjectId, legacy.applicationId, legacy.sourceInstanceId, legacy.historyEpochId), db.prepare("INSERT INTO project_alpha_project_outbox(command_id,external_project_id,operation,command_json,source_id,application_id,destination_base_url,expected_source_instance_id,origin_snapshot_json,state,attempts,next_attempt_at,expected_history_epoch_id) VALUES(?,?,'create',?,'project-alpha:primary',?,'https://legacy.example.test',?,?,'pending',0,0,?)").bind(legacy.commandId, legacy.externalProjectId, body(legacy), legacy.applicationId, legacy.sourceInstanceId, JSON.stringify({ actorId: legacy.staffId }), legacy.historyEpochId)]);
  await db.prepare("UPDATE project_alpha_project_outbox SET state='leased',lease_token='legacy-lease',lease_expires_at=1 WHERE command_id=?").bind(legacy.commandId).run();
  await db.prepare("INSERT INTO project_alpha_project_mappings(external_project_id,source_id,source_instance_id,application_id,project_alpha_public_id,establishment_kind,establishment_command_id,create_command_id,history_epoch_id) VALUES(?,'project-alpha:primary',?,?,?,'create',?,?,?)").bind(legacy.externalProjectId, legacy.sourceInstanceId, legacy.applicationId, "e".repeat(32), legacy.commandId, legacy.commandId, legacy.historyEpochId).run();
  await db.prepare("UPDATE project_alpha_project_outbox SET state='acknowledged',lease_token=NULL,lease_expires_at=NULL,outcome_json='{}' WHERE command_id=?").bind(legacy.commandId).run();
  await migrate("0086_native_shared_projects.sql");
  await db.exec("CREATE TABLE delivery_public_shares(id TEXT PRIMARY KEY,project_id TEXT,url TEXT); INSERT INTO operations_shared_projects(external_project_id,name,lifecycle,scopes_json) VALUES('shared-legacy','Shared','active','[]'); INSERT INTO delivery_public_shares VALUES('share-1','shared-legacy','https://public.example.test/share/secret');");
  preservedBeforeMigration = await Promise.all([
    db.prepare("SELECT * FROM project_alpha_project_mappings WHERE external_project_id=?").bind(legacy.externalProjectId).all(),
    db.prepare("SELECT * FROM operations_shared_projects WHERE external_project_id='shared-legacy'").all(),
    db.prepare("SELECT * FROM delivery_public_shares WHERE id='share-1'").all(),
  ]).then(results => results.map(result => result.results));
  await migrate("0119_project_alpha_project_v2_persistence_ledger.sql"); });
afterAll(async () => runtime.dispose());

describe("0119 dormant PA project v2 persistence ledger", () => {
  it("admits only a real 0086 proof/reservation and records an immutable canonical pending request", async () => { const v = seed(); await native(v); await fingerprint(v).run(); await event(v, 1, "pending").run(); await expect(fingerprint(v).run()).rejects.toThrow(); await expect(event(v, 2, "pending", hash, "not-a-timestamp").run()).rejects.toThrow(); });
  it("allows only append-only pending/uncertain retries and makes conflict, rejected, and acknowledged terminal", async () => { const v = seed(); await native(v); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "uncertain").run(); await event(v, 3, "pending").run(); await event(v, 4, "conflict").run(); await expect(event(v, 5, "pending").run()).rejects.toThrow(/transition is invalid/); for (const terminal of ["rejected", "acknowledged"] as const) { const other = seed(); await native(other); await fingerprint(other).run(); await event(other, 1, "pending").run(); await event(other, 2, terminal).run(); await expect(event(other, 3, "uncertain").run()).rejects.toThrow(/transition is invalid/); } });
  it("requires a private validated acknowledgement before an exact immutable receipt", async () => { const v = seed(); await native(v); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(receipt(v, uuid()).run()).rejects.toThrow(); const a = ack(v); await a.statement.run(); await expect(receipt(v, a.value.acknowledgement_id, { projection_sha256: responseHash, pa_request_id: a.value.pa_request_id }).run()).rejects.toThrow(/not exact/); await receipt(v, a.value.acknowledgement_id, { pa_request_id: a.value.pa_request_id }).run(); await expect(db.prepare("UPDATE project_alpha_project_v2_success_receipts SET pa_replayed=1 WHERE command_id=?").bind(v.commandId).run()).rejects.toThrow(/immutable/); });
  it("binds validated acknowledgements and receipts to the reserved destination origin", async () => { const v = seed(); await native(v); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(ack(v, { destination_origin: "https://other.example.test" }).statement.run()).rejects.toThrow(/not exact/); const a = ack(v); await a.statement.run(); await expect(receipt(v, a.value.acknowledgement_id, { destination_origin: "https://other.example.test", pa_request_id: a.value.pa_request_id }).run()).rejects.toThrow(/not exact/); });
  it("fences bind receipts to the exact public id, revision, hash, and next authority generation", async () => { const v = seed(); await native(v, "bind"); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(ack(v, { project_alpha_public_id: "d".repeat(32) }).statement.run()).rejects.toThrow(/not exact/); await expect(ack(v, { authorization_generation: "01" }).statement.run()).rejects.toThrow(); await ack(v).statement.run(); });
  it("rejects acknowledgements when required command preconditions are absent", async () => { for (const operation of ["create", "bind"] as const) { const v = seed(); const malformed = JSON.parse(body(v, operation)) as Record<string, unknown>; delete malformed.expectedAuthorizationGeneration; await native(v, operation, JSON.stringify(malformed)); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(ack(v).statement.run()).rejects.toThrow(/not exact/); } });
  it("settles mapped updates only for complete preconditions and exact mapping, revision, and generation", async () => { const v = await mappedUpdate(); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(ack(v, { project_alpha_public_id: "d".repeat(32) }).statement.run()).rejects.toThrow(/not exact/); await expect(ack(v, { source_instance_id: uuid() }).statement.run()).rejects.toThrow(/not exact/); await expect(ack(v, { history_epoch_id: uuid() }).statement.run()).rejects.toThrow(/not exact/); await expect(ack(v, { project_alpha_revision: "6" }).statement.run()).rejects.toThrow(/not exact/); await expect(ack(v, { authorization_generation: "2" }).statement.run()).rejects.toThrow(/not exact/); await ack(v).statement.run(); });
  it("rejects mapped updates missing any required optimistic-concurrency field", async () => { for (const field of ["expectedRevision", "expectedProjectionSha256", "expectedAuthorizationGeneration"] as const) { const v = await mappedUpdate(field); await fingerprint(v).run(); await event(v, 1, "pending").run(); await event(v, 2, "acknowledged").run(); await expect(ack(v).statement.run()).rejects.toThrow(/not exact/); } });
  it("revalidates the actual live-authority view and isolates source, epoch, and PA public-id collisions", async () => { const v = seed(); await native(v); await fingerprint(v).run(); await event(v, 1, "pending").run(); await db.prepare("UPDATE native_staff_admissions SET active=0 WHERE staff_id=?").bind(v.staffId).run(); await expect(event(v, 2, "acknowledged").run()).rejects.toThrow(/current native authority/); await db.prepare("UPDATE native_staff_admissions SET active=1 WHERE staff_id=?").bind(v.staffId).run(); await event(v, 2, "acknowledged").run(); await expect(ack(v, { history_epoch_id: uuid() }).statement.run()).rejects.toThrow(/not exact/); const mapped = seed(); await native(mapped); await db.prepare("UPDATE project_alpha_project_outbox SET state='leased',lease_token='lease',lease_expires_at=1 WHERE command_id=?").bind(mapped.commandId).run(); await db.prepare("INSERT INTO project_alpha_project_mappings(external_project_id,source_id,source_instance_id,application_id,project_alpha_public_id,establishment_kind,establishment_command_id,create_command_id,history_epoch_id) VALUES(?,'project-alpha:primary',?,?,?,'create',?,?,?)").bind(mapped.externalProjectId, mapped.sourceInstanceId, mapped.applicationId, publicId, mapped.commandId, mapped.commandId, mapped.historyEpochId).run(); const collision = seed({ sourceInstanceId: mapped.sourceInstanceId, applicationId: mapped.applicationId, historyEpochId: mapped.historyEpochId }); await native(collision); await fingerprint(collision).run(); await event(collision, 1, "pending").run(); await event(collision, 2, "acknowledged").run(); await expect(ack(collision).statement.run()).rejects.toThrow(/not exact/); });
  it("excludes pre-0086 history and preserves exact mapping, shared-project, and public-link rows across migration and rejection", async () => { await expect(fingerprint(legacy).run()).rejects.toThrow(/live native reservation/); const after = await Promise.all([db.prepare("SELECT * FROM project_alpha_project_mappings WHERE external_project_id=?").bind(legacy.externalProjectId).all(), db.prepare("SELECT * FROM operations_shared_projects WHERE external_project_id='shared-legacy'").all(), db.prepare("SELECT * FROM delivery_public_shares WHERE id='share-1'").all()]).then(results => results.map(result => result.results)); expect(after).toEqual(preservedBeforeMigration); });
});
