import { Hono } from "hono";
import { readFileSync } from "node:fs";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { Env, StaffPrincipal } from "../src/worker/types";

const mocks=vi.hoisted(()=>({scope:vi.fn(),native:vi.fn(),bootstrap:vi.fn()}));
vi.mock("../src/worker/acl",()=>({sqlScope:mocks.scope}));
vi.mock("../src/worker/native-staff-auth",()=>({authenticateNativeStaffWithAdmissionVersion:mocks.native}));
vi.mock("../src/worker/project-alpha-directory-v2-bootstrap-dispatcher",()=>({bootstrapProjectAlphaDirectoryOrganization:mocks.bootstrap}));
import { PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ROUTE, registerProjectAlphaDirectoryV2BootstrapAcceptanceRoutes } from "../src/worker/project-alpha-directory-v2-bootstrap-acceptance-routes";

const principal:StaffPrincipal={id:"native-admin",email:"native@example.test",displayName:"Native",accessSubject:"native-subject",projectAlphaUserId:null};
const body={sourceId:"project-alpha:directory-staging",expectedApplicationId:"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",commandId:"bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",recordId:"staging-directory-acceptance-fixture-01",scopes:[{businessAreaId:"drone",divisionId:null}],profile:{name:"Directory acceptance fixture",generalEmail:"",generalPhone:"",addressLine1:"",addressLine2:"",city:"",state:"",postalCode:"",country:""}};
function fixture(enabled=true,administrator=true,environment="staging"){const app=new Hono<{Bindings:Env;Variables:{principal:StaffPrincipal;administrator:boolean}}>();app.use("*",async(c,n)=>{c.set("principal",principal);c.set("administrator",administrator);await n();});registerProjectAlphaDirectoryV2BootstrapAcceptanceRoutes(app);const env={ENVIRONMENT:environment,PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ENABLED:enabled?"true":"false",TEAM_DOMAIN:"https://team.example",OPERATIONS_AUD:"ops",NATIVE_STAFF_ONBOARDING_AUD:"onboarding",OPS_DB:{}} as unknown as Env;const send=(value:unknown=body,headers:Record<string,string>={})=>app.request(`https://ops.example${PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ROUTE}`,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":body.commandId,...headers},body:typeof value==="string"?value:JSON.stringify(value)},env);return{send,app,env};}
describe("Directory-v2 staging bootstrap acceptance route",()=>{beforeEach(()=>{vi.clearAllMocks();mocks.scope.mockResolvedValue({global:true,deniedGlobal:false});mocks.native.mockResolvedValue({admissionVersion:2,identity:{staffId:principal.id,email:principal.email,verifiedAccessSubject:principal.accessSubject}});mocks.bootstrap.mockResolvedValue({status:"acknowledged",publicId:"a".repeat(32),revision:"1"});});
it("mounts the disabled-route camouflage before global /api authentication",()=>{const source=readFileSync(new URL("../src/worker/index.ts",import.meta.url),"utf8"),guard=source.indexOf("app.use(PROJECT_ALPHA_DIRECTORY_V2_BOOTSTRAP_ACCEPTANCE_ROUTE"),authentication=source.indexOf("app.use(\"/api/*\"");expect(guard).toBeGreaterThanOrEqual(0);expect(guard).toBeLessThan(authentication);});
it("is default-off and production-hidden before parsing or native authentication",async()=>{expect((await fixture(false).send()).status).toBe(404);expect((await fixture(true,true,"production").send()).status).toBe(404);expect(mocks.native).not.toHaveBeenCalled();expect(mocks.bootstrap).not.toHaveBeenCalled();});
it("requires administrator, deny-aware integrations.manage, and exact native identity",async()=>{expect((await fixture(true,false).send()).status).toBe(403);mocks.scope.mockResolvedValueOnce({global:true,deniedGlobal:true});expect((await fixture().send()).status).toBe(403);mocks.native.mockResolvedValueOnce({admissionVersion:2,identity:{staffId:"other",email:principal.email,verifiedAccessSubject:principal.accessSubject}});expect((await fixture().send()).status).toBe(403);expect(mocks.bootstrap).not.toHaveBeenCalled();});
it("rejects malformed bodies and a different idempotency key without dispatching",async()=>{expect((await fixture().send({...body,secret:"no"})).status).toBe(400);expect((await fixture().send(body,{"Idempotency-Key":"cccccccc-cccc-4ccc-8ccc-cccccccccccc"})).status).toBe(400);expect((await fixture().send({...body,recordId:"production-record"})).status).toBe(400);expect(mocks.bootstrap).not.toHaveBeenCalled();});
it("passes the separate Directory selection plus native admission version to the guarded dispatcher",async()=>{const response=await fixture().send();expect(response.status).toBe(200);await expect(response.json()).resolves.toEqual({sourceId:body.sourceId,commandId:body.commandId,recordId:body.recordId,outcome:{status:"acknowledged",publicId:"a".repeat(32),revision:"1"}});expect(mocks.bootstrap).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({...body,actor:{staffId:principal.id,accessSubject:principal.accessSubject,admissionVersion:2}}));});
});
