import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { Hono } from "hono";
import { Miniflare } from "miniflare";

const mocks = vi.hoisted(() => ({ sqlScope: vi.fn(), authenticate: vi.fn() }));
vi.mock("../src/worker/acl", async importOriginal => ({ ...await importOriginal<typeof import("../src/worker/acl")>(), sqlScope: mocks.sqlScope }));
vi.mock("../src/worker/native-staff-auth", () => ({ authenticateNativeStaffWithAdmissionVersion: mocks.authenticate }));
import { registerStagingDirectoryOwnerViewGrantRoute } from "../src/worker/staging-directory-owner-view-grant";
import type { Env, StaffPrincipal } from "../src/worker/types";

const principal: StaffPrincipal = { id: "staff-beau-koltz", email: "owner@example.test", displayName: "Owner", accessSubject: "access|owner", projectAlphaUserId: null };
const context = { waitUntil() {}, passThroughOnException() {} } as unknown as ExecutionContext;
const baseEnv = { ENVIRONMENT: "staging", STAGING_DIRECTORY_PROFILE_VIEW_GRANT_ENABLED: "true", EXPECTED_HOST: "ops-staging.ledgetopdroneservices.com", OPERATIONS_SESSION_SECRET: "session-secret", AUDIT_IP_SECRET: "audit-secret-that-is-at-least-32-characters" } as unknown as Env;
const live: Miniflare[] = [];

async function fixture() {
  const mf = new Miniflare({ compatibilityDate: "2026-08-06", modules: true, script: "export default { fetch() { return new Response('ok') } }", d1Databases: { OPS_DB: "staging-owner-grant-route" } });
  live.push(mf); const db = await mf.getD1Database("OPS_DB") as unknown as D1Database;
  await db.batch([
    db.prepare("CREATE TABLE staff_users(id TEXT PRIMARY KEY,email TEXT NOT NULL,display_name TEXT NOT NULL)"), db.prepare("CREATE TABLE roles(id TEXT PRIMARY KEY)"), db.prepare("CREATE TABLE permissions(key TEXT PRIMARY KEY)"), db.prepare("CREATE TABLE role_permissions(role_id TEXT,permission_key TEXT)"),
    db.prepare("CREATE TABLE staff_role_assignments(id TEXT PRIMARY KEY,staff_id TEXT,role_id TEXT,scope TEXT,division_id TEXT,scope_key TEXT)"), db.prepare("CREATE TABLE staff_permission_overrides(id TEXT PRIMARY KEY,staff_id TEXT,permission_key TEXT,effect TEXT,scope TEXT,division_id TEXT,scope_key TEXT)"),
    db.prepare("CREATE TABLE native_staff_admissions(staff_id TEXT PRIMARY KEY,bound_access_subject TEXT,active INTEGER,admitted_by TEXT,version INTEGER)"), db.prepare("CREATE TABLE native_staff_profiles(staff_id TEXT PRIMARY KEY,login_email TEXT,version INTEGER)"),
    db.prepare("CREATE TABLE native_directory_grants(id TEXT PRIMARY KEY,staff_id TEXT,permission TEXT,effect TEXT,scope_kind TEXT,business_area_id TEXT,division_id TEXT,resource_id TEXT,active INTEGER,granted_by TEXT)"), db.prepare("CREATE UNIQUE INDEX native_directory_grant_identity ON native_directory_grants(staff_id,permission,effect,scope_kind,ifnull(business_area_id,''),ifnull(division_id,''),ifnull(resource_id,''))"),
    db.prepare("CREATE TABLE audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_type TEXT,actor_id TEXT,actor_email TEXT,actor_display_name TEXT,action TEXT,entity_type TEXT,entity_id TEXT,division_id TEXT,details_json TEXT,client_address_hash TEXT)"),
    db.prepare("INSERT INTO staff_users VALUES('staff-beau-koltz','owner@example.test','Owner')"), db.prepare("INSERT INTO roles VALUES('role-owner')"), db.prepare("INSERT INTO permissions VALUES('integrations.manage')"), db.prepare("INSERT INTO role_permissions VALUES('role-owner','integrations.manage')"), db.prepare("INSERT INTO staff_role_assignments VALUES('owner-role','staff-beau-koltz','role-owner','global',NULL,'global')"), db.prepare("INSERT INTO native_staff_admissions VALUES('staff-beau-koltz','access|owner',1,'staff-beau-koltz',7)"), db.prepare("INSERT INTO native_staff_profiles VALUES('staff-beau-koltz','owner@example.test',3)"),
  ]); return db;
}
function appFor(db: D1Database) { const app = new Hono<any>(); app.use("*", async (c, next) => { c.set("principal", principal); c.set("administrator", true); await next(); }); registerStagingDirectoryOwnerViewGrantRoute(app); return { app, env: { ...baseEnv, OPS_DB: db } as Env }; }
async function post(app: Hono<any>, env: Env, body: unknown, key: string, host = "ops-staging.ledgetopdroneservices.com") { return app.fetch(new Request(`https://${host}/api/admin/staging/directory/owner-profile-view-grant`, { method: "POST", headers: { Host: host, Origin: `https://${host}`, "CF-Connecting-IP": "192.0.2.1", "Idempotency-Key": key, "Content-Type": "application/json" }, body: JSON.stringify(body) }), env, context); }
afterEach(async () => { await Promise.all(live.splice(0).map(mf => mf.dispose())); });
beforeEach(() => { mocks.sqlScope.mockReset().mockResolvedValue({ global: true, deniedGlobal: false }); mocks.authenticate.mockReset().mockResolvedValue({ identity: { staffId: principal.id, email: principal.email, verifiedAccessSubject: principal.accessSubject, profileVersion: 3 }, admissionVersion: 7, verifiedUntil: "2099-01-01T00:00:00.000Z" }); });

describe("staging owner profile-view grant route SQL", () => {
  it("uses real D1 SQL and records the ensure audit", async () => { const db = await fixture(); const { app, env } = appFor(db); const response = await post(app, env, { confirm: true }, "11111111-1111-4111-8111-111111111111"); expect(response.status).toBe(201); expect(await db.prepare("SELECT permission,effect,scope_kind FROM native_directory_grants").first()).toEqual({ permission: "directory.profile.view", effect: "allow", scope_kind: "global" }); expect(await db.prepare("SELECT action,entity_id FROM audit_events").first()).toMatchObject({ action: expect.stringContaining("owner_profile_view_grant"), entity_id: "11111111-1111-4111-8111-111111111111" }); });
  it("preserves one grant for duplicate and concurrent callers", async () => { const db = await fixture(); const { app, env } = appFor(db); const results = await Promise.all([post(app, env, { confirm: true }, "22222222-2222-4222-8222-222222222222"), post(app, env, { confirm: true }, "33333333-3333-4333-8333-333333333333")]); expect(results.filter(r => r.status === 201)).toHaveLength(1); expect(results.filter(r => r.status === 200)).toHaveLength(1); expect((await post(app, env, { confirm: true }, "44444444-4444-4444-8444-444444444444")).status).toBe(200); expect(await db.prepare("SELECT COUNT(*) count FROM native_directory_grants").first<number>("count")).toBe(1); });
  it("fences stale identity, denied scope, host, and expiry", async () => { const db = await fixture(); const { app, env } = appFor(db); mocks.authenticate.mockResolvedValueOnce({ identity: { staffId: principal.id, email: principal.email, verifiedAccessSubject: principal.accessSubject, profileVersion: 3 }, admissionVersion: 6, verifiedUntil: "2099-01-01T00:00:00.000Z" }); expect((await post(app, env, { confirm: true }, "66666666-6666-4666-8666-666666666666")).status).toBe(409); mocks.sqlScope.mockResolvedValueOnce({ global: true, deniedGlobal: true }); expect((await post(app, env, { confirm: true }, "77777777-7777-4777-8777-777777777777")).status).toBe(403); expect((await post(app, env, { confirm: true }, "88888888-8888-4888-8888-888888888888", "wrong-host.test")).status).toBe(404); mocks.authenticate.mockResolvedValueOnce({ identity: { staffId: principal.id, email: principal.email, verifiedAccessSubject: principal.accessSubject, profileVersion: 3 }, admissionVersion: 7, verifiedUntil: "2000-01-01T00:00:00.000Z" }); expect((await post(app, env, { confirm: true }, "99999999-9999-4999-8999-999999999999")).status).toBe(409); });
  it("rolls back the grant when the audit statement fails in the batch", async () => { const db = await fixture(); await db.prepare("CREATE TRIGGER audit_fail BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'audit failure'); END").run(); const { app, env } = appFor(db); expect((await post(app, env, { confirm: true }, "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa")).status).toBe(500); expect(await db.prepare("SELECT COUNT(*) count FROM native_directory_grants").first<number>("count")).toBe(0); });
});
