import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import test from"node:test";
import{STAGING_TARGET}from"./staging-onboarding-native-only-authority-packet.mjs";import{prepareRelationshipRecoveryAuthorityV184 as prepare,openRelationshipRecoveryAuthorityV184 as open,closeRelationshipRecoveryAuthorityV184 as close,reconcileRelationshipRecoveryAuthorityWindowV184 as reconcile}from"./staging-relationship-generation-recovery-authority-v184-window.mjs";
const ids=Array.from({length:20},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,"0")}`),artifact=input=>({schemaVersion:1,input,approval:{approval_id:input.approval.approvalId},receipt:{command_id:input.approval.commandId,approval_id:input.approval.approvalId,canonical_plan_sha256:"plan",result_sha256:"result"}});
function setup(extra={}){let i=0;const events=[];return{events,deps:{root:"C:/fake",withBinding:async(_,fn)=>fn({db:{},target:STAGING_TARGET}),snapshot:async()=>({grants:[]}),clock:async()=>"2026-10-10T12:00:00.000Z",randomUUID:()=>ids[i++],compile:input=>artifact(input),createEvidence:()=>{events.push("create");return{evidenceDir:"C:/fake/evidence"}},writeEvidence:(_r,_d,_n,v)=>{events.push("write");return v.input.phase==="provision"?"provision.json":"revoke.json"},apply:async()=>{events.push("apply");return{status:"committed"}},readArtifact:()=>artifact({phase:"provision",approval:{grantIds:ids.slice(2,8)},input:"saved"}),reconcile:async()=>({status:"committed",receipt:{}}),...extra}}}
const real=state=>{for(const key of["createEvidence","writeEvidence","readArtifact"])delete state.deps[key]};
test("prepare is read-only, target-bound, and emits only the mixed-scope v2 contract",async()=>{const s=setup(),result=await prepare("c",s.deps);assert.equal(result.mutationsPerformed,false);assert.equal(result.artifact.input.schemaVersion,2);assert.equal(result.artifact.input.target.clientBusinessAreaId,"staging-native-only-portal-acceptance-20261008-window-1");assert.equal(result.artifact.input.target.organizationBusinessAreaId,"drone-services-staging");assert.deepEqual(s.events,[]);const wrong=setup({withBinding:async(_,fn)=>fn({db:{},target:{...STAGING_TARGET,databaseId:"wrong"}})});await assert.rejects(prepare("c",wrong.deps),/trusted staging target/)});
test("apply saves before mutation, bounds output, and handles lost response",async()=>{const s=setup({apply:async()=>{s.events.push("apply");return{status:"committed-after-response-recovery",receipt:{canonical_plan_json:"private"}}}}),result=await open("c",s.deps);assert.deepEqual(s.events,["create","write","apply"]);assert.equal(result.outcome.status,"committed-after-response-recovery");assert.doesNotMatch(JSON.stringify(result),/canonical_plan_json|private/)});
test("apply drift fails closed after evidence save",async()=>{const s=setup({apply:async()=>({status:"committed-but-drifted"})});await assert.rejects(open("c",s.deps),/outcome unknown; reconcile provision\.json/);assert.deepEqual(s.events,["create","write"])});
test("paired close and tampered artifact fail closed",async()=>{const s=setup();assert.equal((await close("c","provision.json",s.deps)).mode,"closed");assert.deepEqual(s.events,["create","write","apply"]);await assert.rejects(close("c","x",setup({readArtifact:()=>{throw Error("saved artifact changed")}}).deps),/saved artifact changed/)});
test("close preserves the saved provision artifact version and target",async()=>{let compiled;const legacyTarget={legacy:true},prior=artifact({schemaVersion:1,target:legacyTarget,phase:"provision",approval:{grantIds:ids.slice(2,8)}}),s=setup({readArtifact:()=>prior,compile:input=>{compiled=input;return artifact(input)}});await close("c","provision.json",s.deps);assert.equal(compiled.schemaVersion,1);assert.equal(compiled.target,legacyTarget);assert.equal(compiled.provisionArtifact,prior)});
test("real helpers round-trip through real reader",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"v184-window-"));try{const s=setup();real(s);s.deps.root=root;const opened=await open("c",s.deps);assert.match(opened.artifactPath,/\.backups[\\/]staging-native-authority[\\/].+[\\/]provision\.json$/);assert.equal((await reconcile("c",opened.artifactPath,{...s.deps,reconcile:async()=>({status:"committed"})})).status,"committed");const c=setup();real(c);c.deps.root=root;assert.match((await close("c",opened.artifactPath,c.deps)).artifactPath,/revoke-recovery-.+\.json$/)}finally{fs.rmSync(root,{recursive:true,force:true})}});
test("real reader rejects nested paths",async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"v184-path-"));try{const s=setup();real(s);s.deps.root=root;const opened=await open("c",s.deps),nested=path.join(path.dirname(opened.artifactPath),"nested");fs.mkdirSync(nested);fs.copyFileSync(opened.artifactPath,path.join(nested,"provision.json"));await assert.rejects(reconcile("c",path.join(nested,"provision.json"),s.deps),/exact private authority path/)}finally{fs.rmSync(root,{recursive:true,force:true})}});
test("real reader rejects UUID directory symlink",async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),"v184-link-")),outside=fs.mkdtempSync(path.join(os.tmpdir(),"v184-out-"));try{const s=setup();real(s);s.deps.root=root;const opened=await open("c",s.deps),link=path.join(path.dirname(path.dirname(opened.artifactPath)),ids[19]);fs.copyFileSync(opened.artifactPath,path.join(outside,"provision.json"));try{fs.symlinkSync(outside,link,"junction")}catch(error){if(["EPERM","EACCES","UNKNOWN"].includes(error.code)){t.skip(`symlink unavailable: ${error.code}`);return}throw error}await assert.rejects(reconcile("c",path.join(link,"provision.json"),s.deps),/non-symlink/)}finally{fs.rmSync(root,{recursive:true,force:true});fs.rmSync(outside,{recursive:true,force:true})}});
test("reconcile bounds success and rejects drift or unknown",async()=>{for(const status of["committed","not-committed"]){const s=setup({reconcile:async()=>({status,receipt:{canonical_plan_json:"private"}})}),result=await reconcile("c","a",s.deps);assert.equal(result.status,status);assert.doesNotMatch(JSON.stringify(result),/canonical_plan_json|private/)}for(const status of["committed-but-drifted","unknown"])await assert.rejects(reconcile("c","a",setup({reconcile:async()=>({status})}).deps),new RegExp(status))});
