import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import {createRequire} from "node:module";
import {fileURLToPath} from "node:url";
import {applyRelationshipRecoveryAuthorityV184,compileRelationshipRecoveryAuthorityV184,RELATIONSHIP_RECOVERY_AUTHORITY_TARGET_V2 as target} from "./staging-relationship-generation-recovery-authority-v184.mjs";
import {STAGING_TARGET} from "./staging-onboarding-native-only-authority-packet.mjs";
import {validateClosedRelationshipRecoveryLineageV184,compileProjectOrganizationAuthorityV184,PROJECT_ORGANIZATION_AUTHORITY_V184_PURPOSE as projectPurpose,PROJECT_ORGANIZATION_AUTHORITY_V184_TARGET as projectTarget} from "./staging-project-organization-authority-v184.mjs";
import {applyProjectOrganizationAuthorityV184,reconcileProjectOrganizationAuthorityV184} from "./staging-project-organization-authority-v184-apply.mjs";

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),".."),requireOperations=createRequire(path.join(root,"apps/operations/package.json"));
const {Miniflare}=requireOperations("miniflare"),{unstable_splitSqlQuery}=requireOperations("wrangler"),migrationDir=path.join(root,"apps/operations/migrations");
const migrationNames=fs.readdirSync(migrationDir).filter(name=>/^\d{4}_.+\.sql$/.test(name)).sort();
const all=async(db,sql,...params)=>(await db.prepare(sql).bind(...params).all()).results;
const first=(db,sql,...params)=>db.prepare(sql).bind(...params).first();
const uuid=n=>`70000000-0000-4000-8000-${String(n).padStart(12,"0")}`;

/** Intentionally duplicated from the reviewed recovery full-schema test. Keep
 * its exceptional migration ordering in sync; do not replace this with source
 * rewriting/evaluation or mutate the existing test module. */
async function migrate(db){
 await db.prepare("PRAGMA foreign_keys=OFF").run();
 await db.prepare("CREATE TABLE d1_migrations(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();
 for(const name of migrationNames){
  const statements=unstable_splitSqlQuery(fs.readFileSync(path.join(migrationDir,name),"utf8").replace(/\r\n/g,"\n")).map(sql=>sql.trim()).filter(sql=>sql&&!/^PRAGMA\s+foreign_keys\s*=\s*ON/i.test(sql));
  if(name.startsWith("0058_")){
   const guardAt=statements.findIndex(sql=>/^CREATE\s+TRIGGER\s+native_directory_enrollments_create_guard/i.test(sql));
   await db.batch(statements.slice(0,guardAt).map(sql=>db.prepare(sql)));
   await db.batch([
    db.prepare("INSERT INTO native_directory_create_admissions(id,staff_id,bound_access_subject,record_id,record_kind,scopes_json,profile_json,destinations_json,active,issued_by) VALUES('fixture-client',?,'access|owner',?,'client',json_array(json_object('businessAreaId',?,'divisionId',NULL)),json_object('name','Client'),json_array(json_object('sourceId',?,'sourceInstanceUUID',?,'applicationUUID',?,'origin','https://pa-staging.ledgetoptechnologies.com','externalCanonicalId',?)),0,?)").bind(target.staffId,target.clientRecordId,target.clientBusinessAreaId,target.sourceId,uuid(101),uuid(102),target.clientRecordId,target.staffId),
    db.prepare("INSERT INTO native_directory_create_admissions(id,staff_id,bound_access_subject,record_id,record_kind,scopes_json,profile_json,destinations_json,active,issued_by) VALUES('fixture-org',?,'access|owner',?,'organization',json_array(json_object('businessAreaId',?,'divisionId',NULL)),json_object('name','Organization'),json_array(json_object('sourceId',?,'sourceInstanceUUID',?,'applicationUUID',?,'origin','https://pa-staging.ledgetoptechnologies.com','externalCanonicalId',?)),0,?)").bind(target.staffId,target.organizationRecordId,target.organizationBusinessAreaId,target.sourceId,uuid(101),uuid(102),target.organizationRecordId,target.staffId),
    db.prepare("INSERT INTO native_directory_enrollments(record_id,destinations_json,create_admission_id) VALUES(?,json_array(json_object('sourceId',?,'sourceInstanceUUID',?,'applicationUUID',?,'historyEpoch',?,'origin',?,'externalCanonicalId',?)),'fixture-client')").bind(target.clientRecordId,target.sourceId,target.sourceInstanceId,target.applicationId,target.historyEpochId,target.destinationOrigin,target.clientRecordId),
    db.prepare("INSERT INTO native_directory_enrollments(record_id,destinations_json,create_admission_id) VALUES(?,json_array(json_object('sourceId',?,'sourceInstanceUUID',?,'applicationUUID',?,'historyEpoch',?,'origin',?,'externalCanonicalId',?)),'fixture-org')").bind(target.organizationRecordId,target.sourceId,target.sourceInstanceId,target.applicationId,target.historyEpochId,target.destinationOrigin,target.organizationRecordId),
    db.prepare("INSERT INTO operations_directory_revisions(record_id,version,mutation_id,profile_json) VALUES(?,2,'fixture-client-current-revision',json_object('name','Client'))").bind(target.clientRecordId),
    db.prepare("INSERT INTO operations_directory_revisions(record_id,version,mutation_id,profile_json) VALUES(?,1,'fixture-organization-current-revision',json_object('name','Organization'))").bind(target.organizationRecordId),
    db.prepare("INSERT INTO operations_directory_intents(intent_id,mutation_id,record_id,record_version,source_id,source_instance_uuid,application_uuid,destination_origin,external_canonical_id,desired_payload_json,state) VALUES('fixture-client-intent','fixture-client-current-revision',?,2,?,?,?,?,?,json_object('name','Client'),'acknowledged')").bind(target.clientRecordId,target.sourceId,target.sourceInstanceId,target.applicationId,target.destinationOrigin,target.clientRecordId)]);
   await db.batch([...statements.slice(guardAt).map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
  }else if(name.startsWith("0065_")){
   await db.batch(statements.slice(0,4).map(sql=>db.prepare(sql)));
   const clientCommand=JSON.stringify({commandId:"fixture-client-evidence",operation:"update",resourceType:"client",externalId:target.clientRecordId,expectedProjectAlphaPublicId:target.clientPublicId,expectedRevision:"7",expectedAuthorizationGeneration:target.predecessorAuthorizationGeneration,fields:{name:"Client"}}),clientOutcome=JSON.stringify({status:"acknowledged",response:{sourceInstanceId:target.sourceInstanceId,applicationId:target.applicationId,historyEpoch:target.historyEpochId,requestId:uuid(104),replayed:false,result:{resource:{type:"client",publicId:target.clientPublicId,revision:"7"},data:{publicId:target.clientPublicId},authorizationGeneration:target.predecessorAuthorizationGeneration}}}),organizationOutcome=JSON.stringify({status:"acknowledged",response:{result:{authorizationGeneration:target.predecessorAuthorizationGeneration}}});
   await db.batch([
    db.prepare("UPDATE operations_directory_intents SET expected_history_epoch_id=? WHERE intent_id='fixture-client-intent'").bind(target.historyEpochId),
    db.prepare("INSERT INTO project_alpha_directory_outbox(command_id,source_id,application_id,resource_type,external_id,command_json,destination_base_url,expected_source_instance_id,origin_snapshot_json,state,next_attempt_at,outcome_json,expected_history_epoch_id) VALUES('fixture-client-evidence',?,?,'client',?,?,?,?,json_object('fixture',1),'acknowledged',0,?,?)").bind(target.sourceId,target.applicationId,target.clientRecordId,clientCommand,target.destinationOrigin,target.sourceInstanceId,clientOutcome,target.historyEpochId),
    db.prepare("INSERT INTO project_alpha_directory_outbox(command_id,source_id,application_id,resource_type,external_id,command_json,destination_base_url,expected_source_instance_id,origin_snapshot_json,state,next_attempt_at,outcome_json,expected_history_epoch_id) VALUES('fixture-organization-evidence',?,?,'organization',?,json_object('operation','update'),?,?,json_object('fixture',1),'acknowledged',0,?,?)").bind(target.sourceId,target.applicationId,target.organizationRecordId,target.destinationOrigin,target.sourceInstanceId,organizationOutcome,target.historyEpochId),
    db.prepare("INSERT INTO project_alpha_directory_mappings(source_id,resource_type,external_id,project_alpha_public_id,source_instance_id,application_id,command_id,history_epoch_id) VALUES(?,'client',?,?,?,?, 'fixture-client-evidence',?)").bind(target.sourceId,target.clientRecordId,target.clientPublicId,target.sourceInstanceId,target.applicationId,target.historyEpochId),
    db.prepare("INSERT INTO project_alpha_directory_mappings(source_id,resource_type,external_id,project_alpha_public_id,source_instance_id,application_id,command_id,history_epoch_id) VALUES(?,'organization',?,?,?,?, 'fixture-organization-evidence',?)").bind(target.sourceId,target.organizationRecordId,target.organizationPublicId,target.sourceInstanceId,target.applicationId,target.historyEpochId)]);
   const dropReserveAt=statements.findIndex(sql=>/^DROP\s+TRIGGER\s+operations_directory_materializations_reserve/i.test(sql));
   await db.batch(statements.slice(4,dropReserveAt+1).map(sql=>db.prepare(sql)));
   await db.prepare("INSERT INTO operations_directory_materializations(intent_id,command_id,command_json,origin_snapshot_json,disposition_json,next_attempt_at,history_epoch_id) VALUES('fixture-client-intent','fixture-client-evidence',?,json_object('fixture',1),json_object('fixture',1),0,?)").bind(clientCommand,target.historyEpochId).run();
   await db.batch([...statements.slice(dropReserveAt+1).map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
  }else if(name.startsWith("0081_")){
   const guardAt=statements.findIndex(sql=>/^CREATE\s+TRIGGER\s+operations_directory_client_organization_history_insert_guard/i.test(sql));
   await db.batch(statements.slice(0,guardAt).map(sql=>db.prepare(sql)));
   await db.prepare("INSERT INTO operations_directory_client_organization_history(client_record_id,relationship_version,mutation_id,previous_organization_record_id,organization_record_id,client_record_version,organization_record_version,actor_staff_id,actor_access_subject,actor_email,actor_admission_version,actor_profile_version) VALUES(?,2,'fixture-mutation',NULL,?,2,1,?,'access|owner','owner@example.test',1,1)").bind(target.clientRecordId,target.organizationRecordId,target.staffId).run();
   await db.batch([...statements.slice(guardAt).map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
  }else if(name.startsWith("0133_")){
   const guardAt=statements.findIndex(sql=>/^CREATE\s+TRIGGER\s+project_alpha_directory_relationship_outbox_insert_guard/i.test(sql));
   await db.batch(statements.slice(0,guardAt).map(sql=>db.prepare(sql)));
   const command=JSON.stringify({commandId:target.predecessorCommandId,expectedClientRevision:"7",expectedAuthorizationGeneration:target.predecessorAuthorizationGeneration,expectedCurrentOrganizationPublicId:null,organization:{externalId:target.organizationRecordId,publicId:target.organizationPublicId,expectedRevision:"9"}});
   await db.prepare("INSERT INTO project_alpha_directory_relationship_outbox(command_id,mutation_id,client_record_id,relationship_version,action,source_id,source_instance_id,application_id,history_epoch_id,destination_origin,client_public_id,expected_client_revision,expected_authorization_generation,expected_current_organization_record_id,expected_current_organization_public_id,organization_record_id,organization_public_id,expected_organization_revision,command_json,request_json,state,next_attempt_at,outcome_json,created_at,updated_at) VALUES(?,'fixture-mutation',?,2,'assign',?,?,?,?, 'https://pa-staging.ledgetoptechnologies.com',?,'7',?,NULL,NULL,?,?,'9',?,json_object('body',1),'terminal',0,json_object('httpStatus',409),'2026-10-10T12:00:00.000Z','2026-10-10T12:00:00.000Z')").bind(target.predecessorCommandId,target.clientRecordId,target.sourceId,target.sourceInstanceId,target.applicationId,target.historyEpochId,target.clientPublicId,target.predecessorAuthorizationGeneration,target.organizationRecordId,target.organizationPublicId,command).run();
   await db.batch([...statements.slice(guardAt).map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
  }else if(name.startsWith("0135_")){
   const copyAt=statements.findIndex(sql=>/^INSERT INTO operations_directory_client_organizations_next/i.test(sql));
   await db.batch(statements.slice(0,copyAt).map(sql=>db.prepare(sql)));
   await db.prepare("INSERT INTO operations_directory_client_organizations_next(client_record_id,organization_record_id,relationship_version) VALUES(?,?,2)").bind(target.clientRecordId,target.organizationRecordId).run();
   await db.batch([...statements.slice(copyAt).map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
  }else await db.batch([...statements.map(sql=>db.prepare(sql)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);
   if(name.startsWith("0057_"))await db.batch([db.prepare("UPDATE staff_users SET access_subject='access|owner',status='active' WHERE id=?").bind(target.staffId),db.prepare("INSERT INTO native_staff_admissions(staff_id,bound_access_subject,active,admitted_by) VALUES(?,'access|owner',1,?)").bind(target.staffId,target.staffId),db.prepare("INSERT OR IGNORE INTO native_business_areas(id,name,active) VALUES(?,'Drone services staging acceptance',1)").bind(target.organizationBusinessAreaId),db.prepare("INSERT OR IGNORE INTO native_business_areas(id,name,active) VALUES(?,?,1)").bind(target.clientBusinessAreaId,projectTarget.businessAreaName),db.prepare("INSERT INTO operations_directory_records(record_id,record_kind,current_version) VALUES(?,'client',2)").bind(target.clientRecordId),db.prepare("INSERT INTO operations_directory_records(record_id,record_kind,current_version) VALUES(?,'organization',1)").bind(target.organizationRecordId),db.prepare("INSERT INTO native_directory_resource_scopes(record_id,scope_kind,business_area_id,active) VALUES(?,'business_area',?,1)").bind(target.clientRecordId,target.clientBusinessAreaId),db.prepare("INSERT INTO native_directory_resource_scopes(record_id,scope_kind,business_area_id,active) VALUES(?,'business_area',?,1)").bind(target.organizationRecordId,target.organizationBusinessAreaId)]);
  if(name.startsWith("0059_"))await db.prepare("INSERT INTO native_staff_profiles(staff_id,login_email,display_name) VALUES(?,'owner@example.test','Owner')").bind(target.staffId).run();
 }
 await db.prepare("PRAGMA foreign_keys=ON").run();
}

async function seed(db){const t="2026-10-10T12:00:00.000Z",grantIds=[uuid(2),uuid(3),uuid(4),uuid(5),uuid(6),uuid(7)],grants=[{id:uuid(1),permission:"directory.profile.view",record:null,active:1,scope:"global"},{id:grantIds[3],permission:"directory.profile.edit",record:target.organizationRecordId,active:0,scope:"resource"},{id:grantIds[4],permission:"directory.identity.link",record:target.organizationRecordId,active:0,scope:"resource"}];for(const grant of grants)await db.prepare("INSERT INTO native_directory_grants(id,staff_id,permission,effect,scope_kind,resource_id,active,granted_by,created_at) VALUES(?, ?,?,'allow',?,?,?, ?,?)").bind(grant.id,target.staffId,grant.permission,grant.scope,grant.record,grant.active,target.staffId,t).run();return grantIds}
async function input(db,phase,grantIds,provisionArtifact){const stamp=(await first(db,"SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now') stamp")).stamp;return{schemaVersion:2,staging:STAGING_TARGET,phase,target,migrationNames,staff:await first(db,"SELECT id,status,access_subject FROM staff_users WHERE id=?",target.staffId),roles:await all(db,"SELECT id,staff_id,role_id,scope,scope_key FROM staff_role_assignments WHERE staff_id=? ORDER BY id",target.staffId),admission:await first(db,"SELECT * FROM native_staff_admissions WHERE staff_id=?",target.staffId),profile:await first(db,"SELECT * FROM native_staff_profiles WHERE staff_id=?",target.staffId),generation:await first(db,"SELECT * FROM native_directory_grant_generations WHERE staff_id=?",target.staffId),records:await all(db,"SELECT record_id,record_kind,current_version FROM operations_directory_records WHERE record_id IN (?,?) ORDER BY CASE record_kind WHEN 'client' THEN 0 ELSE 1 END",target.clientRecordId,target.organizationRecordId),resourceScopes:await all(db,"SELECT record_id,scope_kind,business_area_id,division_id,active FROM native_directory_resource_scopes WHERE record_id IN (?,?) ORDER BY CASE record_id WHEN ? THEN 0 ELSE 1 END",target.clientRecordId,target.organizationRecordId,target.clientRecordId),relationship:await first(db,"SELECT client_record_id,organization_record_id,relationship_version FROM operations_directory_client_organizations WHERE client_record_id=?",target.clientRecordId),predecessor:await first(db,"SELECT command_id,source_id,source_instance_id,application_id,history_epoch_id,destination_origin,client_record_id,client_public_id,relationship_version,action,organization_record_id,organization_public_id,command_json,state,outcome_json FROM project_alpha_directory_relationship_outbox WHERE command_id=?",target.predecessorCommandId),grants:await all(db,"SELECT * FROM native_directory_grants WHERE staff_id=? ORDER BY id",target.staffId),history:await all(db,"SELECT * FROM native_directory_grant_history WHERE staff_id=? ORDER BY grant_generation",target.staffId),approval:{approvalId:crypto.randomUUID(),commandId:crypto.randomUUID(),grantIds,issuedAt:stamp,expiresAt:new Date(Date.parse(stamp)+3600000).toISOString(),executedAt:stamp},...(provisionArtifact?{provisionArtifact}:{})}}

const APPROVAL_COLUMNS="approval_id,canonical_plan_json,canonical_plan_sha256,approved_operator_staff_id,approved_operator_access_subject,independent_binding_verification_json,independent_binding_verification_sha256,issued_by_staff_id,issued_by_access_subject,issued_at,expires_at,revoked_at";
const RECEIPT_COLUMNS="command_id,approval_id,operator_staff_id,operator_access_subject,canonical_plan_json,canonical_plan_sha256,independent_binding_verification_json,independent_binding_verification_sha256,result_json,result_sha256,executed_at";

async function captured(db,provisionArtifact,revokeArtifact){
 return {provisionArtifact,revokeArtifact,
  approvals:await all(db,`SELECT ${APPROVAL_COLUMNS} FROM native_staff_bootstrap_approvals WHERE approval_id IN (?,?) ORDER BY approval_id`,provisionArtifact.approval.approval_id,revokeArtifact.approval.approval_id),
  receipts:await all(db,`SELECT ${RECEIPT_COLUMNS} FROM native_staff_bootstrap_receipts WHERE command_id IN (?,?) ORDER BY command_id`,provisionArtifact.receipt.command_id,revokeArtifact.receipt.command_id),
  directoryGrants:await all(db,"SELECT * FROM native_directory_grants WHERE staff_id=? ORDER BY id",target.staffId),
  directoryGrantHistory:await all(db,"SELECT * FROM native_directory_grant_history WHERE staff_id=? ORDER BY grant_generation",target.staffId),
  directoryGrantGeneration:await first(db,"SELECT * FROM native_directory_grant_generations WHERE staff_id=?",target.staffId)};
}
async function applyStatements(db,artifact){return db.batch(artifact.statements.map(s=>db.prepare(s.sql).bind(...s.params)))}
async function projectInput(db,recoveryLineage){const now=(await first(db,"SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now') stamp")).stamp,issued=new Date(Date.parse(now)-60000).toISOString();return{schemaVersion:1,purpose:projectPurpose,staging:STAGING_TARGET,migrationNames:[...migrationNames],target:projectTarget,staff:await first(db,"SELECT id,status,access_subject FROM staff_users WHERE id=?",projectTarget.staffId),roles:await all(db,"SELECT id,staff_id,role_id,scope,division_id,scope_key,created_by,created_at FROM staff_role_assignments WHERE staff_id=? ORDER BY id",projectTarget.staffId),admission:await first(db,"SELECT * FROM native_staff_admissions WHERE staff_id=?",projectTarget.staffId),profile:await first(db,"SELECT * FROM native_staff_profiles WHERE staff_id=?",projectTarget.staffId),businessArea:await first(db,"SELECT id,name,active FROM native_business_areas WHERE id=?",projectTarget.businessAreaId),projectGeneration:await first(db,"SELECT staff_id,generation FROM native_project_grant_generations WHERE staff_id=?",projectTarget.staffId),projectGrants:await all(db,"SELECT * FROM native_project_grants WHERE staff_id=? ORDER BY id",projectTarget.staffId),recoveryLineage,approval:{provisionApprovalId:crypto.randomUUID(),provisionCommandId:crypto.randomUUID(),revokeApprovalId:crypto.randomUUID(),revokeCommandId:crypto.randomUUID(),grantId:crypto.randomUUID(),issuedAt:issued,expiresAt:new Date(Date.parse(now)+3600000).toISOString()}}}
async function authoritySnapshot(db){return{grants:await all(db,"SELECT * FROM native_project_grants WHERE staff_id=? ORDER BY id",projectTarget.staffId),generation:await first(db,"SELECT * FROM native_project_grant_generations WHERE staff_id=?",projectTarget.staffId),directoryGrants:await all(db,"SELECT * FROM native_directory_grants WHERE staff_id=? ORDER BY id",projectTarget.staffId),directoryGeneration:await first(db,"SELECT * FROM native_directory_grant_generations WHERE staff_id=?",projectTarget.staffId),directoryHistory:await all(db,"SELECT * FROM native_directory_grant_history WHERE staff_id=? ORDER BY grant_generation",projectTarget.staffId),approvals:await all(db,"SELECT * FROM native_staff_bootstrap_approvals WHERE approved_operator_staff_id=? ORDER BY approval_id",projectTarget.staffId),receipts:await all(db,"SELECT * FROM native_staff_bootstrap_receipts WHERE operator_staff_id=? ORDER BY command_id",projectTarget.staffId)}}
async function preservedAuthoritySnapshot(db,selectedGrantId=null){return{directoryGrants:await all(db,"SELECT * FROM native_directory_grants WHERE staff_id=? ORDER BY id",projectTarget.staffId),directoryGeneration:await first(db,"SELECT * FROM native_directory_grant_generations WHERE staff_id=?",projectTarget.staffId),directoryHistory:await all(db,"SELECT * FROM native_directory_grant_history WHERE staff_id=? ORDER BY grant_generation",projectTarget.staffId),unrelatedProjectGrants:await all(db,"SELECT * FROM native_project_grants WHERE staff_id=? AND (? IS NULL OR id<>?) ORDER BY id",projectTarget.staffId,selectedGrantId,selectedGrantId),roles:await all(db,"SELECT * FROM staff_role_assignments WHERE staff_id=? ORDER BY id",projectTarget.staffId),admission:await first(db,"SELECT * FROM native_staff_admissions WHERE staff_id=?",projectTarget.staffId),profile:await first(db,"SELECT * FROM native_staff_profiles WHERE staff_id=?",projectTarget.staffId)}}
async function seedSecondaryRelationshipActor(db){const staffId="staff-project-queue-fixture",subject="access|project-queue-fixture",email="project-queue-fixture@example.test";await db.batch([db.prepare("INSERT INTO staff_users(id,email,display_name,access_subject,status) VALUES(?,?,?,?,'active')").bind(staffId,email,"Project queue fixture",subject),db.prepare("INSERT INTO staff_role_assignments(id,staff_id,role_id,scope,scope_key,created_by) VALUES(?,?, 'role-admin','global','global',?)").bind(uuid(401),staffId,projectTarget.staffId),db.prepare("INSERT INTO native_staff_admissions(staff_id,bound_access_subject,active,admitted_by) VALUES(?,?,1,?)").bind(staffId,subject,projectTarget.staffId),db.prepare("INSERT INTO native_staff_profiles(staff_id,login_email,display_name) VALUES(?,?,?)").bind(staffId,email,"Project queue fixture")]);let n=410;for(const recordId of[target.clientRecordId,target.organizationRecordId])for(const permission of["directory.profile.view","directory.profile.edit","directory.identity.link","directory.enrollment.manage"]){await db.prepare("INSERT INTO native_directory_grants(id,staff_id,permission,effect,scope_kind,resource_id,active,granted_by) VALUES(?,?,?,'allow','resource',?,1,?)").bind(uuid(n++),staffId,permission,recordId,projectTarget.staffId).run()}return{staffId,subject,email,admission:await first(db,"SELECT * FROM native_staff_admissions WHERE staff_id=?",staffId),profile:await first(db,"SELECT * FROM native_staff_profiles WHERE staff_id=?",staffId)} }
function freshPendingRelationship(db,actor){const mutationId=crypto.randomUUID(),commandId=crypto.randomUUID(),verifiedUntil=new Date(Date.now()+60000).toISOString(),pendingCommand=JSON.stringify({commandId,expectedClientRevision:"7",expectedAuthorizationGeneration:target.predecessorAuthorizationGeneration,expectedCurrentOrganizationPublicId:target.organizationPublicId,organization:null});return{mutationId,commandId,statements:[db.prepare("INSERT INTO operations_directory_relationship_write_fences(mutation_id,client_record_id,expected_relationship_version,previous_organization_record_id,organization_record_id,client_record_version,previous_organization_record_version,organization_record_version,actor_staff_id,actor_access_subject,actor_email,actor_admission_version,actor_profile_version,verified_until) VALUES(?,?,2,?,NULL,2,1,NULL,?,?,?,?,?,?)").bind(mutationId,target.clientRecordId,target.organizationRecordId,actor.staffId,actor.subject,actor.email,actor.admission.version,actor.profile.version,verifiedUntil),db.prepare("UPDATE operations_directory_client_organizations SET organization_record_id=NULL,relationship_version=3,updated_at=strftime('%Y-%m-%dT%H:%M:%fZ','now') WHERE client_record_id=? AND relationship_version=2 AND organization_record_id=?").bind(target.clientRecordId,target.organizationRecordId),db.prepare("INSERT INTO project_alpha_directory_relationship_outbox(command_id,mutation_id,client_record_id,relationship_version,action,source_id,source_instance_id,application_id,history_epoch_id,destination_origin,client_public_id,expected_client_revision,expected_authorization_generation,expected_current_organization_record_id,expected_current_organization_public_id,organization_record_id,organization_public_id,expected_organization_revision,supersedes_terminal_command_id,command_json,request_json,next_attempt_at) VALUES(?,?,?,3,'remove',?,?,?,?,?,?, '7',?,?,?,NULL,NULL,NULL,?,?,json_object('body',1),?)").bind(commandId,mutationId,target.clientRecordId,target.sourceId,target.sourceInstanceId,target.applicationId,target.historyEpochId,target.destinationOrigin,target.clientPublicId,target.predecessorAuthorizationGeneration,target.organizationRecordId,target.organizationPublicId,target.predecessorCommandId,pendingCommand,Date.now()),db.prepare("DELETE FROM operations_directory_relationship_write_fences WHERE mutation_id=?").bind(mutationId)]}}

test("closed recovery lineage validates from actual 0001-0184 D1 trigger state",{timeout:240000},async()=>{
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:`project-v184-lineage-${crypto.randomUUID()}`}});
 try{
  const db=await mf.getD1Database("DB");await migrate(db);
  assert.deepEqual((await all(db,"SELECT name FROM d1_migrations ORDER BY name")).map(row=>row.name),migrationNames);
  const grantIds=await seed(db),provisionArtifact=compileRelationshipRecoveryAuthorityV184(await input(db,"provision",grantIds));
  await applyRelationshipRecoveryAuthorityV184(db,provisionArtifact,{target:STAGING_TARGET,root});
  const revokeArtifact=compileRelationshipRecoveryAuthorityV184(await input(db,"revoke",grantIds,provisionArtifact));
  await applyRelationshipRecoveryAuthorityV184(db,revokeArtifact,{target:STAGING_TARGET,root});
  const actual=await captured(db,provisionArtifact,revokeArtifact),validated=validateClosedRelationshipRecoveryLineageV184(actual,{root});
  assert.deepEqual(validated.grantIds,grantIds);assert.equal(validated.generation,actual.directoryGrantGeneration.generation);

  const wrongReceipt=structuredClone(actual);wrongReceipt.receipts[0].result_sha256="0".repeat(64);
  assert.throws(()=>validateClosedRelationshipRecoveryLineageV184(wrongReceipt,{root}),/receipts/);
  const activeGrant=structuredClone(actual);activeGrant.directoryGrants.find(row=>grantIds.includes(row.id)).active=1;
  assert.throws(()=>validateClosedRelationshipRecoveryLineageV184(activeGrant,{root}),/grants/);
  const historyDrift=structuredClone(actual);historyDrift.directoryGrantHistory.at(-1).permission="directory.profile.view";
  assert.throws(()=>validateClosedRelationshipRecoveryLineageV184(historyDrift,{root}),/history successor/);
 }finally{await mf.dispose()}
});

test("organization Project authority provisions and sealed cleanup execute atomically on actual 0001-0184 D1",{timeout:240000},async()=>{
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:`project-organization-v184-authority-${crypto.randomUUID()}`}});
 try{
  const db=await mf.getD1Database("DB");await migrate(db);const recoveryIds=await seed(db),recoveryProvision=compileRelationshipRecoveryAuthorityV184(await input(db,"provision",recoveryIds));await applyRelationshipRecoveryAuthorityV184(db,recoveryProvision,{target:STAGING_TARGET,root});const recoveryRevoke=compileRelationshipRecoveryAuthorityV184(await input(db,"revoke",recoveryIds,recoveryProvision));await applyRelationshipRecoveryAuthorityV184(db,recoveryRevoke,{target:STAGING_TARGET,root});const lineage=await captured(db,recoveryProvision,recoveryRevoke);validateClosedRelationshipRecoveryLineageV184(lineage,{root});
  await db.batch([db.prepare("INSERT OR IGNORE INTO native_business_areas(id,name,active) VALUES(?,?,1)").bind(projectTarget.businessAreaId,projectTarget.businessAreaName),db.prepare("INSERT INTO native_project_grants(id,staff_id,capability,effect,scope_kind,active,granted_by) VALUES(?,?,'project.shared.sync','allow','global',0,?)").bind(uuid(300),projectTarget.staffId,projectTarget.staffId)]);

  let value=await projectInput(db,lineage),compiled=compileProjectOrganizationAuthorityV184(value,{root}),before;
  await db.prepare("UPDATE staff_users SET status='inactive' WHERE id=?").bind(projectTarget.staffId).run();before=await authoritySnapshot(db);await assert.rejects(applyStatements(db,compiled.provision));assert.deepEqual(await authoritySnapshot(db),before);await db.prepare("UPDATE staff_users SET status='active' WHERE id=?").bind(projectTarget.staffId).run();
  value=await projectInput(db,lineage);compiled=compileProjectOrganizationAuthorityV184(value,{root});await db.prepare("UPDATE native_project_grants SET active=1,version=version+1 WHERE id=?").bind(uuid(300)).run();before=await authoritySnapshot(db);await assert.rejects(applyStatements(db,compiled.provision));assert.deepEqual(await authoritySnapshot(db),before);await db.prepare("UPDATE native_project_grants SET active=0,version=version+1 WHERE id=?").bind(uuid(300)).run();
  value=await projectInput(db,lineage);compiled=compileProjectOrganizationAuthorityV184(value,{root});before=await authoritySnapshot(db);await assert.rejects(db.batch([db.prepare("UPDATE native_directory_grants SET active=1 WHERE id=?").bind(recoveryIds[0]),...compiled.provision.statements.map(s=>db.prepare(s.sql).bind(...s.params))]));assert.deepEqual(await authoritySnapshot(db),before);
  value=await projectInput(db,lineage);compiled=compileProjectOrganizationAuthorityV184(value,{root});before=await authoritySnapshot(db);const unrelated=crypto.randomUUID(),insertUnrelated=db.prepare(`INSERT INTO native_staff_bootstrap_approvals(${APPROVAL_COLUMNS}) SELECT ?,canonical_plan_json,canonical_plan_sha256,approved_operator_staff_id,approved_operator_access_subject,independent_binding_verification_json,independent_binding_verification_sha256,issued_by_staff_id,issued_by_access_subject,issued_at,expires_at,NULL FROM native_staff_bootstrap_approvals WHERE approval_id=?`).bind(unrelated,recoveryRevoke.approval.approval_id);await assert.rejects(db.batch([insertUnrelated,...compiled.provision.statements.map(s=>db.prepare(s.sql).bind(...s.params))]));assert.deepEqual(await authoritySnapshot(db),before);

  value=await projectInput(db,lineage);compiled=compileProjectOrganizationAuthorityV184(value,{root});const preservedBefore=await preservedAuthoritySnapshot(db),applied=await applyProjectOrganizationAuthorityV184(db,compiled,"provision",{target:STAGING_TARGET,root});assert.equal(applied.replayed,false);assert.equal((await applyProjectOrganizationAuthorityV184(db,compiled,"provision",{target:STAGING_TARGET,root})).replayed,true);assert.equal((await reconcileProjectOrganizationAuthorityV184(db,compiled,"provision",{target:STAGING_TARGET,root})).status,"settled");await assert.rejects(applyProjectOrganizationAuthorityV184(db,compiled,"revoke",{target:STAGING_TARGET,root}),/sealed/);const altered=structuredClone(compiled);altered.planHash="0".repeat(64);await assert.rejects(applyProjectOrganizationAuthorityV184(db,altered,"provision",{target:STAGING_TARGET,root}),/altered/);await assert.rejects(applyProjectOrganizationAuthorityV184(db,compiled,"provision",{target:{...STAGING_TARGET,databaseId:"wrong"},root}),/staging binding/);const provisionApproval=await first(db,`SELECT ${APPROVAL_COLUMNS} FROM native_staff_bootstrap_approvals WHERE approval_id=?`,value.approval.provisionApprovalId),provisionReceipt=await first(db,`SELECT ${RECEIPT_COLUMNS} FROM native_staff_bootstrap_receipts WHERE command_id=?`,value.approval.provisionCommandId),provisionGrant=await first(db,"SELECT * FROM native_project_grants WHERE id=?",value.approval.grantId);assert.equal(provisionGrant.active,1);assert.equal(provisionGrant.version,1);assert.notEqual(provisionReceipt.executed_at,value.approval.issuedAt);
  const sealed=compileProjectOrganizationAuthorityV184({...value,provisionReadback:{approval:provisionApproval,receipt:provisionReceipt,grant:provisionGrant}},{root});assert.equal(sealed.provision.statements,undefined);await assert.rejects(applyProjectOrganizationAuthorityV184(db,sealed,"provision",{target:STAGING_TARGET,root}),/sealed/);const revoked=await applyProjectOrganizationAuthorityV184(db,sealed,"revoke",{target:STAGING_TARGET,root});assert.equal(revoked.replayed,false);assert.equal((await applyProjectOrganizationAuthorityV184(db,sealed,"revoke",{target:STAGING_TARGET,root})).replayed,true);assert.equal((await reconcileProjectOrganizationAuthorityV184(db,sealed,"revoke",{target:STAGING_TARGET,root})).status,"settled");const closedGrant=await first(db,"SELECT * FROM native_project_grants WHERE id=?",value.approval.grantId),closedApproval=await first(db,"SELECT * FROM native_staff_bootstrap_approvals WHERE approval_id=?",value.approval.provisionApprovalId),revokeReceipt=await first(db,"SELECT * FROM native_staff_bootstrap_receipts WHERE command_id=?",value.approval.revokeCommandId);assert.equal(closedGrant.active,0);assert.equal(closedGrant.version,2);assert.ok(closedApproval.revoked_at);assert.equal(revokeReceipt.approval_id,value.approval.revokeApprovalId);assert.equal((await first(db,"SELECT generation FROM native_project_grant_generations WHERE staff_id=?",projectTarget.staffId)).generation,value.projectGeneration.generation+2);assert.deepEqual(await preservedAuthoritySnapshot(db,value.approval.grantId),preservedBefore);
 }finally{await mf.dispose()}
});

test("organization Project authority rejects valid unrelated pending relationship work atomically",{timeout:240000},async()=>{
 const mf=new Miniflare({modules:true,script:"export default {fetch(){return new Response('ok')}}",d1Databases:{DB:`project-organization-v184-queue-${crypto.randomUUID()}`}});
 try{
  const db=await mf.getD1Database("DB");await migrate(db);const recoveryIds=await seed(db),recoveryProvision=compileRelationshipRecoveryAuthorityV184(await input(db,"provision",recoveryIds));await applyRelationshipRecoveryAuthorityV184(db,recoveryProvision,{target:STAGING_TARGET,root});const recoveryRevoke=compileRelationshipRecoveryAuthorityV184(await input(db,"revoke",recoveryIds,recoveryProvision));await applyRelationshipRecoveryAuthorityV184(db,recoveryRevoke,{target:STAGING_TARGET,root});const lineage=await captured(db,recoveryProvision,recoveryRevoke);validateClosedRelationshipRecoveryLineageV184(lineage,{root});
  await db.batch([db.prepare("INSERT OR IGNORE INTO native_business_areas(id,name,active) VALUES(?,?,1)").bind(projectTarget.businessAreaId,projectTarget.businessAreaName),db.prepare("INSERT INTO native_project_grants(id,staff_id,capability,effect,scope_kind,active,granted_by) VALUES(?,?,'project.shared.sync','allow','global',0,?)").bind(uuid(300),projectTarget.staffId,projectTarget.staffId)]);
  const actor=await seedSecondaryRelationshipActor(db),value=await projectInput(db,lineage),compiled=compileProjectOrganizationAuthorityV184(value,{root}),before=await authoritySnapshot(db),relationshipBefore=await first(db,"SELECT * FROM operations_directory_client_organizations WHERE client_record_id=?",target.clientRecordId),predecessorBefore=await first(db,"SELECT * FROM project_alpha_directory_relationship_outbox WHERE command_id=?",target.predecessorCommandId);

  const probe=freshPendingRelationship(db,actor);await assert.rejects(db.batch([...probe.statements,db.prepare("SELECT json('fresh-pending-fixture-probe')")]),/malformed JSON/);assert.deepEqual(await authoritySnapshot(db),before);assert.deepEqual(await first(db,"SELECT * FROM operations_directory_client_organizations WHERE client_record_id=?",target.clientRecordId),relationshipBefore);assert.deepEqual(await first(db,"SELECT * FROM project_alpha_directory_relationship_outbox WHERE command_id=?",target.predecessorCommandId),predecessorBefore);assert.equal(await first(db,"SELECT command_id FROM project_alpha_directory_relationship_outbox WHERE command_id=?",probe.commandId),null);

  const pending=freshPendingRelationship(db,actor);await assert.rejects(db.batch([...pending.statements,...compiled.provision.statements.map(statement=>db.prepare(statement.sql).bind(...statement.params))]),/malformed JSON/);assert.deepEqual(await authoritySnapshot(db),before);assert.deepEqual(await first(db,"SELECT * FROM operations_directory_client_organizations WHERE client_record_id=?",target.clientRecordId),relationshipBefore);assert.deepEqual(await first(db,"SELECT * FROM project_alpha_directory_relationship_outbox WHERE command_id=?",target.predecessorCommandId),predecessorBefore);assert.equal(await first(db,"SELECT command_id FROM project_alpha_directory_relationship_outbox WHERE command_id=?",pending.commandId),null);
 }finally{await mf.dispose()}
});
