import assert from "node:assert/strict";import crypto from "node:crypto";import fs from "node:fs";import os from "node:os";import path from "node:path";import test,{after} from "node:test";import{createRequire}from"node:module";
import{ORGANIZATION_RELATIONSHIP_TARGET as target,compileOrganizationRelationshipAuthority,applyOrganizationRelationshipAuthority}from"./staging-organization-relationship-authority.mjs";import{STAGING_TARGET}from"./staging-onboarding-native-only-authority-packet.mjs";
const root=path.resolve(import.meta.dirname,".."),req=createRequire(path.join(root,"apps/operations/package.json")),{Miniflare}=req("miniflare"),{unstable_splitSqlQuery}=req("wrangler"),{build}=req("esbuild"),dir=path.join(root,"apps/operations/migrations"),migrationNames=fs.readdirSync(dir).filter(n=>/^\d{4}_.+\.sql$/.test(n)&&n.slice(0,4)<="0183").sort();
const reviewedRoot=fs.mkdtempSync(path.join(os.tmpdir(),"organization-authority-fullschema-reviewed-")),reviewedDir=path.join(reviewedRoot,"apps/operations/migrations");fs.mkdirSync(reviewedDir,{recursive:true});for(const name of migrationNames)fs.copyFileSync(path.join(dir,name),path.join(reviewedDir,name));after(()=>fs.rmSync(reviewedRoot,{recursive:true,force:true}));
const all=async(db,sql,...p)=>(await db.prepare(sql).bind(...p).all()).results,first=(db,sql,...p)=>db.prepare(sql).bind(...p).first();
async function migrate(db){await db.prepare("CREATE TABLE d1_migrations(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE NOT NULL,applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)").run();for(const name of migrationNames){const source=fs.readFileSync(path.join(dir,name),"utf8").replace(/\r\n/g,"\n"),sqls=unstable_splitSqlQuery(source).map(s=>s.trim()).filter(s=>s&&!/^PRAGMA\s+foreign_keys\s*=\s*ON/i.test(s));await db.batch([...sqls.map(s=>db.prepare(s)),db.prepare("INSERT INTO d1_migrations(name) VALUES(?)").bind(name)]);}}
let writer;async function loadWriter(){if(writer)return writer;const built=await build({entryPoints:[path.join(root,"apps/operations/src/worker/native-directory-profile-writer.ts")],bundle:true,platform:"node",format:"esm",write:false,target:"node22"});const loaded=await import(`data:text/javascript;base64,${Buffer.from(built.outputFiles[0].contents).toString("base64")}`);writer={...loaded,writeNativeDirectoryProfile:(db,input)=>loaded.writeNativeDirectoryProfile(db,{...input,mutationId:"70000000-0000-4000-8000-000000000001"})};return writer;}
async function seed(db){await db.prepare("UPDATE staff_users SET access_subject='access|org-test' WHERE id=?").bind(target.staffId).run();await db.prepare("INSERT INTO native_staff_admissions(staff_id,bound_access_subject,active,admitted_by) VALUES(?,'access|org-test',1,?)").bind(target.staffId,target.staffId).run();const staff=await first(db,"SELECT email,display_name FROM staff_users WHERE id=?",target.staffId);await db.prepare("INSERT INTO native_staff_profiles(staff_id,login_email,display_name) VALUES(?,?,?)").bind(target.staffId,staff.email,staff.display_name).run();await db.prepare("INSERT INTO native_business_areas(id,name,active) VALUES(?,?,1)").bind(target.businessAreaId,"Drone Services Staging").run();const seedIds=["seed-edit","seed-identity","seed-enroll"],perms=["directory.profile.edit","directory.identity.link","directory.enrollment.manage"];for(let i=0;i<3;i++)await db.prepare("INSERT INTO native_directory_grants(id,staff_id,permission,effect,scope_kind,business_area_id,active,granted_by) VALUES(?, ?,?,'allow','business_area',?,1,?)").bind(seedIds[i],target.staffId,perms[i],target.businessAreaId,target.staffId).run();
 const profile={name:"Relationship organization",generalEmail:"",generalPhone:"",addressLine1:"",addressLine2:"",city:"",state:"",postalCode:"",country:""},scopes=[{businessAreaId:target.businessAreaId,divisionId:null}],destination={sourceId:target.sourceId,sourceInstanceUUID:"d2f7acb8-375d-4da7-8d37-3f2455a3972b",applicationUUID:"150cb108-af37-4973-ab6e-f6d991a6e8c8",historyEpoch:"8c194c00-c7dd-4c6c-82ce-d391ef3fa998",origin:"https://pa-staging.ledgetoptechnologies.com",externalCanonicalId:target.recordId,expectedAuthorizationGeneration:"1"},admission=`admission-${target.recordId}`;await db.prepare("INSERT INTO native_directory_create_admissions(id,staff_id,bound_access_subject,record_id,record_kind,scopes_json,profile_json,destinations_json,issued_by) VALUES(?,?,?,?,'organization',?,?,?,?)").bind(admission,target.staffId,"access|org-test",target.recordId,JSON.stringify(scopes),JSON.stringify(profile),JSON.stringify([{...destination,expectedAuthorizationGeneration:undefined}],(_,v)=>v),target.staffId).run();const{writeNativeDirectoryProfile}=await loadWriter();const made=await writeNativeDirectoryProfile(db,{operation:"create",mutationId:target.recordId,createAdmissionId:admission,recordId:target.recordId,expectedLocalVersion:0,kind:"organization",profile,scopes,destinations:[destination],actor:{staffId:target.staffId,accessSubject:"access|org-test",admissionVersion:1,selectedGrantId:seedIds[0],loginEmail:staff.email,profileVersion:1,selectedIdentityGrantId:seedIds[1]}});assert.equal(made.status,"written");const command=made.commandIds[0];await db.batch([db.prepare("UPDATE project_alpha_directory_outbox SET state='leased',lease_token='test',lease_expires_at=?,attempts=attempts+1 WHERE command_id=?").bind(Date.now()+60000,command),db.prepare("UPDATE project_alpha_directory_outbox SET state='terminal',outcome_json='{}',lease_token=NULL,lease_expires_at=NULL WHERE command_id=? AND lease_token='test'").bind(command)]);for(const id of seedIds)await db.prepare("UPDATE native_directory_grants SET active=0 WHERE id=?").bind(id).run();}
async function input(db,phase="provision",provisionArtifact){const stamp=(await first(db,"SELECT strftime('%Y-%m-%dT%H:%M:%fZ','now') stamp")).stamp,n=phase==="provision"?"1":"2";return{schemaVersion:2,staging:STAGING_TARGET,phase,target,migrationNames,admission:await first(db,"SELECT * FROM native_staff_admissions WHERE staff_id=?",target.staffId),profile:await first(db,"SELECT * FROM native_staff_profiles WHERE staff_id=?",target.staffId),generation:await first(db,"SELECT * FROM native_directory_grant_generations WHERE staff_id=?",target.staffId),record:await first(db,"SELECT record_id,record_kind,current_version FROM operations_directory_records WHERE record_id=?",target.recordId),resourceScope:await first(db,"SELECT record_id,scope_kind,business_area_id,division_id,active FROM native_directory_resource_scopes WHERE record_id=?",target.recordId),grants:await all(db,"SELECT * FROM native_directory_grants WHERE staff_id=? ORDER BY id",target.staffId),history:await all(db,"SELECT * FROM native_directory_grant_history WHERE staff_id=? ORDER BY grant_id,grant_version",target.staffId),approval:{approvalId:`40000000-0000-4000-8000-00000000000${n}`,commandId:`50000000-0000-4000-8000-00000000000${n}`,grantIds:["60000000-0000-4000-8000-000000000001","60000000-0000-4000-8000-000000000002"],issuedAt:stamp,expiresAt:new Date(Date.parse(stamp)+3600000).toISOString(),executedAt:stamp},...(provisionArtifact?{provisionArtifact}:{})};}
test("exact organization authority is atomic across the current full schema and repeated activation", async () => {
  const mf = new Miniflare({ modules: true, script: "export default{fetch(){return new Response('ok')}}",
    d1Databases: { DB: `org-${crypto.randomUUID()}` } });
  try {
    const db = await mf.getD1Database("DB");
    await migrate(db);
    assert.deepEqual((await all(db, "SELECT name FROM d1_migrations ORDER BY name")).map(row => row.name), migrationNames);
    await seed(db);
    const provision = compileOrganizationRelationshipAuthority(await input(db), { root: reviewedRoot });
    await db.prepare("CREATE TRIGGER org_test_race BEFORE INSERT ON native_directory_grants WHEN NEW.id='60000000-0000-4000-8000-000000000002' BEGIN SELECT RAISE(ABORT,'org race');END").run();
    await assert.rejects(applyOrganizationRelationshipAuthority(db, provision, { target: STAGING_TARGET, root: reviewedRoot }), /org race/);
    assert.equal(await first(db, "SELECT approval_id FROM native_staff_bootstrap_approvals WHERE approval_id=?", provision.approval.approval_id), null);
    await db.prepare("DROP TRIGGER org_test_race").run();
    await applyOrganizationRelationshipAuthority(db, provision, { target: STAGING_TARGET, root: reviewedRoot });
    assert.deepEqual((await all(db, "SELECT permission,scope_kind,business_area_id,division_id,resource_id,active FROM native_directory_grants WHERE id IN (?,?) ORDER BY permission", ...provision.input.approval.grantIds)), [
      { permission: "directory.identity.link", scope_kind: "resource", business_area_id: null, division_id: null, resource_id: target.recordId, active: 1 },
      { permission: "directory.profile.edit", scope_kind: "resource", business_area_id: null, division_id: null, resource_id: target.recordId, active: 1 },
    ]);
    const revoke = compileOrganizationRelationshipAuthority(await input(db, "revoke", provision), { root: reviewedRoot });
    await applyOrganizationRelationshipAuthority(db, revoke, { target: STAGING_TARGET, root: reviewedRoot });
    const beforeHistory = await all(db, "SELECT * FROM native_directory_grant_history WHERE grant_id IN (?,?) ORDER BY grant_id,grant_version", ...provision.input.approval.grantIds);
    const repeatedInput = await input(db);
    repeatedInput.approval.approvalId = crypto.randomUUID();
    repeatedInput.approval.commandId = crypto.randomUUID();
    const repeated = compileOrganizationRelationshipAuthority(repeatedInput, { root: reviewedRoot });
    await db.prepare("CREATE TRIGGER org_test_reactivation_race BEFORE UPDATE ON native_directory_grants WHEN NEW.id='60000000-0000-4000-8000-000000000002' AND NEW.active=1 BEGIN SELECT RAISE(ABORT,'reactivation race');END").run();
    await assert.rejects(applyOrganizationRelationshipAuthority(db, repeated, { target: STAGING_TARGET, root: reviewedRoot }), /reactivation race/);
    assert.equal(await first(db, "SELECT approval_id FROM native_staff_bootstrap_approvals WHERE approval_id=?", repeated.approval.approval_id), null);
    assert.deepEqual(await all(db, "SELECT * FROM native_directory_grant_history WHERE grant_id IN (?,?) ORDER BY grant_id,grant_version", ...provision.input.approval.grantIds), beforeHistory);
    await db.prepare("DROP TRIGGER org_test_reactivation_race").run();
    await applyOrganizationRelationshipAuthority(db, repeated, { target: STAGING_TARGET, root: reviewedRoot });
    const repeatRevokeInput = await input(db, "revoke", repeated);
    repeatRevokeInput.approval.approvalId = crypto.randomUUID();
    repeatRevokeInput.approval.commandId = crypto.randomUUID();
    const repeatRevoke = compileOrganizationRelationshipAuthority(repeatRevokeInput, { root: reviewedRoot });
    await applyOrganizationRelationshipAuthority(db, repeatRevoke, { target: STAGING_TARGET, root: reviewedRoot });
    assert.deepEqual((await all(db, "SELECT active FROM native_directory_grants WHERE id IN (?,?) ORDER BY id", ...provision.input.approval.grantIds)).map(row => row.active), [0, 0]);
    const afterHistory = await all(db, "SELECT * FROM native_directory_grant_history WHERE grant_id IN (?,?) ORDER BY grant_id,grant_version", ...provision.input.approval.grantIds);
    assert.deepEqual(afterHistory.filter(row => row.grant_version <= 2), beforeHistory);
    for (const id of provision.input.approval.grantIds) {
      assert.deepEqual(afterHistory.filter(row => row.grant_id === id).map(row => [row.grant_version, row.active]), [[1, 1], [2, 0], [3, 1], [4, 0]]);
    }
  } finally { await mf.dispose(); }
}, 120000);
