import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

// Wrangler 4.118 can alternate between typed and comment-only Worker
// entrypoint bindings when the previous declaration imports the main module.
// Generate all configuration/runtime types with Wrangler, then normalize its
// entrypoint declarations into one deterministic, TypeScript-checked form.
const checkOnly = process.argv.includes("--check");
const strictVarsFalse = process.argv.includes("--strict-vars=false");
const appRoot = process.cwd();
const targetName = "worker-configuration.d.ts";
const probeName = `worker-configuration.typegen-${process.pid}.d.ts`;
const targetPath = resolve(appRoot, targetName);
const probePath = resolve(appRoot, probeName);
const configPath = resolve(appRoot, "wrangler.jsonc");
const wranglerCli = resolve(appRoot, "node_modules", "wrangler", "bin", "wrangler.js");

const configSource = readFileSync(configPath, "utf8");
const mainMatch = configSource.match(/^\s*"main"\s*:\s*"([^"]+)"/m);
if (!mainMatch) {
  throw new Error("wrangler.jsonc must declare a main Worker entrypoint.");
}
const mainFile = mainMatch[1].replaceAll("\\", "/");
const mainImport = `./${mainFile.replace(/\.(?:[cm]?[jt]sx?)$/, "")}`;
if (!existsSync(resolve(appRoot, mainFile))) {
  throw new Error(`Worker entrypoint does not exist: ${mainFile}`);
}

rmSync(probePath, { force: true });
try {
  const wranglerArgs = [wranglerCli, "types", probeName, "--config=wrangler.jsonc"];
  if (strictVarsFalse) {
    wranglerArgs.push("--strict-vars=false");
  }
  const generated = spawnSync(process.execPath, wranglerArgs, {
    cwd: appRoot,
    env: {
      ...process.env,
      WRANGLER_LOG_PATH: resolve(appRoot, ".wrangler", `typegen-${process.pid}.log`),
    },
    stdio: "inherit",
  });
  if (generated.error) {
    console.error(generated.error.message);
  }
  if (generated.status !== 0 || !existsSync(probePath)) {
    process.exitCode = generated.status || 1;
  } else {
    const generatedTypes = readFileSync(probePath, "utf8").replace(/\r\n/g, "\n");
    const durableClasses = [];
    let canonical = generatedTypes
      .replace(
        /^(\t[A-Z0-9_]+): Workflow \/\* ([A-Za-z_$][\w$]*) \*\/;$/gm,
        (_line, binding, className) =>
          `${binding}: Workflow<Parameters<import("${mainImport}").${className}['run']>[0]['payload']>;`,
      )
      .replace(
        /^(\t[A-Z0-9_]+): DurableObjectNamespace \/\* ([A-Za-z_$][\w$]*) \*\/;$/gm,
        (_line, binding, className) => {
          durableClasses.push(className);
          return `${binding}: DurableObjectNamespace<import("${mainImport}").${className}>;`;
        },
      );

    for (const match of canonical.matchAll(
      /DurableObjectNamespace<import\("[^"]+"\)\.([A-Za-z_$][\w$]*)>/g,
    )) {
      durableClasses.push(match[1]);
    }
    const durableNamespace = durableClasses.length
      ? `\t\tdurableNamespaces: ${[...new Set(durableClasses)]
          .sort()
          .map((name) => `"${name}"`)
          .join(" | ")};`
      : "";
    if (!canonical.includes("\tinterface GlobalProps {")) {
      canonical = canonical.replace(
        /declare namespace Cloudflare \{\n/,
        `declare namespace Cloudflare {\n\tinterface GlobalProps {\n\t\tmainModule: typeof import("${mainImport}");${durableNamespace ? `\n${durableNamespace}` : ""}\n\t}\n`,
      );
    } else if (durableNamespace && !canonical.includes("\t\tdurableNamespaces:")) {
      canonical = canonical.replace(
        /(\t\tmainModule: typeof import\("[^"]+"\);)/,
        `$1\n${durableNamespace}`,
      );
    }

    if (
      canonical.includes("Workflow /*") ||
      canonical.includes("DurableObjectNamespace /*") ||
      !canonical.includes(`mainModule: typeof import("${mainImport}")`)
    ) {
      throw new Error("Worker entrypoint declarations could not be normalized.");
    }

    const command = strictVarsFalse ? "wrangler types --strict-vars=false" : "wrangler types";
    const headerPattern =
      /^\/\/ Generated by Wrangler by running `[^`]+` \(hash: [a-zA-Z0-9]+\)$/m;
    if (!headerPattern.test(canonical)) {
      throw new Error("Wrangler generated an unrecognized declaration header.");
    }
    canonical = canonical.replace(
      headerPattern,
      `// Generated by Wrangler by running \`${command}\` (hash: __CONTENT_HASH__)`,
    );
    const contentHash = createHash("sha256").update(canonical).digest("hex").slice(0, 32);
    canonical = canonical.replace("__CONTENT_HASH__", contentHash);

    if (checkOnly) {
      const current = existsSync(targetPath)
        ? readFileSync(targetPath, "utf8").replace(/\r\n/g, "\n")
        : "";
      if (current !== canonical) {
        console.error("Worker types are out of date. Run npm run cf-typegen.");
        process.exitCode = 1;
      } else {
        console.log("Worker types are up to date.");
      }
    } else {
      writeFileSync(targetPath, canonical, "utf8");
      console.log(`Worker types written to ${targetName}.`);
    }
  }
} finally {
  rmSync(probePath, { force: true });
}
